// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for dfs.contests (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml
package com.statapi.dfs;

import com.statapi.JsonValue;

public record DFSContest(
    Long id,
    Long externalId,
    Long slateId,
    Integer contestType,
    Integer entryCount,
    Integer entryFee,
    Boolean guaranteed,
    Integer maxEntries,
    Integer maxEntriesPerUser,
    String name,
    Integer prizePool
) {

    public static DFSContest fromJson(JsonValue json) {
        return new DFSContest(
            json.get("id").asLong(),
            json.get("external_id").asLong(),
            json.get("slate_id").asLong(),
            json.get("contest_type").asInt(),
            json.get("entry_count").asInt(),
            json.get("entry_fee").asInt(),
            json.get("guaranteed").asBoolean(),
            json.get("max_entries").asInt(),
            json.get("max_entries_per_user").asInt(),
            json.get("name").asString(),
            json.get("prize_pool").asInt()
        );
    }
}
