// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for dfs.contest_user_lineup_player_entries (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml
package com.statapi.dfs;

import java.util.LinkedHashMap;
import java.util.Map;

public final class DFSContestUserLineupPlayerEntriesListParams {

    private Long contestUserLineupId;
    private Long limit;
    private Long fromId;

    public DFSContestUserLineupPlayerEntriesListParams contestUserLineupId(Long contestUserLineupId) {
        this.contestUserLineupId = contestUserLineupId;
        return this;
    }

    public DFSContestUserLineupPlayerEntriesListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public DFSContestUserLineupPlayerEntriesListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (contestUserLineupId != null) {
            query.put("contest_user_lineup_id", String.valueOf(contestUserLineupId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
