// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for dfs.contests (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml
package com.statapi.dfs;

import java.util.LinkedHashMap;
import java.util.Map;

public final class DFSContestsListParams {

    private Long slateId;
    private Long limit;
    private Long fromId;

    public DFSContestsListParams slateId(Long slateId) {
        this.slateId = slateId;
        return this;
    }

    public DFSContestsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public DFSContestsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (slateId != null) {
            query.put("slate_id", String.valueOf(slateId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
