// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for dfs.contest_user_lineups (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml
package com.statapi.dfs;

import java.util.LinkedHashMap;
import java.util.Map;

public final class DFSContestUserLineupsListParams {

    private Long contestId;
    private Long contestUserId;
    private Long limit;
    private Long fromId;

    public DFSContestUserLineupsListParams contestId(Long contestId) {
        this.contestId = contestId;
        return this;
    }

    public DFSContestUserLineupsListParams contestUserId(Long contestUserId) {
        this.contestUserId = contestUserId;
        return this;
    }

    public DFSContestUserLineupsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public DFSContestUserLineupsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (contestId != null) {
            query.put("contest_id", String.valueOf(contestId));
        }
        if (contestUserId != null) {
            query.put("contest_user_id", String.valueOf(contestUserId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
