// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for dfs.contest_user_lineup_player_entries (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml
package com.statapi.dfs;

import com.statapi.JsonValue;

public record DFSContestUserLineupPlayerEntry(
    Long id,
    Long contestUserLineupId,
    Long slatePlayerId,
    Integer displayOrder,
    Double points,
    String rosterPosition
) {

    public static DFSContestUserLineupPlayerEntry fromJson(JsonValue json) {
        return new DFSContestUserLineupPlayerEntry(
            json.get("id").asLong(),
            json.get("contest_user_lineup_id").asLong(),
            json.get("slate_player_id").asLong(),
            json.get("display_order").asInt(),
            json.get("points").asDouble(),
            json.get("roster_position").asString()
        );
    }
}
