// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for dfs.slate_projection_sources (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml
package com.statapi.dfs;

import com.statapi.JsonValue;

public record DFSSlateProjectionSource(
    Long id,
    Long slateSettingId,
    String description,
    Integer displayOrder,
    Boolean enabled,
    String name,
    Integer sourceType
) {

    public static DFSSlateProjectionSource fromJson(JsonValue json) {
        return new DFSSlateProjectionSource(
            json.get("id").asLong(),
            json.get("slate_setting_id").asLong(),
            json.get("description").asString(),
            json.get("display_order").asInt(),
            json.get("enabled").asBoolean(),
            json.get("name").asString(),
            json.get("source_type").asInt()
        );
    }
}
