// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for dfs.slate_settings (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml
package com.statapi.dfs;

import com.statapi.JsonValue;

public record DFSSlateSetting(
    Long id,
    Long leagueId,
    Long operatorId,
    Integer contestType,
    String gameStyle,
    Integer gameType,
    String name,
    JsonValue settings
) {

    public static DFSSlateSetting fromJson(JsonValue json) {
        return new DFSSlateSetting(
            json.get("id").asLong(),
            json.get("league_id").asLong(),
            json.get("operator_id").asLong(),
            json.get("contest_type").asInt(),
            json.get("game_style").asString(),
            json.get("game_type").asInt(),
            json.get("name").asString(),
            json.get("settings")
        );
    }
}
