# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for nfl.coaching_staff_tenures (public API).
# Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

NFLCoachingStaffTenure = TypedDict(
    "NFLCoachingStaffTenure",
    {
        "id": int,
        "season_id": int,
        "team_id": int,
        "effective_date": str,
        "end_date": str | None,
        "first_name": str | None,
        "full_name": str,
        "is_interim": bool,
        "last_name": str | None,
        "position": str,
        "reason": str | None,
    },
)


class NFLCoachingStaffTenuresResource:
    _PATH = "/api/v1/nfl/coaching_staff_tenures"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, team_id: int | None = None, season_id: int | None = None, position: str | None = None, limit: int | None = None, from_id: int | None = None) -> Page[NFLCoachingStaffTenure]:
        body, quota = self._transport.request(self._PATH, {
            "team_id": team_id,
            "season_id": season_id,
            "position": position,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[NFLCoachingStaffTenure] = body["coaching_staff_tenures"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> NFLCoachingStaffTenure:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: NFLCoachingStaffTenure = body
        return row

    def iter(self, *, team_id: int | None = None, season_id: int | None = None, position: str | None = None, limit: int | None = None) -> Iterator[NFLCoachingStaffTenure]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(team_id=team_id, season_id=season_id, position=position, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
