# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for nfl.depth_chart_entries (public API).
# Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

NFLDepthChartEntry = TypedDict(
    "NFLDepthChartEntry",
    {
        "id": int,
        "player_id": int,
        "snapshot_id": int,
        "depth_order": int,
        "depth_position": str,
        "formation": str | None,
        "jersey_number": int | None,
        "position": str,
    },
)


class NFLDepthChartEntriesResource:
    _PATH = "/api/v1/nfl/depth_chart_entries"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, snapshot_id: int | None = None, player_id: int | None = None, position: str | None = None, limit: int | None = None, from_id: int | None = None) -> Page[NFLDepthChartEntry]:
        body, quota = self._transport.request(self._PATH, {
            "snapshot_id": snapshot_id,
            "player_id": player_id,
            "position": position,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[NFLDepthChartEntry] = body["depth_chart_entries"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> NFLDepthChartEntry:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: NFLDepthChartEntry = body
        return row

    def iter(self, *, snapshot_id: int | None = None, player_id: int | None = None, position: str | None = None, limit: int | None = None) -> Iterator[NFLDepthChartEntry]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(snapshot_id=snapshot_id, player_id=player_id, position=position, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
