# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for nfl.draft_picks (public API).
# Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

NFLDraftPick = TypedDict(
    "NFLDraftPick",
    {
        "id": int,
        "cfb_player_id": str | None,
        "gsis_id": str,
        "pfr_player_id": str,
        "player_id": int,
        "team_id": int,
        "age": int | None,
        "allpro_count": int,
        "car_av": int | None,
        "career_to_year": int | None,
        "category": str,
        "college": str,
        "def_ints": int,
        "def_sacks": float,
        "def_solo_tackles": int,
        "dr_av": int | None,
        "games_played": int,
        "is_hof": bool,
        "pass_attempts": int,
        "pass_completions": int,
        "pass_ints": int,
        "pass_tds": int,
        "pass_yds": int,
        "pfr_player_name": str | None,
        "pick": int,
        "position": str,
        "probowl_count": int,
        "rec_tds": int,
        "rec_yds": int,
        "receptions": int,
        "round": int,
        "rush_atts": int,
        "rush_tds": int,
        "rush_yds": int,
        "season": int,
        "seasons_started": int,
        "side": str,
        "w_av": int | None,
    },
)


class NFLDraftPicksResource:
    _PATH = "/api/v1/nfl/draft_picks"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, season: int | None = None, round: int | None = None, team_id: int | None = None, player_id: int | None = None, position: str | None = None, limit: int | None = None, from_id: int | None = None) -> Page[NFLDraftPick]:
        body, quota = self._transport.request(self._PATH, {
            "season": season,
            "round": round,
            "team_id": team_id,
            "player_id": player_id,
            "position": position,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[NFLDraftPick] = body["draft_picks"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> NFLDraftPick:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: NFLDraftPick = body
        return row

    def iter(self, *, season: int | None = None, round: int | None = None, team_id: int | None = None, player_id: int | None = None, position: str | None = None, limit: int | None = None) -> Iterator[NFLDraftPick]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(season=season, round=round, team_id=team_id, player_id=player_id, position=position, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
