# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for nfl.game_player_ngs_rushings (public API).
# Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

NFLGamePlayerNgsRushing = TypedDict(
    "NFLGamePlayerNgsRushing",
    {
        "id": int,
        "game_id": int,
        "player_gsis_id": str,
        "player_id": int,
        "team_id": int,
        "avg_rush_yds": float | None,
        "avg_time_to_los": float | None,
        "efficiency": float | None,
        "expected_rush_yds": float | None,
        "percent_attempts_gte_eight_defenders": float | None,
        "rush_attempts": int | None,
        "rush_pct_over_expected": float | None,
        "rush_tds": int | None,
        "rush_yds": int | None,
        "rush_yds_over_expected": float | None,
        "rush_yds_over_expected_per_att": float | None,
        "season": int,
        "season_type": str,
        "week": int,
    },
)


class NFLGamePlayerNgsRushingsResource:
    _PATH = "/api/v1/nfl/game_player_ngs_rushings"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, game_id: int | None = None, player_id: int | None = None, team_id: int | None = None, season: int | None = None, week: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[NFLGamePlayerNgsRushing]:
        body, quota = self._transport.request(self._PATH, {
            "game_id": game_id,
            "player_id": player_id,
            "team_id": team_id,
            "season": season,
            "week": week,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[NFLGamePlayerNgsRushing] = body["game_player_ngs_rushings"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> NFLGamePlayerNgsRushing:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: NFLGamePlayerNgsRushing = body
        return row

    def iter(self, *, game_id: int | None = None, player_id: int | None = None, team_id: int | None = None, season: int | None = None, week: int | None = None, limit: int | None = None) -> Iterator[NFLGamePlayerNgsRushing]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(game_id=game_id, player_id=player_id, team_id=team_id, season=season, week=week, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
