# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for nfl.player_news (public API).
# Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import Any, TypedDict

from ..page import Page
from ..transport import HttpTransport

NFLPlayerNew = TypedDict(
    "NFLPlayerNew",
    {
        "id": int,
        "external_id": str | None,
        "player_id": int | None,
        "team_id": int | None,
        "ai_processed": bool,
        "analysis": str | None,
        "author": str | None,
        "category": str | None,
        "content": str | None,
        "description": str | None,
        "link": str | None,
        "news_time": str,
        "priority": int,
        "situational_impact": dict[str, Any] | None,
        "source": str | None,
        "title": str,
    },
)


class NFLPlayerNewsResource:
    _PATH = "/api/v1/nfl/player_news"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, player_id: int | None = None, team_id: int | None = None, category: str | None = None, source: str | None = None, news_time: str | None = None, limit: int | None = None, from_id: int | None = None) -> Page[NFLPlayerNew]:
        body, quota = self._transport.request(self._PATH, {
            "player_id": player_id,
            "team_id": team_id,
            "category": category,
            "source": source,
            "news_time": news_time,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[NFLPlayerNew] = body["player_news"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> NFLPlayerNew:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: NFLPlayerNew = body
        return row

    def iter(self, *, player_id: int | None = None, team_id: int | None = None, category: str | None = None, source: str | None = None, news_time: str | None = None, limit: int | None = None) -> Iterator[NFLPlayerNew]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(player_id=player_id, team_id=team_id, category=category, source=source, news_time=news_time, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
