# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for dfs.contest_user_lineup_player_entries (public API).
# Source: schema/api/groups/public.yml + schema/model/dfs/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

DFSContestUserLineupPlayerEntry = TypedDict(
    "DFSContestUserLineupPlayerEntry",
    {
        "id": int,
        "contest_user_lineup_id": int,
        "slate_player_id": int,
        "display_order": int,
        "points": float | None,
        "roster_position": str,
    },
)


class DFSContestUserLineupPlayerEntriesResource:
    _PATH = "/api/v1/dfs/contest_user_lineup_player_entries"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, contest_user_lineup_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[DFSContestUserLineupPlayerEntry]:
        body, quota = self._transport.request(self._PATH, {
            "contest_user_lineup_id": contest_user_lineup_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[DFSContestUserLineupPlayerEntry] = body["contest_user_lineup_player_entries"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> DFSContestUserLineupPlayerEntry:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: DFSContestUserLineupPlayerEntry = body
        return row

    def iter(self, *, contest_user_lineup_id: int | None = None, limit: int | None = None) -> Iterator[DFSContestUserLineupPlayerEntry]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(contest_user_lineup_id=contest_user_lineup_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
