# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for dfs.team_stats (public API).
# Source: schema/api/groups/public.yml + schema/model/dfs/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import Any, TypedDict

from ..page import Page
from ..transport import HttpTransport

DFSTeamStat = TypedDict(
    "DFSTeamStat",
    {
        "id": int,
        "game_id": int,
        "league_id": int,
        "team_id": int,
        "data": dict[str, Any],
    },
)


class DFSTeamStatsResource:
    _PATH = "/api/v1/dfs/team_stats"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, limit: int | None = None, from_id: int | None = None) -> Page[DFSTeamStat]:
        body, quota = self._transport.request(self._PATH, {
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[DFSTeamStat] = body["team_stats"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> DFSTeamStat:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: DFSTeamStat = body
        return row

    def iter(self, *, limit: int | None = None) -> Iterator[DFSTeamStat]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
