// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for pga.course_hole_stats (public API).
// Source: schema/api/groups/public.yml + schema/model/golf/*.yml
package com.statapi.pga;

import java.util.LinkedHashMap;
import java.util.Map;

public final class PGACourseHoleStatsListParams {

    private Long tournamentId;
    private Long limit;
    private Long fromId;

    public PGACourseHoleStatsListParams tournamentId(Long tournamentId) {
        this.tournamentId = tournamentId;
        return this;
    }

    public PGACourseHoleStatsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public PGACourseHoleStatsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (tournamentId != null) {
            query.put("tournament_id", String.valueOf(tournamentId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
