// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for pga.player_news (public API).
// Source: schema/api/groups/public.yml + schema/model/golf/*.yml
package com.statapi.pga;

import java.util.LinkedHashMap;
import java.util.Map;

public final class PGAPlayerNewsListParams {

    private Long playerId;
    private Long tournamentId;
    private String newsTime;
    private Long limit;
    private Long fromId;

    public PGAPlayerNewsListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public PGAPlayerNewsListParams tournamentId(Long tournamentId) {
        this.tournamentId = tournamentId;
        return this;
    }

    public PGAPlayerNewsListParams newsTime(String newsTime) {
        this.newsTime = newsTime;
        return this;
    }

    public PGAPlayerNewsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public PGAPlayerNewsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (tournamentId != null) {
            query.put("tournament_id", String.valueOf(tournamentId));
        }
        if (newsTime != null) {
            query.put("news_time", String.valueOf(newsTime));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
