// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for pga.players (public API).
// Source: schema/api/groups/public.yml + schema/model/golf/*.yml
package com.statapi.pga;

import com.statapi.JsonValue;

public record PGAPlayer(
    Long id,
    String leagueId,
    Integer leaguePlayerId,
    String birthCity,
    String birthCountry,
    String birthDate,
    String birthState,
    String college,
    String country,
    String firstName,
    String fullName,
    String lastName,
    Integer pgaDebutYear,
    String photoUrl,
    String shortName,
    String swings
) {

    public static PGAPlayer fromJson(JsonValue json) {
        return new PGAPlayer(
            json.get("id").asLong(),
            json.get("league_id").asString(),
            json.get("league_player_id").asInt(),
            json.get("birth_city").asString(),
            json.get("birth_country").asString(),
            json.get("birth_date").asString(),
            json.get("birth_state").asString(),
            json.get("college").asString(),
            json.get("country").asString(),
            json.get("first_name").asString(),
            json.get("full_name").asString(),
            json.get("last_name").asString(),
            json.get("pga_debut_year").asInt(),
            json.get("photo_url").asString(),
            json.get("short_name").asString(),
            json.get("swings").asString()
        );
    }
}
