// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for pga.player_shots (public API).
// Source: schema/api/groups/public.yml + schema/model/golf/*.yml
package com.statapi.pga;

import com.statapi.JsonValue;

public record PGAPlayerShot(
    Long id,
    Long playerId,
    Long tournamentId,
    Double apexHeight,
    Double ballSpeed,
    Double carryDistance,
    Double clubSpeed,
    Double distanceRemainingYards,
    Double distanceYards,
    Boolean finalStroke,
    String fromLocation,
    String fromLocationCode,
    Double fromX,
    Double fromY,
    Double fromZ,
    Integer holeNumber,
    Double launchAngle,
    Double launchSpin,
    Integer par,
    String playByPlay,
    Integer roundNumber,
    Integer shotNumber,
    Double smashFactor,
    Double spinAxis,
    String strokeType,
    String toLocation,
    String toLocationCode,
    Double toX,
    Double toY,
    Double toZ
) {

    public static PGAPlayerShot fromJson(JsonValue json) {
        return new PGAPlayerShot(
            json.get("id").asLong(),
            json.get("player_id").asLong(),
            json.get("tournament_id").asLong(),
            json.get("apex_height").asDouble(),
            json.get("ball_speed").asDouble(),
            json.get("carry_distance").asDouble(),
            json.get("club_speed").asDouble(),
            json.get("distance_remaining_yards").asDouble(),
            json.get("distance_yards").asDouble(),
            json.get("final_stroke").asBoolean(),
            json.get("from_location").asString(),
            json.get("from_location_code").asString(),
            json.get("from_x").asDouble(),
            json.get("from_y").asDouble(),
            json.get("from_z").asDouble(),
            json.get("hole_number").asInt(),
            json.get("launch_angle").asDouble(),
            json.get("launch_spin").asDouble(),
            json.get("par").asInt(),
            json.get("play_by_play").asString(),
            json.get("round_number").asInt(),
            json.get("shot_number").asInt(),
            json.get("smash_factor").asDouble(),
            json.get("spin_axis").asDouble(),
            json.get("stroke_type").asString(),
            json.get("to_location").asString(),
            json.get("to_location_code").asString(),
            json.get("to_x").asDouble(),
            json.get("to_y").asDouble(),
            json.get("to_z").asDouble()
        );
    }
}
