// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for pga.tournaments (public API).
// Source: schema/api/groups/public.yml + schema/model/golf/*.yml
package com.statapi.pga;

import java.util.LinkedHashMap;
import java.util.Map;

public final class PGATournamentsListParams {

    private Long seasonId;
    private Long tourId;
    private Long limit;
    private Long fromId;

    public PGATournamentsListParams seasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    public PGATournamentsListParams tourId(Long tourId) {
        this.tourId = tourId;
        return this;
    }

    public PGATournamentsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public PGATournamentsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (seasonId != null) {
            query.put("season_id", String.valueOf(seasonId));
        }
        if (tourId != null) {
            query.put("tour_id", String.valueOf(tourId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
