// DO NOT EDIT — generated by generate-sdk-smoke.ts
//
// Live smoke for @stat-api/client. Runs six probes against STAT_API_BASE_URL
// (default https://api.stat-api.com) with STAT_API_KEY. Run: bun smoke/smoke.ts
import { StatApi, AuthenticationError } from '../src/index.js';
import { parseQuota } from '../src/core/client.js';

// The SDK is intentionally free of node/bun type deps; the smoke stays the same
// way — env + exit go through guarded globalThis access so it typechecks under
// the library's own strict, node-types-free tsconfig.
function env(name: string): string | undefined {
  return (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env?.[name];
}
function exit(code: number): void {
  const proc = (globalThis as { process?: { exit?: (n: number) => never } }).process;
  if (proc && proc.exit) proc.exit(code);
}

const BASE_URL = env('STAT_API_BASE_URL') ?? 'https://api.stat-api.com';
const KEY = env('STAT_API_KEY');

let failures = 0;
function pass(id: string, msg: string): void { console.log('PASS ' + id + '  ' + msg); }
function fail(id: string, msg: string): void { failures++; console.log('FAIL ' + id + '  ' + msg); }

async function main(): Promise<number> {
  if (!KEY) { console.error('STAT_API_KEY is required'); return 2; }
  const api = new StatApi({ apiKey: KEY, baseUrl: BASE_URL });

  // probe1 — plain list
  let firstId: number | null = null;
  try {
    const p = await api.nba.teams.list({ limit: 2 });
    if (p.teams.length >= 1) { firstId = p.teams[0].id; pass('probe1-list', 'nba.teams limit=2 -> ' + p.teams.length + ' rows'); }
    else fail('probe1-list', 'nba.teams returned 0 rows');
  } catch (e) { fail('probe1-list', String(e)); }

  // probe2 — required-filter-set table via smoke params
  try {
    const p = await api.dfs.contest_users.list({ operator_id: 1 });
    if (Array.isArray(p.contest_users)) pass('probe2-required-set', 'dfs.contest_users via smoke params -> ' + p.contest_users.length + ' rows');
    else fail('probe2-required-set', 'response missing rows array');
  } catch (e) { fail('probe2-required-set', String(e)); }

  // probe3 — get(id)
  try {
    if (firstId === null) fail('probe3-get', 'no id from probe1');
    else {
      const row = await api.nba.teams.get(firstId);
      if (row.id === firstId) pass('probe3-get', 'get(' + firstId + ') ok');
      else fail('probe3-get', 'id mismatch ' + row.id);
    }
  } catch (e) { fail('probe3-get', String(e)); }

  // probe4 — two-page keyset walk
  try {
    const p1 = await api.nba.teams.list({ limit: 2 });
    const cursor = p1.next_from_id;
    if (cursor === null) fail('probe4-paginate', 'page1 next_from_id is null');
    else {
      const p2 = await api.nba.teams.list({ limit: 2, from_id: cursor });
      if (p2.teams.length >= 1 && p2.teams.every(r => r.id > cursor)) pass('probe4-paginate', 'page2 ids advance past ' + cursor);
      else fail('probe4-paginate', 'page2 did not advance: ' + p2.teams.map(r => r.id).join(','));
    }
  } catch (e) { fail('probe4-paginate', String(e)); }

  // probe5 — bad key -> AuthenticationError
  try {
    const bad = new StatApi({ apiKey: 'sdb_bad_00000000000000000000000000000000', baseUrl: BASE_URL });
    await bad.nba.teams.list({ limit: 2 });
    fail('probe5-auth', 'bad key did not raise');
  } catch (e) {
    if (e instanceof AuthenticationError) pass('probe5-auth', 'bad key -> AuthenticationError');
    else fail('probe5-auth', 'wrong error type: ' + (e instanceof Error ? e.constructor.name : String(e)));
  }

  // probe6 — quota headers. The TS list() does not surface quota like the other
  // four SDKs' Page<T>; bridge via the SDK's own parseQuota on the same request.
  try {
    const resp = await fetch(BASE_URL + '/api/v1/nba/teams?limit=2', { headers: { Authorization: 'Bearer ' + KEY } });
    const quota = parseQuota(resp.headers);
    if (quota !== null) pass('probe6-quota', 'quota surfaced (limit=' + quota.limit + ')');
    else fail('probe6-quota', 'no quota headers on list response');
  } catch (e) { fail('probe6-quota', String(e)); }

  return failures === 0 ? 0 : 1;
}

if ((import.meta as { main?: boolean }).main) {
  main().then(exit).catch(e => { console.error(e); exit(2); });
}
