// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// Resource accessor for the polymarket league (public API).
package com.statapi.polymarket;

import com.statapi.Http;

public final class PolymarketApi {

    private final PolymarketEventsResource events;
    private final PolymarketSportsResource sports;
    private final PolymarketTokensResource tokens;
    private final PolymarketMarketsResource markets;
    private final PolymarketCandlesResource candles;
    private final PolymarketMarketSnapshotsResource marketSnapshots;
    private final PolymarketOrderBookSnapshotsResource orderBookSnapshots;
    private final PolymarketPriceHistoriesResource priceHistories;
    private final PolymarketPublicTradesResource publicTrades;
    private final PolymarketTokenSnapshotsResource tokenSnapshots;

    public PolymarketApi(Http http) {
        this.events = new PolymarketEventsResource(http);
        this.sports = new PolymarketSportsResource(http);
        this.tokens = new PolymarketTokensResource(http);
        this.markets = new PolymarketMarketsResource(http);
        this.candles = new PolymarketCandlesResource(http);
        this.marketSnapshots = new PolymarketMarketSnapshotsResource(http);
        this.orderBookSnapshots = new PolymarketOrderBookSnapshotsResource(http);
        this.priceHistories = new PolymarketPriceHistoriesResource(http);
        this.publicTrades = new PolymarketPublicTradesResource(http);
        this.tokenSnapshots = new PolymarketTokenSnapshotsResource(http);
    }

    public PolymarketEventsResource events() {
        return events;
    }

    public PolymarketSportsResource sports() {
        return sports;
    }

    public PolymarketTokensResource tokens() {
        return tokens;
    }

    public PolymarketMarketsResource markets() {
        return markets;
    }

    public PolymarketCandlesResource candles() {
        return candles;
    }

    public PolymarketMarketSnapshotsResource marketSnapshots() {
        return marketSnapshots;
    }

    public PolymarketOrderBookSnapshotsResource orderBookSnapshots() {
        return orderBookSnapshots;
    }

    public PolymarketPriceHistoriesResource priceHistories() {
        return priceHistories;
    }

    public PolymarketPublicTradesResource publicTrades() {
        return publicTrades;
    }

    public PolymarketTokenSnapshotsResource tokenSnapshots() {
        return tokenSnapshots;
    }
}
