// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for polymarket.tokens (public API).
// Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml
package com.statapi.polymarket;

import com.statapi.JsonValue;

public record PolymarketToken(
    Long id,
    Long eventId,
    Long marketId,
    String tokenId,
    Integer finalPriceBps,
    String outcome,
    Integer outcomeIndex,
    Integer priceBps,
    Boolean winner
) {

    public static PolymarketToken fromJson(JsonValue json) {
        return new PolymarketToken(
            json.get("id").asLong(),
            json.get("event_id").asLong(),
            json.get("market_id").asLong(),
            json.get("token_id").asString(),
            json.get("final_price_bps").asInt(),
            json.get("outcome").asString(),
            json.get("outcome_index").asInt(),
            json.get("price_bps").asInt(),
            json.get("winner").asBoolean()
        );
    }
}
