// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for polymarket.price_histories (public API).
// Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml
package com.statapi.polymarket;

import java.util.LinkedHashMap;
import java.util.Map;

public final class PolymarketPriceHistoriesListParams {

    private String tokenId;
    private Long marketId;
    private Integer intervalSeconds;
    private Long limit;
    private Long fromId;

    public PolymarketPriceHistoriesListParams tokenId(String tokenId) {
        this.tokenId = tokenId;
        return this;
    }

    public PolymarketPriceHistoriesListParams marketId(Long marketId) {
        this.marketId = marketId;
        return this;
    }

    public PolymarketPriceHistoriesListParams intervalSeconds(Integer intervalSeconds) {
        this.intervalSeconds = intervalSeconds;
        return this;
    }

    public PolymarketPriceHistoriesListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public PolymarketPriceHistoriesListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (tokenId != null) {
            query.put("token_id", String.valueOf(tokenId));
        }
        if (marketId != null) {
            query.put("market_id", String.valueOf(marketId));
        }
        if (intervalSeconds != null) {
            query.put("interval_seconds", String.valueOf(intervalSeconds));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
