// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for polymarket.public_trades (public API).
// Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml
package com.statapi.polymarket;

import com.statapi.JsonValue;

public record PolymarketPublicTrade(
    Long id,
    Long marketId,
    String tokenId,
    String tradeId,
    String makerAddress,
    Integer priceBps,
    String side,
    Long size,
    String takerAddress,
    String tradedAt
) {

    public static PolymarketPublicTrade fromJson(JsonValue json) {
        return new PolymarketPublicTrade(
            json.get("id").asLong(),
            json.get("market_id").asLong(),
            json.get("token_id").asString(),
            json.get("trade_id").asString(),
            json.get("maker_address").asString(),
            json.get("price_bps").asInt(),
            json.get("side").asString(),
            json.get("size").asLong(),
            json.get("taker_address").asString(),
            json.get("traded_at").asString()
        );
    }
}
