// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for polymarket.markets (public API).
// Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml
package com.statapi.polymarket;

import java.util.LinkedHashMap;
import java.util.Map;

public final class PolymarketMarketsListParams {

    private Long eventId;
    private Long competitionId;
    private String status;
    private Boolean active;
    private Long limit;
    private Long fromId;

    public PolymarketMarketsListParams eventId(Long eventId) {
        this.eventId = eventId;
        return this;
    }

    public PolymarketMarketsListParams competitionId(Long competitionId) {
        this.competitionId = competitionId;
        return this;
    }

    public PolymarketMarketsListParams status(String status) {
        this.status = status;
        return this;
    }

    public PolymarketMarketsListParams active(Boolean active) {
        this.active = active;
        return this;
    }

    public PolymarketMarketsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public PolymarketMarketsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (eventId != null) {
            query.put("event_id", String.valueOf(eventId));
        }
        if (competitionId != null) {
            query.put("competition_id", String.valueOf(competitionId));
        }
        if (status != null) {
            query.put("status", String.valueOf(status));
        }
        if (active != null) {
            query.put("active", String.valueOf(active));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
