// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for polymarket.order_book_snapshots (public API).
// Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml
package com.statapi.polymarket;

import java.util.LinkedHashMap;
import java.util.Map;

public final class PolymarketOrderBookSnapshotsListParams {

    private Long marketId;
    private String tokenId;
    private Long limit;
    private Long fromId;

    public PolymarketOrderBookSnapshotsListParams marketId(Long marketId) {
        this.marketId = marketId;
        return this;
    }

    public PolymarketOrderBookSnapshotsListParams tokenId(String tokenId) {
        this.tokenId = tokenId;
        return this;
    }

    public PolymarketOrderBookSnapshotsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public PolymarketOrderBookSnapshotsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (marketId != null) {
            query.put("market_id", String.valueOf(marketId));
        }
        if (tokenId != null) {
            query.put("token_id", String.valueOf(tokenId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
