// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for polymarket.price_histories (public API).
// Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml
package com.statapi.polymarket;

import com.statapi.JsonValue;

public record PolymarketPriceHistory(
    Long id,
    Long marketId,
    String tokenId,
    Integer closeBps,
    Integer highBps,
    Integer intervalSeconds,
    Integer lowBps,
    Integer openBps,
    String periodStart,
    Long volume
) {

    public static PolymarketPriceHistory fromJson(JsonValue json) {
        return new PolymarketPriceHistory(
            json.get("id").asLong(),
            json.get("market_id").asLong(),
            json.get("token_id").asString(),
            json.get("close_bps").asInt(),
            json.get("high_bps").asInt(),
            json.get("interval_seconds").asInt(),
            json.get("low_bps").asInt(),
            json.get("open_bps").asInt(),
            json.get("period_start").asString(),
            json.get("volume").asLong()
        );
    }
}
