// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for polymarket.market_snapshots (public API).
// Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml
package com.statapi.polymarket;

import com.statapi.JsonValue;

public record PolymarketMarketSnapshot(
    Long id,
    String conditionId,
    Long marketId,
    Integer bestAskBps,
    Integer bestBidBps,
    String capturedAt,
    Integer lastTradePriceBps,
    Long liquidity,
    Long volume
) {

    public static PolymarketMarketSnapshot fromJson(JsonValue json) {
        return new PolymarketMarketSnapshot(
            json.get("id").asLong(),
            json.get("condition_id").asString(),
            json.get("market_id").asLong(),
            json.get("best_ask_bps").asInt(),
            json.get("best_bid_bps").asInt(),
            json.get("captured_at").asString(),
            json.get("last_trade_price_bps").asInt(),
            json.get("liquidity").asLong(),
            json.get("volume").asLong()
        );
    }
}
