# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for mlb.game_lines (public API).
# Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

MLBGameLine = TypedDict(
    "MLBGameLine",
    {
        "id": int,
        "game_id": int,
        "operator_id": int,
        "season_id": int,
        "captured_at": str,
        "implied_away_score": float | None,
        "implied_away_win_pct": float | None,
        "implied_home_score": float | None,
        "implied_home_win_pct": float | None,
        "is_opening": bool,
        "moneyline_away": int | None,
        "moneyline_home": int | None,
        "over_odds": int | None,
        "spread": float | None,
        "spread_away_odds": int | None,
        "spread_home_odds": int | None,
        "total": float | None,
        "under_odds": int | None,
    },
)


class MLBGameLinesResource:
    _PATH = "/api/v1/mlb/game_lines"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, game_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[MLBGameLine]:
        body, quota = self._transport.request(self._PATH, {
            "game_id": game_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[MLBGameLine] = body["game_lines"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> MLBGameLine:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: MLBGameLine = body
        return row

    def iter(self, *, game_id: int | None = None, limit: int | None = None) -> Iterator[MLBGameLine]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(game_id=game_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
