# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for mlb.game_team_rosters (public API).
# Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

MLBGameTeamRoster = TypedDict(
    "MLBGameTeamRoster",
    {
        "id": int,
        "game_id": int,
        "player_id": int,
        "team_id": int,
        "batting_order": int | None,
        "comment": str | None,
        "day": int,
        "position": str | None,
        "starter": bool,
        "status": str | None,
    },
)


class MLBGameTeamRostersResource:
    _PATH = "/api/v1/mlb/game_team_rosters"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, game_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[MLBGameTeamRoster]:
        body, quota = self._transport.request(self._PATH, {
            "game_id": game_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[MLBGameTeamRoster] = body["game_team_rosters"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> MLBGameTeamRoster:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: MLBGameTeamRoster = body
        return row

    def iter(self, *, game_id: int | None = None, limit: int | None = None) -> Iterator[MLBGameTeamRoster]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(game_id=game_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
