# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for mlb.park_factors (public API).
# Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

MLBParkFactor = TypedDict(
    "MLBParkFactor",
    {
        "id": int,
        "season_id": int,
        "venue_id": int,
        "basic_park_factor": float,
        "double_factor": float,
        "fly_ball_factor": float | None,
        "ground_ball_factor": float | None,
        "handedness_factor": float,
        "home_run_factor": float,
        "left_handed_factor": float,
        "right_handed_factor": float,
        "run_factor": float | None,
        "single_factor": float,
        "strikeout_factor": float,
        "triple_factor": float,
        "updated_date": str,
        "walk_factor": float,
        "years_of_data": int,
    },
)


class MLBParkFactorsResource:
    _PATH = "/api/v1/mlb/park_factors"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, venue_id: int | None = None, season_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[MLBParkFactor]:
        body, quota = self._transport.request(self._PATH, {
            "venue_id": venue_id,
            "season_id": season_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[MLBParkFactor] = body["park_factors"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> MLBParkFactor:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: MLBParkFactor = body
        return row

    def iter(self, *, venue_id: int | None = None, season_id: int | None = None, limit: int | None = None) -> Iterator[MLBParkFactor]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(venue_id=venue_id, season_id=season_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
