# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for mlb.players (public API).
# Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

MLBPlayer = TypedDict(
    "MLBPlayer",
    {
        "id": int,
        "league_id": str | None,
        "league_player_id": int,
        "team_id": int | None,
        "bats": str | None,
        "birth_city": str | None,
        "birth_country": str | None,
        "birth_date": str | None,
        "birth_state": str | None,
        "debut_date": str | None,
        "display_fi_last": str | None,
        "display_last_comma_first": str | None,
        "draft_number": str | None,
        "draft_round": str | None,
        "draft_year": str | None,
        "first_name": str,
        "full_name": str,
        "full_position_list": str | None,
        "height": int | None,
        "jersey": str | None,
        "last_name": str,
        "league_slug": str | None,
        "position_category": str | None,
        "primary_position": str,
        "profile_pic_url": str | None,
        "roster_status": str | None,
        "school": str | None,
        "throws": str | None,
        "weight": int | None,
    },
)


class MLBPlayersResource:
    _PATH = "/api/v1/mlb/players"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, team_id: int | None = None, roster_status: str | None = None, limit: int | None = None, from_id: int | None = None) -> Page[MLBPlayer]:
        body, quota = self._transport.request(self._PATH, {
            "team_id": team_id,
            "roster_status": roster_status,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[MLBPlayer] = body["players"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> MLBPlayer:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: MLBPlayer = body
        return row

    def iter(self, *, team_id: int | None = None, roster_status: str | None = None, limit: int | None = None) -> Iterator[MLBPlayer]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(team_id=team_id, roster_status=roster_status, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
