# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for mlb.player_awards (public API).
# Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

MLBPlayerAward = TypedDict(
    "MLBPlayerAward",
    {
        "id": int,
        "player_id": int,
        "season_id": int,
        "team_id": int | None,
        "award_date": str | None,
        "award_name": str,
        "award_type": str,
        "is_winner": bool,
    },
)


class MLBPlayerAwardsResource:
    _PATH = "/api/v1/mlb/player_awards"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, player_id: int | None = None, season_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[MLBPlayerAward]:
        body, quota = self._transport.request(self._PATH, {
            "player_id": player_id,
            "season_id": season_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[MLBPlayerAward] = body["player_awards"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> MLBPlayerAward:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: MLBPlayerAward = body
        return row

    def iter(self, *, player_id: int | None = None, season_id: int | None = None, limit: int | None = None) -> Iterator[MLBPlayerAward]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(player_id=player_id, season_id=season_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
