# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for mlb.season_player_stats (public API).
# Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

MLBSeasonPlayerStat = TypedDict(
    "MLBSeasonPlayerStat",
    {
        "id": int,
        "player_id": int,
        "season_id": int,
        "assists": int,
        "at_bats": int,
        "balls": int | None,
        "batters_faced": int,
        "batting_average": float,
        "blown_saves": int,
        "caught_stealing": int,
        "caught_stealing_by": int,
        "complete_games": int,
        "double_plays": int,
        "doubles": int,
        "earned_run_average": float,
        "earned_runs": int,
        "errors": int,
        "fielding_games": int,
        "fielding_games_started": int,
        "fielding_percentage": float,
        "fielding_position": str,
        "games_pitched": int,
        "games_played": int,
        "games_started": int,
        "games_started_pitching": int,
        "grounded_into_double_play": int,
        "hit_by_pitch": int,
        "hits": int,
        "hits_allowed": int,
        "hits_per_nine": float,
        "holds": int,
        "home_runs": int,
        "home_runs_allowed": int,
        "home_runs_per_nine": float,
        "innings_pitched": float,
        "intentional_walks": int | None,
        "left_on_base": int | None,
        "losses": int,
        "on_base_percentage": float,
        "on_base_plus_slugging": float,
        "passed_balls": int,
        "pitches_thrown": int | None,
        "plate_appearances": int,
        "putouts": int,
        "quality_starts": int | None,
        "runs": int,
        "runs_allowed": int,
        "runs_batted_in": int,
        "sacrifice_flies": int,
        "sacrifice_hits": int,
        "save_opportunities": int,
        "saves": int,
        "shutouts": int,
        "singles": int | None,
        "slugging_percentage": float,
        "stolen_bases": int,
        "stolen_bases_allowed": int,
        "strikeouts": int,
        "strikeouts_per_nine": float,
        "strikeouts_pitched": int,
        "strikes": int | None,
        "total_bases": int | None,
        "total_chances": int,
        "triples": int,
        "walks": int,
        "walks_allowed": int,
        "walks_per_nine": float,
        "whip": float,
        "wins": int,
    },
)


class MLBSeasonPlayerStatsResource:
    _PATH = "/api/v1/mlb/season_player_stats"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, season_id: int | None = None, player_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[MLBSeasonPlayerStat]:
        body, quota = self._transport.request(self._PATH, {
            "season_id": season_id,
            "player_id": player_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[MLBSeasonPlayerStat] = body["season_player_stats"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> MLBSeasonPlayerStat:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: MLBSeasonPlayerStat = body
        return row

    def iter(self, *, season_id: int | None = None, player_id: int | None = None, limit: int | None = None) -> Iterator[MLBSeasonPlayerStat]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(season_id=season_id, player_id=player_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
