# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for mlb.season_team_stats (public API).
# Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

MLBSeasonTeamStat = TypedDict(
    "MLBSeasonTeamStat",
    {
        "id": int,
        "season_id": int,
        "team_id": int,
        "at_bats": int,
        "batting_average": float,
        "blown_saves": int,
        "caught_stealing": int,
        "complete_games": int,
        "double_plays": int,
        "doubles": int,
        "earned_run_average": float,
        "earned_runs": int,
        "errors": int,
        "fielding_percentage": float,
        "games_played": int,
        "hits": int,
        "holds": int,
        "home_runs": int,
        "innings_pitched": float,
        "losses": int,
        "on_base_percentage": float,
        "on_base_plus_slugging": float,
        "runs_allowed": int,
        "runs_batted_in": int,
        "runs_scored": int,
        "save_opportunities": int,
        "saves": int,
        "shutouts": int,
        "slugging_percentage": float,
        "stolen_bases": int,
        "strikeouts": int,
        "ties": int,
        "triples": int,
        "walks": int,
        "whip": float,
        "wins": int,
    },
)


class MLBSeasonTeamStatsResource:
    _PATH = "/api/v1/mlb/season_team_stats"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, season_id: int | None = None, team_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[MLBSeasonTeamStat]:
        body, quota = self._transport.request(self._PATH, {
            "season_id": season_id,
            "team_id": team_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[MLBSeasonTeamStat] = body["season_team_stats"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> MLBSeasonTeamStat:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: MLBSeasonTeamStat = body
        return row

    def iter(self, *, season_id: int | None = None, team_id: int | None = None, limit: int | None = None) -> Iterator[MLBSeasonTeamStat]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(season_id=season_id, team_id=team_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
