# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for mlb.season_run_environments (public API).
# Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

MLBSeasonRunEnvironment = TypedDict(
    "MLBSeasonRunEnvironment",
    {
        "id": int,
        "season_id": int,
        "batting_average_on_balls_in_play": float,
        "fip_constant": float,
        "home_run_per_fly_ball": float,
        "runs_per_out": float,
        "runs_per_plate_appearance": float,
        "strikeout_rate": float,
        "updated_date": str,
        "walk_rate": float,
    },
)


class MLBSeasonRunEnvironmentsResource:
    _PATH = "/api/v1/mlb/season_run_environments"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, season_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[MLBSeasonRunEnvironment]:
        body, quota = self._transport.request(self._PATH, {
            "season_id": season_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[MLBSeasonRunEnvironment] = body["season_run_environments"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> MLBSeasonRunEnvironment:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: MLBSeasonRunEnvironment = body
        return row

    def iter(self, *, season_id: int | None = None, limit: int | None = None) -> Iterator[MLBSeasonRunEnvironment]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(season_id=season_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
