# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for mlb.venue_weathers (public API).
# Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

MLBVenueWeather = TypedDict(
    "MLBVenueWeather",
    {
        "id": int,
        "game_id": int,
        "venue_id": int,
        "air_density": float | None,
        "ball_carry_factor": float | None,
        "cloud_cover": float | None,
        "dew_point": float | None,
        "feels_like_temperature": float | None,
        "humidity": float | None,
        "is_dome": bool | None,
        "precipitation": float | None,
        "precipitation_probability": float | None,
        "pressure": float | None,
        "recorded_at": str | None,
        "roof_status": str | None,
        "temperature": float | None,
        "time_minutes": int,
        "uv_index": float | None,
        "visibility": float | None,
        "weather_condition": str | None,
        "weather_description": str | None,
        "wind_blowing_out": bool | None,
        "wind_component_out": float | None,
        "wind_direction": float | None,
        "wind_direction_relative": float | None,
        "wind_gust": float | None,
        "wind_speed": float | None,
    },
)


class MLBVenueWeathersResource:
    _PATH = "/api/v1/mlb/venue_weathers"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, game_id: int | None = None, venue_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[MLBVenueWeather]:
        body, quota = self._transport.request(self._PATH, {
            "game_id": game_id,
            "venue_id": venue_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[MLBVenueWeather] = body["venue_weathers"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> MLBVenueWeather:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: MLBVenueWeather = body
        return row

    def iter(self, *, game_id: int | None = None, venue_id: int | None = None, limit: int | None = None) -> Iterator[MLBVenueWeather]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(game_id=game_id, venue_id=venue_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
