// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// Resource accessor for the nba league (public API).
package com.statapi.nba;

import com.statapi.Http;

public final class NbaApi {

    private final NBASeasonsResource seasons;
    private final NBAStadiumsResource stadiums;
    private final NBARefereesResource referees;
    private final NBACoachingStaffsResource coachingStaffs;
    private final NBATeamsResource teams;
    private final NBAGamesResource games;
    private final NBAPlayersResource players;
    private final NBABroadcastersResource broadcasters;
    private final NBAOperatorTeamLookupsResource operatorTeamLookups;
    private final NBAPlayoffsResource playoffs;
    private final NBASeasonTeamStatsResource seasonTeamStats;
    private final NBATeamCoachingStaffsResource teamCoachingStaffs;
    private final NBATeamStandingsResource teamStandings;
    private final NBAGameBroadcastersResource gameBroadcasters;
    private final NBAGameLinesResource gameLines;
    private final NBAGamePeriodLinesResource gamePeriodLines;
    private final NBAGamePlayerPropsResource gamePlayerProps;
    private final NBAGamePlayerStatsResource gamePlayerStats;
    private final NBAGamePossessionsResource gamePossessions;
    private final NBAGameRefereesResource gameReferees;
    private final NBAGameTeamLineupStintsResource gameTeamLineupStints;
    private final NBAGameTeamRostersResource gameTeamRosters;
    private final NBAGameTeamStatsResource gameTeamStats;
    private final NBAOperatorPlayerLookupsResource operatorPlayerLookups;
    private final NBAPlayByPlaysResource playByPlays;
    private final NBAPlayerNewsResource playerNews;
    private final NBASeasonPlayerStatsResource seasonPlayerStats;
    private final NBATeamDepthChartsResource teamDepthCharts;
    private final NBATeamGameContextsResource teamGameContexts;

    public NbaApi(Http http) {
        this.seasons = new NBASeasonsResource(http);
        this.stadiums = new NBAStadiumsResource(http);
        this.referees = new NBARefereesResource(http);
        this.coachingStaffs = new NBACoachingStaffsResource(http);
        this.teams = new NBATeamsResource(http);
        this.games = new NBAGamesResource(http);
        this.players = new NBAPlayersResource(http);
        this.broadcasters = new NBABroadcastersResource(http);
        this.operatorTeamLookups = new NBAOperatorTeamLookupsResource(http);
        this.playoffs = new NBAPlayoffsResource(http);
        this.seasonTeamStats = new NBASeasonTeamStatsResource(http);
        this.teamCoachingStaffs = new NBATeamCoachingStaffsResource(http);
        this.teamStandings = new NBATeamStandingsResource(http);
        this.gameBroadcasters = new NBAGameBroadcastersResource(http);
        this.gameLines = new NBAGameLinesResource(http);
        this.gamePeriodLines = new NBAGamePeriodLinesResource(http);
        this.gamePlayerProps = new NBAGamePlayerPropsResource(http);
        this.gamePlayerStats = new NBAGamePlayerStatsResource(http);
        this.gamePossessions = new NBAGamePossessionsResource(http);
        this.gameReferees = new NBAGameRefereesResource(http);
        this.gameTeamLineupStints = new NBAGameTeamLineupStintsResource(http);
        this.gameTeamRosters = new NBAGameTeamRostersResource(http);
        this.gameTeamStats = new NBAGameTeamStatsResource(http);
        this.operatorPlayerLookups = new NBAOperatorPlayerLookupsResource(http);
        this.playByPlays = new NBAPlayByPlaysResource(http);
        this.playerNews = new NBAPlayerNewsResource(http);
        this.seasonPlayerStats = new NBASeasonPlayerStatsResource(http);
        this.teamDepthCharts = new NBATeamDepthChartsResource(http);
        this.teamGameContexts = new NBATeamGameContextsResource(http);
    }

    public NBASeasonsResource seasons() {
        return seasons;
    }

    public NBAStadiumsResource stadiums() {
        return stadiums;
    }

    public NBARefereesResource referees() {
        return referees;
    }

    public NBACoachingStaffsResource coachingStaffs() {
        return coachingStaffs;
    }

    public NBATeamsResource teams() {
        return teams;
    }

    public NBAGamesResource games() {
        return games;
    }

    public NBAPlayersResource players() {
        return players;
    }

    public NBABroadcastersResource broadcasters() {
        return broadcasters;
    }

    public NBAOperatorTeamLookupsResource operatorTeamLookups() {
        return operatorTeamLookups;
    }

    public NBAPlayoffsResource playoffs() {
        return playoffs;
    }

    public NBASeasonTeamStatsResource seasonTeamStats() {
        return seasonTeamStats;
    }

    public NBATeamCoachingStaffsResource teamCoachingStaffs() {
        return teamCoachingStaffs;
    }

    public NBATeamStandingsResource teamStandings() {
        return teamStandings;
    }

    public NBAGameBroadcastersResource gameBroadcasters() {
        return gameBroadcasters;
    }

    public NBAGameLinesResource gameLines() {
        return gameLines;
    }

    public NBAGamePeriodLinesResource gamePeriodLines() {
        return gamePeriodLines;
    }

    public NBAGamePlayerPropsResource gamePlayerProps() {
        return gamePlayerProps;
    }

    public NBAGamePlayerStatsResource gamePlayerStats() {
        return gamePlayerStats;
    }

    public NBAGamePossessionsResource gamePossessions() {
        return gamePossessions;
    }

    public NBAGameRefereesResource gameReferees() {
        return gameReferees;
    }

    public NBAGameTeamLineupStintsResource gameTeamLineupStints() {
        return gameTeamLineupStints;
    }

    public NBAGameTeamRostersResource gameTeamRosters() {
        return gameTeamRosters;
    }

    public NBAGameTeamStatsResource gameTeamStats() {
        return gameTeamStats;
    }

    public NBAOperatorPlayerLookupsResource operatorPlayerLookups() {
        return operatorPlayerLookups;
    }

    public NBAPlayByPlaysResource playByPlays() {
        return playByPlays;
    }

    public NBAPlayerNewsResource playerNews() {
        return playerNews;
    }

    public NBASeasonPlayerStatsResource seasonPlayerStats() {
        return seasonPlayerStats;
    }

    public NBATeamDepthChartsResource teamDepthCharts() {
        return teamDepthCharts;
    }

    public NBATeamGameContextsResource teamGameContexts() {
        return teamGameContexts;
    }
}
