// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nba.coaching_staffs (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import com.statapi.JsonValue;

public record NBACoachingStaff(
    Long id,
    Integer coachId,
    String firstName,
    String lastName,
    String name
) {

    public static NBACoachingStaff fromJson(JsonValue json) {
        return new NBACoachingStaff(
            json.get("id").asLong(),
            json.get("coach_id").asInt(),
            json.get("first_name").asString(),
            json.get("last_name").asString(),
            json.get("name").asString()
        );
    }
}
