// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nba.game_lines (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NBAGameLinesListParams {

    private Long gameId;
    private Long seasonId;
    private Long operatorId;
    private Boolean isOpening;
    private Long limit;
    private Long fromId;

    public NBAGameLinesListParams gameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    public NBAGameLinesListParams seasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    public NBAGameLinesListParams operatorId(Long operatorId) {
        this.operatorId = operatorId;
        return this;
    }

    public NBAGameLinesListParams isOpening(Boolean isOpening) {
        this.isOpening = isOpening;
        return this;
    }

    public NBAGameLinesListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NBAGameLinesListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (gameId != null) {
            query.put("game_id", String.valueOf(gameId));
        }
        if (seasonId != null) {
            query.put("season_id", String.valueOf(seasonId));
        }
        if (operatorId != null) {
            query.put("operator_id", String.valueOf(operatorId));
        }
        if (isOpening != null) {
            query.put("is_opening", String.valueOf(isOpening));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
