// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nba.game_team_stats (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NBAGameTeamStatsListParams {

    private Long gameId;
    private Long teamId;
    private Long limit;
    private Long fromId;

    public NBAGameTeamStatsListParams gameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    public NBAGameTeamStatsListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NBAGameTeamStatsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NBAGameTeamStatsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (gameId != null) {
            query.put("game_id", String.valueOf(gameId));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
