// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nba.games (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NBAGamesListParams {

    private Long seasonId;
    private Long homeTeamId;
    private Long awayTeamId;
    private String status;
    private Integer day;
    private String seasonType;
    private Long limit;
    private Long fromId;

    public NBAGamesListParams seasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    public NBAGamesListParams homeTeamId(Long homeTeamId) {
        this.homeTeamId = homeTeamId;
        return this;
    }

    public NBAGamesListParams awayTeamId(Long awayTeamId) {
        this.awayTeamId = awayTeamId;
        return this;
    }

    public NBAGamesListParams status(String status) {
        this.status = status;
        return this;
    }

    public NBAGamesListParams day(Integer day) {
        this.day = day;
        return this;
    }

    public NBAGamesListParams seasonType(String seasonType) {
        this.seasonType = seasonType;
        return this;
    }

    public NBAGamesListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NBAGamesListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (seasonId != null) {
            query.put("season_id", String.valueOf(seasonId));
        }
        if (homeTeamId != null) {
            query.put("home_team_id", String.valueOf(homeTeamId));
        }
        if (awayTeamId != null) {
            query.put("away_team_id", String.valueOf(awayTeamId));
        }
        if (status != null) {
            query.put("status", String.valueOf(status));
        }
        if (day != null) {
            query.put("day", String.valueOf(day));
        }
        if (seasonType != null) {
            query.put("season_type", String.valueOf(seasonType));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
