// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nba.game_team_rosters (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NBAGameTeamRostersListParams {

    private Long gameId;
    private Long teamId;
    private Long playerId;
    private Long limit;
    private Long fromId;

    public NBAGameTeamRostersListParams gameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    public NBAGameTeamRostersListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NBAGameTeamRostersListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public NBAGameTeamRostersListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NBAGameTeamRostersListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (gameId != null) {
            query.put("game_id", String.valueOf(gameId));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
