// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nba.players (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NBAPlayersListParams {

    private Long teamId;
    private String rosterStatus;
    private Long limit;
    private Long fromId;

    public NBAPlayersListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NBAPlayersListParams rosterStatus(String rosterStatus) {
        this.rosterStatus = rosterStatus;
        return this;
    }

    public NBAPlayersListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NBAPlayersListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (rosterStatus != null) {
            query.put("roster_status", String.valueOf(rosterStatus));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
