// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nba.player_news (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NBAPlayerNewsListParams {

    private Long playerId;
    private Long teamId;
    private String category;
    private String newsTime;
    private Long limit;
    private Long fromId;

    public NBAPlayerNewsListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public NBAPlayerNewsListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NBAPlayerNewsListParams category(String category) {
        this.category = category;
        return this;
    }

    public NBAPlayerNewsListParams newsTime(String newsTime) {
        this.newsTime = newsTime;
        return this;
    }

    public NBAPlayerNewsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NBAPlayerNewsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (category != null) {
            query.put("category", String.valueOf(category));
        }
        if (newsTime != null) {
            query.put("news_time", String.valueOf(newsTime));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
