// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nba.referees (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import com.statapi.JsonValue;

public record NBAReferee(
    Long id,
    Integer nbaRefereeId,
    Boolean active,
    String birthCity,
    String birthCountry,
    String birthDate,
    String birthState,
    String college,
    Integer experience,
    String firstName,
    String fullName,
    String jerseyNumber,
    String lastName
) {

    public static NBAReferee fromJson(JsonValue json) {
        return new NBAReferee(
            json.get("id").asLong(),
            json.get("nba_referee_id").asInt(),
            json.get("active").asBoolean(),
            json.get("birth_city").asString(),
            json.get("birth_country").asString(),
            json.get("birth_date").asString(),
            json.get("birth_state").asString(),
            json.get("college").asString(),
            json.get("experience").asInt(),
            json.get("first_name").asString(),
            json.get("full_name").asString(),
            json.get("jersey_number").asString(),
            json.get("last_name").asString()
        );
    }
}
