// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nba.season_team_stats (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import com.statapi.JsonValue;

public record NBASeasonTeamStat(
    Long id,
    Long seasonId,
    Long teamId,
    Integer gamesPlayed,
    Integer losses,
    Integer ptsAllowed,
    Integer ptsScored,
    Integer ties,
    Integer wins
) {

    public static NBASeasonTeamStat fromJson(JsonValue json) {
        return new NBASeasonTeamStat(
            json.get("id").asLong(),
            json.get("season_id").asLong(),
            json.get("team_id").asLong(),
            json.get("games_played").asInt(),
            json.get("losses").asInt(),
            json.get("pts_allowed").asInt(),
            json.get("pts_scored").asInt(),
            json.get("ties").asInt(),
            json.get("wins").asInt()
        );
    }
}
