// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nba.team_coaching_staffs (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import com.statapi.JsonValue;

public record NBATeamCoachingStaff(
    Long id,
    Long coachingStaffId,
    Long seasonId,
    Long teamId,
    String coachType,
    String endDate,
    Boolean isAssistant,
    Integer sortSequence,
    String startDate
) {

    public static NBATeamCoachingStaff fromJson(JsonValue json) {
        return new NBATeamCoachingStaff(
            json.get("id").asLong(),
            json.get("coaching_staff_id").asLong(),
            json.get("season_id").asLong(),
            json.get("team_id").asLong(),
            json.get("coach_type").asString(),
            json.get("end_date").asString(),
            json.get("is_assistant").asBoolean(),
            json.get("sort_sequence").asInt(),
            json.get("start_date").asString()
        );
    }
}
