// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nba.team_standings (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NBATeamStandingsListParams {

    private Long seasonId;
    private Long teamId;
    private Integer day;
    private Long limit;
    private Long fromId;

    public NBATeamStandingsListParams seasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    public NBATeamStandingsListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NBATeamStandingsListParams day(Integer day) {
        this.day = day;
        return this;
    }

    public NBATeamStandingsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NBATeamStandingsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (seasonId != null) {
            query.put("season_id", String.valueOf(seasonId));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (day != null) {
            query.put("day", String.valueOf(day));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
