// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nba.team_game_contexts (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import com.statapi.JsonValue;

public record NBATeamGameContext(
    Long id,
    Long gameId,
    Long opponentTeamId,
    Long seasonId,
    Long teamId,
    Integer conferenceRank,
    String gameType,
    Integer gamesRemaining,
    Integer intensity,
    Boolean isBackToBack,
    Boolean isClinch,
    Boolean isElimination,
    Integer istGroupRank,
    String istGroupRecord,
    String motivation,
    Integer restDays,
    Double seasonPct,
    String seasonPhase,
    Integer teamSeriesWins,
    Double winPct
) {

    public static NBATeamGameContext fromJson(JsonValue json) {
        return new NBATeamGameContext(
            json.get("id").asLong(),
            json.get("game_id").asLong(),
            json.get("opponent_team_id").asLong(),
            json.get("season_id").asLong(),
            json.get("team_id").asLong(),
            json.get("conference_rank").asInt(),
            json.get("game_type").asString(),
            json.get("games_remaining").asInt(),
            json.get("intensity").asInt(),
            json.get("is_back_to_back").asBoolean(),
            json.get("is_clinch").asBoolean(),
            json.get("is_elimination").asBoolean(),
            json.get("ist_group_rank").asInt(),
            json.get("ist_group_record").asString(),
            json.get("motivation").asString(),
            json.get("rest_days").asInt(),
            json.get("season_pct").asDouble(),
            json.get("season_phase").asString(),
            json.get("team_series_wins").asInt(),
            json.get("win_pct").asDouble()
        );
    }
}
