// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nba.team_coaching_staffs (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml
package com.statapi.nba;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NBATeamCoachingStaffsListParams {

    private Long teamId;
    private Long seasonId;
    private String coachType;
    private Long limit;
    private Long fromId;

    public NBATeamCoachingStaffsListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NBATeamCoachingStaffsListParams seasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    public NBATeamCoachingStaffsListParams coachType(String coachType) {
        this.coachType = coachType;
        return this;
    }

    public NBATeamCoachingStaffsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NBATeamCoachingStaffsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (seasonId != null) {
            query.put("season_id", String.valueOf(seasonId));
        }
        if (coachType != null) {
            query.put("coach_type", String.valueOf(coachType));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
