// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nfl.combine_results (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import com.statapi.JsonValue;

public record NFLCombineResult(
    Long id,
    String cfbId,
    String pfrId,
    Long playerId,
    Long teamId,
    Integer bench,
    Integer broadJump,
    Double cone,
    Double forty,
    String ht,
    String position,
    String school,
    Integer season,
    Double shuttle,
    Double vertical,
    Integer wt
) {

    public static NFLCombineResult fromJson(JsonValue json) {
        return new NFLCombineResult(
            json.get("id").asLong(),
            json.get("cfb_id").asString(),
            json.get("pfr_id").asString(),
            json.get("player_id").asLong(),
            json.get("team_id").asLong(),
            json.get("bench").asInt(),
            json.get("broad_jump").asInt(),
            json.get("cone").asDouble(),
            json.get("forty").asDouble(),
            json.get("ht").asString(),
            json.get("position").asString(),
            json.get("school").asString(),
            json.get("season").asInt(),
            json.get("shuttle").asDouble(),
            json.get("vertical").asDouble(),
            json.get("wt").asInt()
        );
    }
}
