// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.coaching_staffs (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLCoachingStaffsListParams {

    private Long teamId;
    private Long seasonId;
    private String position;
    private Long limit;
    private Long fromId;

    public NFLCoachingStaffsListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NFLCoachingStaffsListParams seasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    public NFLCoachingStaffsListParams position(String position) {
        this.position = position;
        return this;
    }

    public NFLCoachingStaffsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLCoachingStaffsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (seasonId != null) {
            query.put("season_id", String.valueOf(seasonId));
        }
        if (position != null) {
            query.put("position", String.valueOf(position));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
