// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.combine_results (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLCombineResultsListParams {

    private Long playerId;
    private Integer season;
    private String position;
    private Long limit;
    private Long fromId;

    public NFLCombineResultsListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public NFLCombineResultsListParams season(Integer season) {
        this.season = season;
        return this;
    }

    public NFLCombineResultsListParams position(String position) {
        this.position = position;
        return this;
    }

    public NFLCombineResultsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLCombineResultsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (season != null) {
            query.put("season", String.valueOf(season));
        }
        if (position != null) {
            query.put("position", String.valueOf(position));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
