// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nfl.coaching_staff_tenures (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import com.statapi.JsonValue;

public record NFLCoachingStaffTenure(
    Long id,
    Long seasonId,
    Long teamId,
    String effectiveDate,
    String endDate,
    String firstName,
    String fullName,
    Boolean isInterim,
    String lastName,
    String position,
    String reason
) {

    public static NFLCoachingStaffTenure fromJson(JsonValue json) {
        return new NFLCoachingStaffTenure(
            json.get("id").asLong(),
            json.get("season_id").asLong(),
            json.get("team_id").asLong(),
            json.get("effective_date").asString(),
            json.get("end_date").asString(),
            json.get("first_name").asString(),
            json.get("full_name").asString(),
            json.get("is_interim").asBoolean(),
            json.get("last_name").asString(),
            json.get("position").asString(),
            json.get("reason").asString()
        );
    }
}
