// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.draft_picks (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLDraftPicksListParams {

    private Integer season;
    private Integer round;
    private Long teamId;
    private Long playerId;
    private String position;
    private Long limit;
    private Long fromId;

    public NFLDraftPicksListParams season(Integer season) {
        this.season = season;
        return this;
    }

    public NFLDraftPicksListParams round(Integer round) {
        this.round = round;
        return this;
    }

    public NFLDraftPicksListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NFLDraftPicksListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public NFLDraftPicksListParams position(String position) {
        this.position = position;
        return this;
    }

    public NFLDraftPicksListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLDraftPicksListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (season != null) {
            query.put("season", String.valueOf(season));
        }
        if (round != null) {
            query.put("round", String.valueOf(round));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (position != null) {
            query.put("position", String.valueOf(position));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
