// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.game_team_rosters (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLGameTeamRostersListParams {

    private Long gameId;
    private Long teamId;
    private Long playerId;
    private String position;
    private String status;
    private Long limit;
    private Long fromId;

    public NFLGameTeamRostersListParams gameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    public NFLGameTeamRostersListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NFLGameTeamRostersListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public NFLGameTeamRostersListParams position(String position) {
        this.position = position;
        return this;
    }

    public NFLGameTeamRostersListParams status(String status) {
        this.status = status;
        return this;
    }

    public NFLGameTeamRostersListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLGameTeamRostersListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (gameId != null) {
            query.put("game_id", String.valueOf(gameId));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (position != null) {
            query.put("position", String.valueOf(position));
        }
        if (status != null) {
            query.put("status", String.valueOf(status));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
