// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.game_player_redzone_stats (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLGamePlayerRedzoneStatsListParams {

    private Long gameId;
    private Long playerId;
    private Long teamId;
    private Long opponentTeamId;
    private String position;
    private Long limit;
    private Long fromId;

    public NFLGamePlayerRedzoneStatsListParams gameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    public NFLGamePlayerRedzoneStatsListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public NFLGamePlayerRedzoneStatsListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NFLGamePlayerRedzoneStatsListParams opponentTeamId(Long opponentTeamId) {
        this.opponentTeamId = opponentTeamId;
        return this;
    }

    public NFLGamePlayerRedzoneStatsListParams position(String position) {
        this.position = position;
        return this;
    }

    public NFLGamePlayerRedzoneStatsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLGamePlayerRedzoneStatsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (gameId != null) {
            query.put("game_id", String.valueOf(gameId));
        }
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (opponentTeamId != null) {
            query.put("opponent_team_id", String.valueOf(opponentTeamId));
        }
        if (position != null) {
            query.put("position", String.valueOf(position));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
