// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nfl.game_drives (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import com.statapi.JsonValue;

public record NFLGameDrive(
    Long id,
    Long firstPlayId,
    Long gameId,
    Long lastPlayId,
    Long possessionTeamId,
    Integer driveNumber,
    String endTransition,
    String endYardLine,
    Boolean endedWithScore,
    Integer firstDowns,
    Integer fixedDrive,
    String gameClockEnd,
    String gameClockStart,
    Boolean inside20,
    Integer playCount,
    Integer quarterEnd,
    Integer quarterStart,
    String result,
    String startTransition,
    String startYardLine,
    String timeOfPossession,
    Integer ydsPenalized
) {

    public static NFLGameDrive fromJson(JsonValue json) {
        return new NFLGameDrive(
            json.get("id").asLong(),
            json.get("first_play_id").asLong(),
            json.get("game_id").asLong(),
            json.get("last_play_id").asLong(),
            json.get("possession_team_id").asLong(),
            json.get("drive_number").asInt(),
            json.get("end_transition").asString(),
            json.get("end_yard_line").asString(),
            json.get("ended_with_score").asBoolean(),
            json.get("first_downs").asInt(),
            json.get("fixed_drive").asInt(),
            json.get("game_clock_end").asString(),
            json.get("game_clock_start").asString(),
            json.get("inside_20").asBoolean(),
            json.get("play_count").asInt(),
            json.get("quarter_end").asInt(),
            json.get("quarter_start").asInt(),
            json.get("result").asString(),
            json.get("start_transition").asString(),
            json.get("start_yard_line").asString(),
            json.get("time_of_possession").asString(),
            json.get("yds_penalized").asInt()
        );
    }
}
