// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nfl.game_player_ngs_receivings (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import com.statapi.JsonValue;

public record NFLGamePlayerNgsReceiving(
    Long id,
    Long gameId,
    String playerGsisId,
    Long playerId,
    Long teamId,
    Double avgCushion,
    Double avgExpectedYac,
    Double avgIntendedAirYds,
    Double avgSeparation,
    Double avgYac,
    Double avgYacAboveExpectation,
    Double catchPercentage,
    Double percentShareOfIntendedAirYds,
    Integer recTds,
    Integer receptions,
    Integer season,
    String seasonType,
    Integer targets,
    Integer week,
    Integer yards
) {

    public static NFLGamePlayerNgsReceiving fromJson(JsonValue json) {
        return new NFLGamePlayerNgsReceiving(
            json.get("id").asLong(),
            json.get("game_id").asLong(),
            json.get("player_gsis_id").asString(),
            json.get("player_id").asLong(),
            json.get("team_id").asLong(),
            json.get("avg_cushion").asDouble(),
            json.get("avg_expected_yac").asDouble(),
            json.get("avg_intended_air_yds").asDouble(),
            json.get("avg_separation").asDouble(),
            json.get("avg_yac").asDouble(),
            json.get("avg_yac_above_expectation").asDouble(),
            json.get("catch_percentage").asDouble(),
            json.get("percent_share_of_intended_air_yds").asDouble(),
            json.get("rec_tds").asInt(),
            json.get("receptions").asInt(),
            json.get("season").asInt(),
            json.get("season_type").asString(),
            json.get("targets").asInt(),
            json.get("week").asInt(),
            json.get("yards").asInt()
        );
    }
}
