// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.game_player_ngs_passings (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLGamePlayerNgsPassingsListParams {

    private Long gameId;
    private Long playerId;
    private Long teamId;
    private Integer season;
    private Integer week;
    private Long limit;
    private Long fromId;

    public NFLGamePlayerNgsPassingsListParams gameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    public NFLGamePlayerNgsPassingsListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public NFLGamePlayerNgsPassingsListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NFLGamePlayerNgsPassingsListParams season(Integer season) {
        this.season = season;
        return this;
    }

    public NFLGamePlayerNgsPassingsListParams week(Integer week) {
        this.week = week;
        return this;
    }

    public NFLGamePlayerNgsPassingsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLGamePlayerNgsPassingsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (gameId != null) {
            query.put("game_id", String.valueOf(gameId));
        }
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (season != null) {
            query.put("season", String.valueOf(season));
        }
        if (week != null) {
            query.put("week", String.valueOf(week));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
