// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK resource for nfl.game_referees (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import com.statapi.Http;
import com.statapi.JsonValue;
import com.statapi.Page;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;

public final class NFLGameRefereesResource {

    private static final String PATH = "/api/v1/nfl/game_referees";

    private final Http http;

    public NFLGameRefereesResource(Http http) {
        this.http = http;
    }

    public Page<NFLGameReferee> list() {
        return list(new NFLGameRefereesListParams());
    }

    public Page<NFLGameReferee> list(NFLGameRefereesListParams params) {
        Map<String, String> query = params == null ? Collections.emptyMap() : params.toQuery();
        return fetch(query);
    }

    public NFLGameReferee get(long id) {
        Http.Response response = http.get(PATH + "/" + id, Collections.emptyMap());
        return NFLGameReferee.fromJson(response.body());
    }

    public Iterable<NFLGameReferee> iterate() {
        return iterate(new NFLGameRefereesListParams());
    }

    public Iterable<NFLGameReferee> iterate(NFLGameRefereesListParams params) {
        Map<String, String> base = params == null ? Collections.emptyMap() : params.toQuery();
        return () -> new PageWalker(base);
    }

    private Page<NFLGameReferee> fetch(Map<String, String> query) {
        Http.Response response = http.get(PATH, query);
        JsonValue body = response.body();
        List<NFLGameReferee> rows = new ArrayList<>();
        for (JsonValue row : body.get("game_referees").asArray()) {
            rows.add(NFLGameReferee.fromJson(row));
        }
        return new Page<>(rows, body.get("limit").asLong(), body.get("next_from_id").asLong(), response.quota());
    }

    // Lazy auto-pager: fetches one page at a time, following next_from_id. On a
    // required-filter-set table an unfiltered walk 400s on the first fetch
    // (→ ValidationException), same as list().
    private final class PageWalker implements Iterator<NFLGameReferee> {

        private final Map<String, String> base;
        private Iterator<NFLGameReferee> current = Collections.emptyIterator();
        private Long nextFromId;
        private boolean done;
        private boolean started;

        PageWalker(Map<String, String> base) {
            this.base = base;
        }

        @Override
        public boolean hasNext() {
            while (!current.hasNext() && !done) {
                fetchNext();
            }
            return current.hasNext();
        }

        @Override
        public NFLGameReferee next() {
            if (!hasNext()) {
                throw new NoSuchElementException();
            }
            return current.next();
        }

        private void fetchNext() {
            Map<String, String> query = new LinkedHashMap<>(base);
            // Always walk with from_id: it forces the server's ascending
            // keyset order. Without it, DESC-default tables re-yield page 1
            // and under-walk. First page honors a caller-supplied from_id
            // (already present in the base map), else starts at 0.
            if (started) {
                query.put("from_id", String.valueOf(nextFromId));
            } else if (!query.containsKey("from_id")) {
                query.put("from_id", "0");
            }
            started = true;
            Page<NFLGameReferee> page = fetch(query);
            current = page.rows().iterator();
            nextFromId = page.nextFromId();
            if (nextFromId == null) {
                done = true;
            }
        }
    }
}
