// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.game_referees (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLGameRefereesListParams {

    private Long gameId;
    private Long refereeId;
    private String position;
    private Long limit;
    private Long fromId;

    public NFLGameRefereesListParams gameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    public NFLGameRefereesListParams refereeId(Long refereeId) {
        this.refereeId = refereeId;
        return this;
    }

    public NFLGameRefereesListParams position(String position) {
        this.position = position;
        return this;
    }

    public NFLGameRefereesListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLGameRefereesListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (gameId != null) {
            query.put("game_id", String.valueOf(gameId));
        }
        if (refereeId != null) {
            query.put("referee_id", String.valueOf(refereeId));
        }
        if (position != null) {
            query.put("position", String.valueOf(position));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
