// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nfl.injuries (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import com.statapi.JsonValue;

public record NFLInjury(
    Long id,
    Long gameId,
    Long playerId,
    Long seasonId,
    Long teamId,
    String dateModified,
    String gameType,
    String position,
    String practicePrimaryInjury,
    String practiceSecondaryInjury,
    String practiceStatus,
    String reportPrimaryInjury,
    String reportSecondaryInjury,
    String reportStatus,
    Integer week
) {

    public static NFLInjury fromJson(JsonValue json) {
        return new NFLInjury(
            json.get("id").asLong(),
            json.get("game_id").asLong(),
            json.get("player_id").asLong(),
            json.get("season_id").asLong(),
            json.get("team_id").asLong(),
            json.get("date_modified").asString(),
            json.get("game_type").asString(),
            json.get("position").asString(),
            json.get("practice_primary_injury").asString(),
            json.get("practice_secondary_injury").asString(),
            json.get("practice_status").asString(),
            json.get("report_primary_injury").asString(),
            json.get("report_secondary_injury").asString(),
            json.get("report_status").asString(),
            json.get("week").asInt()
        );
    }
}
