// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nfl.operator_team_lookups (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import com.statapi.JsonValue;

public record NFLOperatorTeamLookup(
    Long id,
    Long operatorId,
    String operatorTeamId,
    Long teamId,
    String abbreviation,
    String teamName
) {

    public static NFLOperatorTeamLookup fromJson(JsonValue json) {
        return new NFLOperatorTeamLookup(
            json.get("id").asLong(),
            json.get("operator_id").asLong(),
            json.get("operator_team_id").asString(),
            json.get("team_id").asLong(),
            json.get("abbreviation").asString(),
            json.get("team_name").asString()
        );
    }
}
