// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nfl.operator_player_lookups (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import com.statapi.JsonValue;

public record NFLOperatorPlayerLookup(
    Long id,
    Long operatorId,
    String operatorPlayerId,
    Long playerId,
    String playerName,
    String position
) {

    public static NFLOperatorPlayerLookup fromJson(JsonValue json) {
        return new NFLOperatorPlayerLookup(
            json.get("id").asLong(),
            json.get("operator_id").asLong(),
            json.get("operator_player_id").asString(),
            json.get("player_id").asLong(),
            json.get("player_name").asString(),
            json.get("position").asString()
        );
    }
}
