// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.operator_team_lookups (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLOperatorTeamLookupsListParams {

    private Long operatorId;
    private Long teamId;
    private Long limit;
    private Long fromId;

    public NFLOperatorTeamLookupsListParams operatorId(Long operatorId) {
        this.operatorId = operatorId;
        return this;
    }

    public NFLOperatorTeamLookupsListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NFLOperatorTeamLookupsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLOperatorTeamLookupsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (operatorId != null) {
            query.put("operator_id", String.valueOf(operatorId));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
