// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.play_by_plays (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLPlayByPlaysListParams {

    private Long gameId;
    private Long possessionTeamId;
    private Long defensiveTeamId;
    private Long driveId;
    private Long limit;
    private Long fromId;

    public NFLPlayByPlaysListParams gameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    public NFLPlayByPlaysListParams possessionTeamId(Long possessionTeamId) {
        this.possessionTeamId = possessionTeamId;
        return this;
    }

    public NFLPlayByPlaysListParams defensiveTeamId(Long defensiveTeamId) {
        this.defensiveTeamId = defensiveTeamId;
        return this;
    }

    public NFLPlayByPlaysListParams driveId(Long driveId) {
        this.driveId = driveId;
        return this;
    }

    public NFLPlayByPlaysListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLPlayByPlaysListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (gameId != null) {
            query.put("game_id", String.valueOf(gameId));
        }
        if (possessionTeamId != null) {
            query.put("possession_team_id", String.valueOf(possessionTeamId));
        }
        if (defensiveTeamId != null) {
            query.put("defensive_team_id", String.valueOf(defensiveTeamId));
        }
        if (driveId != null) {
            query.put("drive_id", String.valueOf(driveId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
