// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nfl.player_contracts (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import com.statapi.JsonValue;

public record NFLPlayerContract(
    Long id,
    String otcId,
    Long playerId,
    Long teamId,
    Long apy,
    Double apyCapPct,
    String college,
    String dateOfBirth,
    Long guaranteed,
    String height,
    Long inflatedApy,
    Long inflatedGuaranteed,
    Long inflatedValue,
    Boolean isActive,
    String playerPageUrl,
    String position,
    String seasonHistoryJson,
    Long value,
    Integer weight,
    Integer yearSigned,
    Integer years
) {

    public static NFLPlayerContract fromJson(JsonValue json) {
        return new NFLPlayerContract(
            json.get("id").asLong(),
            json.get("otc_id").asString(),
            json.get("player_id").asLong(),
            json.get("team_id").asLong(),
            json.get("apy").asLong(),
            json.get("apy_cap_pct").asDouble(),
            json.get("college").asString(),
            json.get("date_of_birth").asString(),
            json.get("guaranteed").asLong(),
            json.get("height").asString(),
            json.get("inflated_apy").asLong(),
            json.get("inflated_guaranteed").asLong(),
            json.get("inflated_value").asLong(),
            json.get("is_active").asBoolean(),
            json.get("player_page_url").asString(),
            json.get("position").asString(),
            json.get("season_history_json").asString(),
            json.get("value").asLong(),
            json.get("weight").asInt(),
            json.get("year_signed").asInt(),
            json.get("years").asInt()
        );
    }
}
