// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.player_contracts (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLPlayerContractsListParams {

    private Long playerId;
    private Long teamId;
    private String position;
    private Long limit;
    private Long fromId;

    public NFLPlayerContractsListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public NFLPlayerContractsListParams teamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    public NFLPlayerContractsListParams position(String position) {
        this.position = position;
        return this;
    }

    public NFLPlayerContractsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLPlayerContractsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (teamId != null) {
            query.put("team_id", String.valueOf(teamId));
        }
        if (position != null) {
            query.put("position", String.valueOf(position));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
