// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nfl.season_player_stats (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml
package com.statapi.nfl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NFLSeasonPlayerStatsListParams {

    private Long playerId;
    private Long seasonId;
    private Long limit;
    private Long fromId;

    public NFLSeasonPlayerStatsListParams playerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    public NFLSeasonPlayerStatsListParams seasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    public NFLSeasonPlayerStatsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NFLSeasonPlayerStatsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (playerId != null) {
            query.put("player_id", String.valueOf(playerId));
        }
        if (seasonId != null) {
            query.put("season_id", String.valueOf(seasonId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
