# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for pga.player_holes (public API).
# Source: schema/api/groups/public.yml + schema/model/golf/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

PGAPlayerHole = TypedDict(
    "PGAPlayerHole",
    {
        "id": int,
        "player_id": int,
        "player_round_id": int,
        "tournament_id": int,
        "birdie": bool | None,
        "bogey": bool | None,
        "double_bogey": bool | None,
        "double_eagle": bool | None,
        "eagle": bool | None,
        "hole_in_one": bool | None,
        "hole_number": int,
        "is_par": bool | None,
        "par": int | None,
        "round_number": int,
        "score": int | None,
        "to_par": int | None,
        "worse_than_double_bogey": bool | None,
    },
)


class PGAPlayerHolesResource:
    _PATH = "/api/v1/pga/player_holes"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, player_id: int | None = None, tournament_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[PGAPlayerHole]:
        body, quota = self._transport.request(self._PATH, {
            "player_id": player_id,
            "tournament_id": tournament_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[PGAPlayerHole] = body["player_holes"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> PGAPlayerHole:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: PGAPlayerHole = body
        return row

    def iter(self, *, player_id: int | None = None, tournament_id: int | None = None, limit: int | None = None) -> Iterator[PGAPlayerHole]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(player_id=player_id, tournament_id=tournament_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
