# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for pga.player_rounds (public API).
# Source: schema/api/groups/public.yml + schema/model/golf/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

PGAPlayerRound = TypedDict(
    "PGAPlayerRound",
    {
        "id": int,
        "player_id": int,
        "player_round_id": int,
        "tournament_id": int,
        "back_nine_start": bool | None,
        "birdies": int | None,
        "bogeys": int | None,
        "day": str | None,
        "double_bogeys": int | None,
        "double_eagles": int | None,
        "eagles": int | None,
        "holes_in_one": int | None,
        "par": int | None,
        "pars": int | None,
        "round_number": int,
        "score": int | None,
        "sg_approach": float | None,
        "sg_around_green": float | None,
        "sg_off_tee": float | None,
        "sg_putting": float | None,
        "sg_tee_to_green": float | None,
        "sg_total": float | None,
        "tee_time": str | None,
        "triple_bogeys": int | None,
        "worse_than_double_bogey": int | None,
        "worse_than_triple_bogey": int | None,
    },
)


class PGAPlayerRoundsResource:
    _PATH = "/api/v1/pga/player_rounds"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, player_id: int | None = None, tournament_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[PGAPlayerRound]:
        body, quota = self._transport.request(self._PATH, {
            "player_id": player_id,
            "tournament_id": tournament_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[PGAPlayerRound] = body["player_rounds"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> PGAPlayerRound:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: PGAPlayerRound = body
        return row

    def iter(self, *, player_id: int | None = None, tournament_id: int | None = None, limit: int | None = None) -> Iterator[PGAPlayerRound]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(player_id=player_id, tournament_id=tournament_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
