# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for pga.tournament_rounds (public API).
# Source: schema/api/groups/public.yml + schema/model/golf/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

PGATournamentRound = TypedDict(
    "PGATournamentRound",
    {
        "id": int,
        "round_id": int,
        "tournament_id": int,
        "day": str,
        "round_number": int,
    },
)


class PGATournamentRoundsResource:
    _PATH = "/api/v1/pga/tournament_rounds"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, tournament_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[PGATournamentRound]:
        body, quota = self._transport.request(self._PATH, {
            "tournament_id": tournament_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[PGATournamentRound] = body["tournament_rounds"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> PGATournamentRound:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: PGATournamentRound = body
        return row

    def iter(self, *, tournament_id: int | None = None, limit: int | None = None) -> Iterator[PGATournamentRound]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(tournament_id=tournament_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
