# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for polymarket.markets (public API).
# Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

PolymarketMarket = TypedDict(
    "PolymarketMarket",
    {
        "id": int,
        "competition_id": int | None,
        "condition_id": str,
        "event_id": int,
        "payout_token_id": str | None,
        "active": bool,
        "best_ask_bps": int | None,
        "best_bid_bps": int | None,
        "closed": bool,
        "last_trade_price_bps": int | None,
        "liquidity": int | None,
        "neg_risk": bool,
        "outcome_count": int,
        "question": str | None,
        "resolution_source": str | None,
        "resolved_at": str | None,
        "result": str | None,
        "slug": str | None,
        "status": str,
        "volume": int | None,
    },
)


class PolymarketMarketsResource:
    _PATH = "/api/v1/polymarket/markets"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, event_id: int | None = None, competition_id: int | None = None, status: str | None = None, active: bool | None = None, limit: int | None = None, from_id: int | None = None) -> Page[PolymarketMarket]:
        body, quota = self._transport.request(self._PATH, {
            "event_id": event_id,
            "competition_id": competition_id,
            "status": status,
            "active": active,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[PolymarketMarket] = body["markets"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> PolymarketMarket:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: PolymarketMarket = body
        return row

    def iter(self, *, event_id: int | None = None, competition_id: int | None = None, status: str | None = None, active: bool | None = None, limit: int | None = None) -> Iterator[PolymarketMarket]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(event_id=event_id, competition_id=competition_id, status=status, active=active, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
