# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for polymarket.market_snapshots (public API).
# Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

PolymarketMarketSnapshot = TypedDict(
    "PolymarketMarketSnapshot",
    {
        "id": int,
        "condition_id": str,
        "market_id": int,
        "best_ask_bps": int | None,
        "best_bid_bps": int | None,
        "captured_at": str,
        "last_trade_price_bps": int | None,
        "liquidity": int | None,
        "volume": int | None,
    },
)


class PolymarketMarketSnapshotsResource:
    _PATH = "/api/v1/polymarket/market_snapshots"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, market_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[PolymarketMarketSnapshot]:
        body, quota = self._transport.request(self._PATH, {
            "market_id": market_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[PolymarketMarketSnapshot] = body["market_snapshots"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> PolymarketMarketSnapshot:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: PolymarketMarketSnapshot = body
        return row

    def iter(self, *, market_id: int | None = None, limit: int | None = None) -> Iterator[PolymarketMarketSnapshot]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(market_id=market_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
