# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for polymarket.sports (public API).
# Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

PolymarketSport = TypedDict(
    "PolymarketSport",
    {
        "id": int,
        "sport_id": int | None,
        "name": str,
        "tag_slug": str,
    },
)


class PolymarketSportsResource:
    _PATH = "/api/v1/polymarket/sports"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, limit: int | None = None, from_id: int | None = None) -> Page[PolymarketSport]:
        body, quota = self._transport.request(self._PATH, {
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[PolymarketSport] = body["sports"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> PolymarketSport:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: PolymarketSport = body
        return row

    def iter(self, *, limit: int | None = None) -> Iterator[PolymarketSport]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
