# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for polymarket.tokens (public API).
# Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

PolymarketToken = TypedDict(
    "PolymarketToken",
    {
        "id": int,
        "event_id": int | None,
        "market_id": int,
        "token_id": str,
        "final_price_bps": int | None,
        "outcome": str,
        "outcome_index": int,
        "price_bps": int | None,
        "winner": bool | None,
    },
)


class PolymarketTokensResource:
    _PATH = "/api/v1/polymarket/tokens"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, market_id: int | None = None, event_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[PolymarketToken]:
        body, quota = self._transport.request(self._PATH, {
            "market_id": market_id,
            "event_id": event_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[PolymarketToken] = body["tokens"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> PolymarketToken:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: PolymarketToken = body
        return row

    def iter(self, *, market_id: int | None = None, event_id: int | None = None, limit: int | None = None) -> Iterator[PolymarketToken]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(market_id=market_id, event_id=event_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
