// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nhl.arenas (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml
package com.statapi.nhl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NHLArenasListParams {

    private Long limit;
    private Long fromId;

    public NHLArenasListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NHLArenasListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
