// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nhl.games (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml
package com.statapi.nhl;

import com.statapi.JsonValue;

public record NHLGame(
    Long id,
    Long arenaId,
    Long awayTeamId,
    Long homeTeamId,
    Integer leagueGameId,
    String leagueId,
    Long seasonId,
    Integer attendance,
    Integer awayTeamScore,
    Integer awayTeamScoreOvertime,
    Integer awayTeamScorePeriod1,
    Integer awayTeamScorePeriod2,
    Integer awayTeamScorePeriod3,
    Integer awayTeamSeriesWins,
    String channel,
    String dateTime,
    String dateTimeUtc,
    Integer day,
    String gameTime,
    Integer homeTeamScore,
    Integer homeTeamScoreOvertime,
    Integer homeTeamScorePeriod1,
    Integer homeTeamScorePeriod2,
    Integer homeTeamScorePeriod3,
    Integer homeTeamSeriesWins,
    Boolean isOvertime,
    Boolean isShootout,
    String lastPlay,
    Boolean neutralSite,
    Integer overtimePeriods,
    String period,
    String playoffRound,
    String seasonType,
    Integer seriesGameNumber,
    String status,
    Integer timeRemainingMinutes,
    Integer timeRemainingSeconds
) {

    public static NHLGame fromJson(JsonValue json) {
        return new NHLGame(
            json.get("id").asLong(),
            json.get("arena_id").asLong(),
            json.get("away_team_id").asLong(),
            json.get("home_team_id").asLong(),
            json.get("league_game_id").asInt(),
            json.get("league_id").asString(),
            json.get("season_id").asLong(),
            json.get("attendance").asInt(),
            json.get("away_team_score").asInt(),
            json.get("away_team_score_overtime").asInt(),
            json.get("away_team_score_period1").asInt(),
            json.get("away_team_score_period2").asInt(),
            json.get("away_team_score_period3").asInt(),
            json.get("away_team_series_wins").asInt(),
            json.get("channel").asString(),
            json.get("date_time").asString(),
            json.get("date_time_utc").asString(),
            json.get("day").asInt(),
            json.get("game_time").asString(),
            json.get("home_team_score").asInt(),
            json.get("home_team_score_overtime").asInt(),
            json.get("home_team_score_period1").asInt(),
            json.get("home_team_score_period2").asInt(),
            json.get("home_team_score_period3").asInt(),
            json.get("home_team_series_wins").asInt(),
            json.get("is_overtime").asBoolean(),
            json.get("is_shootout").asBoolean(),
            json.get("last_play").asString(),
            json.get("neutral_site").asBoolean(),
            json.get("overtime_periods").asInt(),
            json.get("period").asString(),
            json.get("playoff_round").asString(),
            json.get("season_type").asString(),
            json.get("series_game_number").asInt(),
            json.get("status").asString(),
            json.get("time_remaining_minutes").asInt(),
            json.get("time_remaining_seconds").asInt()
        );
    }
}
