// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nhl.penalties (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml
package com.statapi.nhl;

import com.statapi.JsonValue;

public record NHLPenalty(
    Long id,
    Long drawnByPlayerId,
    Long gameId,
    Integer penaltyId,
    Long playerId,
    Long teamId,
    String description,
    Boolean isBenchPenalty,
    Integer penaltyMinutes,
    String penaltyType,
    Integer periodNumber,
    String timeRemaining
) {

    public static NHLPenalty fromJson(JsonValue json) {
        return new NHLPenalty(
            json.get("id").asLong(),
            json.get("drawn_by_player_id").asLong(),
            json.get("game_id").asLong(),
            json.get("penalty_id").asInt(),
            json.get("player_id").asLong(),
            json.get("team_id").asLong(),
            json.get("description").asString(),
            json.get("is_bench_penalty").asBoolean(),
            json.get("penalty_minutes").asInt(),
            json.get("penalty_type").asString(),
            json.get("period_number").asInt(),
            json.get("time_remaining").asString()
        );
    }
}
