// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nhl.seasons (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml
package com.statapi.nhl;

import com.statapi.JsonValue;

public record NHLSeason(
    Long id,
    String leagueId,
    String endDate,
    String postSeasonStartDate,
    String regularSeasonStartDate,
    String stanleyCupFinalsDate,
    String startDate,
    Integer startYear
) {

    public static NHLSeason fromJson(JsonValue json) {
        return new NHLSeason(
            json.get("id").asLong(),
            json.get("league_id").asString(),
            json.get("end_date").asString(),
            json.get("post_season_start_date").asString(),
            json.get("regular_season_start_date").asString(),
            json.get("stanley_cup_finals_date").asString(),
            json.get("start_date").asString(),
            json.get("start_year").asInt()
        );
    }
}
