// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for nhl.standings (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml
package com.statapi.nhl;

import com.statapi.JsonValue;

public record NHLStanding(
    Long id,
    Long seasonId,
    Long teamId,
    Integer awayLosses,
    Integer awayOvertimeLosses,
    Integer awayWins,
    Boolean clinchedConference,
    Boolean clinchedDivision,
    Boolean clinchedPlayoffs,
    Boolean clinchedPresidentsTrophy,
    String conference,
    Integer conferenceRank,
    String division,
    Integer divisionRank,
    Integer gamesPlayed,
    Integer goalDifferential,
    Integer goalsAgainst,
    Integer goalsFor,
    Integer homeLosses,
    Integer homeOvertimeLosses,
    Integer homeWins,
    Integer last10Losses,
    Integer last10OvertimeLosses,
    Integer last10Wins,
    Integer losses,
    Integer overtimeLosses,
    Integer pts,
    Double ptsPercentage,
    Integer rank,
    Integer regulationWins,
    String seasonType,
    Integer shootoutLosses,
    Integer shootoutWins,
    String streak,
    Integer wildCardRank,
    Integer wins
) {

    public static NHLStanding fromJson(JsonValue json) {
        return new NHLStanding(
            json.get("id").asLong(),
            json.get("season_id").asLong(),
            json.get("team_id").asLong(),
            json.get("away_losses").asInt(),
            json.get("away_overtime_losses").asInt(),
            json.get("away_wins").asInt(),
            json.get("clinched_conference").asBoolean(),
            json.get("clinched_division").asBoolean(),
            json.get("clinched_playoffs").asBoolean(),
            json.get("clinched_presidents_trophy").asBoolean(),
            json.get("conference").asString(),
            json.get("conference_rank").asInt(),
            json.get("division").asString(),
            json.get("division_rank").asInt(),
            json.get("games_played").asInt(),
            json.get("goal_differential").asInt(),
            json.get("goals_against").asInt(),
            json.get("goals_for").asInt(),
            json.get("home_losses").asInt(),
            json.get("home_overtime_losses").asInt(),
            json.get("home_wins").asInt(),
            json.get("last_10_losses").asInt(),
            json.get("last_10_overtime_losses").asInt(),
            json.get("last_10_wins").asInt(),
            json.get("losses").asInt(),
            json.get("overtime_losses").asInt(),
            json.get("pts").asInt(),
            json.get("pts_percentage").asDouble(),
            json.get("rank").asInt(),
            json.get("regulation_wins").asInt(),
            json.get("season_type").asString(),
            json.get("shootout_losses").asInt(),
            json.get("shootout_wins").asInt(),
            json.get("streak").asString(),
            json.get("wild_card_rank").asInt(),
            json.get("wins").asInt()
        );
    }
}
