// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for nhl.teams (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml
package com.statapi.nhl;

import java.util.LinkedHashMap;
import java.util.Map;

public final class NHLTeamsListParams {

    private Boolean active;
    private Long limit;
    private Long fromId;

    public NHLTeamsListParams active(Boolean active) {
        this.active = active;
        return this;
    }

    public NHLTeamsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public NHLTeamsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (active != null) {
            query.put("active", String.valueOf(active));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
