// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for mlb.broadcasters (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import com.statapi.JsonValue;

public record MLBBroadcaster(
    Long id,
    Integer broadcasterId,
    Integer broadcasterTeamId,
    Integer regionId,
    String broadcasterAbbreviation,
    String broadcasterDescription,
    String broadcasterDisplay,
    String broadcasterMedia,
    Integer broadcasterRanking,
    String broadcasterScope,
    String broadcasterVideoLink,
    String tapeDelayComments
) {

    public static MLBBroadcaster fromJson(JsonValue json) {
        return new MLBBroadcaster(
            json.get("id").asLong(),
            json.get("broadcaster_id").asInt(),
            json.get("broadcaster_team_id").asInt(),
            json.get("region_id").asInt(),
            json.get("broadcaster_abbreviation").asString(),
            json.get("broadcaster_description").asString(),
            json.get("broadcaster_display").asString(),
            json.get("broadcaster_media").asString(),
            json.get("broadcaster_ranking").asInt(),
            json.get("broadcaster_scope").asString(),
            json.get("broadcaster_video_link").asString(),
            json.get("tape_delay_comments").asString()
        );
    }
}
