// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for mlb.game_broadcasters (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import com.statapi.JsonValue;

public record MLBGameBroadcaster(
    Long id,
    Long broadcasterId,
    Long gameId,
    String broadcasterType
) {

    public static MLBGameBroadcaster fromJson(JsonValue json) {
        return new MLBGameBroadcaster(
            json.get("id").asLong(),
            json.get("broadcaster_id").asLong(),
            json.get("game_id").asLong(),
            json.get("broadcaster_type").asString()
        );
    }
}
