// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for mlb.game_umpires (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import com.statapi.JsonValue;

public record MLBGameUmpire(
    Long id,
    Long gameId,
    Long umpireId,
    String position
) {

    public static MLBGameUmpire fromJson(JsonValue json) {
        return new MLBGameUmpire(
            json.get("id").asLong(),
            json.get("game_id").asLong(),
            json.get("umpire_id").asLong(),
            json.get("position").asString()
        );
    }
}
