// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for mlb.game_team_stats (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import com.statapi.JsonValue;

public record MLBGameTeamStat(
    Long id,
    Long gameId,
    Long teamId,
    Integer assists,
    Integer balks,
    Integer battersFaced,
    Double battingAverage,
    Integer caughtStealing,
    Integer doublePlaysTurned,
    Integer doubles,
    Double earnedRunAverage,
    Integer earnedRuns,
    Integer errors,
    Integer groundedIntoDoublePlay,
    Integer hitByPitch,
    Integer hits,
    Integer homeRuns,
    Double inningsPitched,
    Integer leftOnBase,
    Integer loss,
    Double onBasePercentage,
    Double onBasePlusSlugging,
    Integer passedBalls,
    Integer pitchesThrown,
    Integer putouts,
    Integer runs,
    Integer runsBattedIn,
    Integer sacrificeFlies,
    Integer sacrificeHits,
    Double sluggingPercentage,
    Integer stolenBases,
    Integer strikeouts,
    Integer strikes,
    Integer triples,
    Integer walks,
    Integer wildPitches,
    Integer win
) {

    public static MLBGameTeamStat fromJson(JsonValue json) {
        return new MLBGameTeamStat(
            json.get("id").asLong(),
            json.get("game_id").asLong(),
            json.get("team_id").asLong(),
            json.get("assists").asInt(),
            json.get("balks").asInt(),
            json.get("batters_faced").asInt(),
            json.get("batting_average").asDouble(),
            json.get("caught_stealing").asInt(),
            json.get("double_plays_turned").asInt(),
            json.get("doubles").asInt(),
            json.get("earned_run_average").asDouble(),
            json.get("earned_runs").asInt(),
            json.get("errors").asInt(),
            json.get("grounded_into_double_play").asInt(),
            json.get("hit_by_pitch").asInt(),
            json.get("hits").asInt(),
            json.get("home_runs").asInt(),
            json.get("innings_pitched").asDouble(),
            json.get("left_on_base").asInt(),
            json.get("loss").asInt(),
            json.get("on_base_percentage").asDouble(),
            json.get("on_base_plus_slugging").asDouble(),
            json.get("passed_balls").asInt(),
            json.get("pitches_thrown").asInt(),
            json.get("putouts").asInt(),
            json.get("runs").asInt(),
            json.get("runs_batted_in").asInt(),
            json.get("sacrifice_flies").asInt(),
            json.get("sacrifice_hits").asInt(),
            json.get("slugging_percentage").asDouble(),
            json.get("stolen_bases").asInt(),
            json.get("strikeouts").asInt(),
            json.get("strikes").asInt(),
            json.get("triples").asInt(),
            json.get("walks").asInt(),
            json.get("wild_pitches").asInt(),
            json.get("win").asInt()
        );
    }
}
