// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for mlb.game_team_rosters (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import com.statapi.JsonValue;

public record MLBGameTeamRoster(
    Long id,
    Long gameId,
    Long playerId,
    Long teamId,
    Integer battingOrder,
    String comment,
    Integer day,
    String position,
    Boolean starter,
    String status
) {

    public static MLBGameTeamRoster fromJson(JsonValue json) {
        return new MLBGameTeamRoster(
            json.get("id").asLong(),
            json.get("game_id").asLong(),
            json.get("player_id").asLong(),
            json.get("team_id").asLong(),
            json.get("batting_order").asInt(),
            json.get("comment").asString(),
            json.get("day").asInt(),
            json.get("position").asString(),
            json.get("starter").asBoolean(),
            json.get("status").asString()
        );
    }
}
