// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for mlb.operator_team_lookups (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import com.statapi.JsonValue;

public record MLBOperatorTeamLookup(
    Long id,
    Long operatorId,
    String operatorTeamId,
    Long teamId,
    String abbreviation,
    String teamName
) {

    public static MLBOperatorTeamLookup fromJson(JsonValue json) {
        return new MLBOperatorTeamLookup(
            json.get("id").asLong(),
            json.get("operator_id").asLong(),
            json.get("operator_team_id").asString(),
            json.get("team_id").asLong(),
            json.get("abbreviation").asString(),
            json.get("team_name").asString()
        );
    }
}
