// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for mlb.series_odds (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import java.util.LinkedHashMap;
import java.util.Map;

public final class MLBSeriesOddsListParams {

    private Long seasonId;
    private Long limit;
    private Long fromId;

    public MLBSeriesOddsListParams seasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    public MLBSeriesOddsListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public MLBSeriesOddsListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (seasonId != null) {
            query.put("season_id", String.valueOf(seasonId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
