// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for mlb.season_run_environments (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import com.statapi.JsonValue;

public record MLBSeasonRunEnvironment(
    Long id,
    Long seasonId,
    Double battingAverageOnBallsInPlay,
    Double fipConstant,
    Double homeRunPerFlyBall,
    Double runsPerOut,
    Double runsPerPlateAppearance,
    Double strikeoutRate,
    String updatedDate,
    Double walkRate
) {

    public static MLBSeasonRunEnvironment fromJson(JsonValue json) {
        return new MLBSeasonRunEnvironment(
            json.get("id").asLong(),
            json.get("season_id").asLong(),
            json.get("batting_average_on_balls_in_play").asDouble(),
            json.get("fip_constant").asDouble(),
            json.get("home_run_per_fly_ball").asDouble(),
            json.get("runs_per_out").asDouble(),
            json.get("runs_per_plate_appearance").asDouble(),
            json.get("strikeout_rate").asDouble(),
            json.get("updated_date").asString(),
            json.get("walk_rate").asDouble()
        );
    }
}
