// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for mlb.season_team_stats (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import com.statapi.JsonValue;

public record MLBSeasonTeamStat(
    Long id,
    Long seasonId,
    Long teamId,
    Integer atBats,
    Double battingAverage,
    Integer blownSaves,
    Integer caughtStealing,
    Integer completeGames,
    Integer doublePlays,
    Integer doubles,
    Double earnedRunAverage,
    Integer earnedRuns,
    Integer errors,
    Double fieldingPercentage,
    Integer gamesPlayed,
    Integer hits,
    Integer holds,
    Integer homeRuns,
    Double inningsPitched,
    Integer losses,
    Double onBasePercentage,
    Double onBasePlusSlugging,
    Integer runsAllowed,
    Integer runsBattedIn,
    Integer runsScored,
    Integer saveOpportunities,
    Integer saves,
    Integer shutouts,
    Double sluggingPercentage,
    Integer stolenBases,
    Integer strikeouts,
    Integer ties,
    Integer triples,
    Integer walks,
    Double whip,
    Integer wins
) {

    public static MLBSeasonTeamStat fromJson(JsonValue json) {
        return new MLBSeasonTeamStat(
            json.get("id").asLong(),
            json.get("season_id").asLong(),
            json.get("team_id").asLong(),
            json.get("at_bats").asInt(),
            json.get("batting_average").asDouble(),
            json.get("blown_saves").asInt(),
            json.get("caught_stealing").asInt(),
            json.get("complete_games").asInt(),
            json.get("double_plays").asInt(),
            json.get("doubles").asInt(),
            json.get("earned_run_average").asDouble(),
            json.get("earned_runs").asInt(),
            json.get("errors").asInt(),
            json.get("fielding_percentage").asDouble(),
            json.get("games_played").asInt(),
            json.get("hits").asInt(),
            json.get("holds").asInt(),
            json.get("home_runs").asInt(),
            json.get("innings_pitched").asDouble(),
            json.get("losses").asInt(),
            json.get("on_base_percentage").asDouble(),
            json.get("on_base_plus_slugging").asDouble(),
            json.get("runs_allowed").asInt(),
            json.get("runs_batted_in").asInt(),
            json.get("runs_scored").asInt(),
            json.get("save_opportunities").asInt(),
            json.get("saves").asInt(),
            json.get("shutouts").asInt(),
            json.get("slugging_percentage").asDouble(),
            json.get("stolen_bases").asInt(),
            json.get("strikeouts").asInt(),
            json.get("ties").asInt(),
            json.get("triples").asInt(),
            json.get("walks").asInt(),
            json.get("whip").asDouble(),
            json.get("wins").asInt()
        );
    }
}
