// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for mlb.team_starting_lineups (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import com.statapi.JsonValue;

public record MLBTeamStartingLineup(
    Long id,
    Long gameId,
    Long pitcherId,
    Long teamId,
    Integer batterStatus,
    Integer pitcherStatus
) {

    public static MLBTeamStartingLineup fromJson(JsonValue json) {
        return new MLBTeamStartingLineup(
            json.get("id").asLong(),
            json.get("game_id").asLong(),
            json.get("pitcher_id").asLong(),
            json.get("team_id").asLong(),
            json.get("batter_status").asInt(),
            json.get("pitcher_status").asInt()
        );
    }
}
