// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for mlb.venue_weathers (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml
package com.statapi.mlb;

import java.util.LinkedHashMap;
import java.util.Map;

public final class MLBVenueWeathersListParams {

    private Long gameId;
    private Long venueId;
    private Long limit;
    private Long fromId;

    public MLBVenueWeathersListParams gameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    public MLBVenueWeathersListParams venueId(Long venueId) {
        this.venueId = venueId;
        return this;
    }

    public MLBVenueWeathersListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public MLBVenueWeathersListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (gameId != null) {
            query.put("game_id", String.valueOf(gameId));
        }
        if (venueId != null) {
            query.put("venue_id", String.valueOf(venueId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
