# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for nba.game_team_stats (public API).
# Source: schema/api/groups/public.yml + schema/model/nba/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

NBAGameTeamStat = TypedDict(
    "NBAGameTeamStat",
    {
        "id": int,
        "game_id": int,
        "team_id": int,
        "assist_percentage": float,
        "assist_ratio": float,
        "assists": int,
        "assists_to_turnovers": float,
        "bench_pts": int,
        "blocks": int,
        "conference_rank": int,
        "defensive_rating": float,
        "defensive_rebound_percentage": float,
        "defensive_rebounds": int,
        "effective_field_goal_percentage": float,
        "estimated_defensive_rating": float,
        "estimated_net_rating": float,
        "estimated_offensive_rating": float,
        "estimated_pace": float,
        "fast_break_pts": int,
        "field_goal_percentage": float,
        "field_goals_attempted": int,
        "field_goals_made": int,
        "fouls": int,
        "free_throw_attempt_rate": float,
        "free_throw_percentage": float,
        "free_throws_attempted": int,
        "free_throws_made": int,
        "loss": int,
        "losses": int,
        "minutes": int,
        "net_rating": float,
        "offensive_rating": float,
        "offensive_rebound_percentage": float,
        "offensive_rebounds": int,
        "pace": float,
        "pace_per40": float,
        "pct_ast_2pm": float,
        "pct_ast_3pm": float,
        "pct_ast_fgm": float,
        "pct_fga_2pt": float,
        "pct_fga_3pt": float,
        "pct_pts_2pt": float,
        "pct_pts_2pt_mr": float,
        "pct_pts_3pt": float,
        "pct_pts_fb": float,
        "pct_pts_ft": float,
        "pct_pts_off_tov": float,
        "pct_pts_paint": float,
        "pct_uast_2pm": float,
        "pct_uast_3pm": float,
        "pct_uast_fgm": float,
        "player_impact_estimate": float,
        "possessions": int,
        "pts": int,
        "pts_in_paint": int,
        "pts_off_turnovers": int,
        "rebound_percentage": float,
        "rebounds": int,
        "second_chance_pts": int,
        "steals": int,
        "steals_to_turnovers": float,
        "three_point_percentage": float,
        "three_pointers_attempted": int,
        "three_pointers_made": int,
        "timeouts_remaining": int,
        "true_shooting_percentage": float,
        "turnover_percentage": float,
        "turnovers": int,
        "win": int,
        "wins": int,
    },
)


class NBAGameTeamStatsResource:
    _PATH = "/api/v1/nba/game_team_stats"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, game_id: int | None = None, team_id: int | None = None, limit: int | None = None, from_id: int | None = None) -> Page[NBAGameTeamStat]:
        body, quota = self._transport.request(self._PATH, {
            "game_id": game_id,
            "team_id": team_id,
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[NBAGameTeamStat] = body["game_team_stats"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> NBAGameTeamStat:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: NBAGameTeamStat = body
        return row

    def iter(self, *, game_id: int | None = None, team_id: int | None = None, limit: int | None = None) -> Iterator[NBAGameTeamStat]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(game_id=game_id, team_id=team_id, limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
