# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# SDK resource for nba.seasons (public API).
# Source: schema/api/groups/public.yml + schema/model/nba/*.yml

from __future__ import annotations

from collections.abc import Iterator
from typing import TypedDict

from ..page import Page
from ..transport import HttpTransport

NBASeason = TypedDict(
    "NBASeason",
    {
        "id": int,
        "end_date": str | None,
        "post_season_start_date": str | None,
        "regular_season_start_date": str | None,
        "start_date": str,
        "start_year": int,
    },
)


class NBASeasonsResource:
    _PATH = "/api/v1/nba/seasons"

    def __init__(self, transport: HttpTransport) -> None:
        self._transport = transport

    def list(self, *, limit: int | None = None, from_id: int | None = None) -> Page[NBASeason]:
        body, quota = self._transport.request(self._PATH, {
            "limit": limit,
            "from_id": from_id,
        })
        rows: list[NBASeason] = body["seasons"]
        return Page(
            rows=rows,
            limit=body.get("limit"),
            next_from_id=body.get("next_from_id"),
            quota=quota,
        )

    def get(self, id: int) -> NBASeason:
        body, _ = self._transport.request(f"{self._PATH}/{id}")
        row: NBASeason = body
        return row

    def iter(self, *, limit: int | None = None) -> Iterator[NBASeason]:
        # Always walk with from_id (starting at 0): from_id forces the server's
        # ascending keyset order. Without it, DESC-default tables re-yield page
        # 1 and under-walk. Iteration is therefore always oldest-first.
        from_id: int | None = 0
        while True:
            page = self.list(limit=limit, from_id=from_id)
            for row in page.rows:
                yield row
            if page.next_from_id is None:
                return
            from_id = page.next_from_id
