// DO NOT EDIT — generated by generate-sdk-smoke.ts
//
// Live smoke for the statapi Java SDK. Runs six probes against
// STAT_API_BASE_URL (default https://api.stat-api.com) with STAT_API_KEY. Compiled
// separately from the library tree against the built library classes.
import com.statapi.AuthenticationException;
import com.statapi.Page;
import com.statapi.StatApi;
import com.statapi.dfs.DFSContestUsersListParams;
import com.statapi.nba.NBATeam;
import com.statapi.nba.NBATeamsListParams;

public final class Smoke {

    private static int failures = 0;

    private static void pass(String probe, String msg) {
        System.out.println("PASS " + probe + "  " + msg);
    }

    private static void fail(String probe, String msg) {
        failures++;
        System.out.println("FAIL " + probe + "  " + msg);
    }

    public static void main(String[] args) {
        String baseUrl = System.getenv("STAT_API_BASE_URL");
        if (baseUrl == null || baseUrl.isEmpty()) {
            baseUrl = "https://api.stat-api.com";
        }
        String key = System.getenv("STAT_API_KEY");
        if (key == null || key.isEmpty()) {
            System.err.println("STAT_API_KEY is required");
            System.exit(2);
        }

        StatApi api = new StatApi(key, baseUrl);

        // probe1 — plain list
        Long firstId = null;
        try {
            Page<NBATeam> page = api.nba().teams().list(new NBATeamsListParams().limit(2L));
            if (page.rows().size() >= 1) {
                firstId = page.rows().get(0).id();
                pass("probe1-list", "nba.teams limit=2 -> " + page.rows().size() + " rows");
            } else {
                fail("probe1-list", "nba.teams returned 0 rows");
            }
        } catch (Exception e) {
            fail("probe1-list", e.toString());
        }

        // probe2 — required-filter-set table via smoke params
        try {
            Page<?> page = api.dfs().contestUsers().list(new DFSContestUsersListParams().operatorId(1L));
            pass("probe2-required-set", "dfs.contest_users via smoke params -> " + page.rows().size() + " rows");
        } catch (Exception e) {
            fail("probe2-required-set", e.toString());
        }

        // probe3 — get(id)
        try {
            if (firstId == null) {
                fail("probe3-get", "no id from probe1");
            } else {
                NBATeam row = api.nba().teams().get(firstId);
                if (row.id().equals(firstId)) {
                    pass("probe3-get", "get(" + firstId + ") ok");
                } else {
                    fail("probe3-get", "id mismatch " + row.id());
                }
            }
        } catch (Exception e) {
            fail("probe3-get", e.toString());
        }

        // probe4 — two-page keyset walk
        try {
            Page<NBATeam> p1 = api.nba().teams().list(new NBATeamsListParams().limit(2L));
            Long cursor = p1.nextFromId();
            if (cursor == null) {
                fail("probe4-paginate", "page1 next_from_id is null");
            } else {
                Page<NBATeam> p2 = api.nba().teams().list(new NBATeamsListParams().limit(2L).fromId(cursor));
                boolean advanced = p2.rows().size() >= 1;
                for (NBATeam r : p2.rows()) {
                    if (r.id() <= cursor) {
                        advanced = false;
                    }
                }
                if (advanced) {
                    pass("probe4-paginate", "page2 ids advance past " + cursor);
                } else {
                    fail("probe4-paginate", "page2 did not advance");
                }
            }
        } catch (Exception e) {
            fail("probe4-paginate", e.toString());
        }

        // probe5 — bad key -> AuthenticationException
        try {
            StatApi bad = new StatApi("sdb_bad_00000000000000000000000000000000", baseUrl);
            bad.nba().teams().list(new NBATeamsListParams().limit(2L));
            fail("probe5-auth", "bad key did not raise");
        } catch (AuthenticationException e) {
            pass("probe5-auth", "bad key -> AuthenticationException");
        } catch (Exception e) {
            fail("probe5-auth", "wrong error type: " + e.getClass().getSimpleName());
        }

        // probe6 — quota surfaced on the list Page
        try {
            Page<NBATeam> page = api.nba().teams().list(new NBATeamsListParams().limit(2L));
            if (page.quota() != null) {
                pass("probe6-quota", "quota surfaced (limit=" + page.quota().limit() + ")");
            } else {
                fail("probe6-quota", "no quota on list response");
            }
        } catch (Exception e) {
            fail("probe6-quota", e.toString());
        }

        System.exit(failures == 0 ? 0 : 1);
    }
}
