// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for dfs.contest_users (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// DFSContestUser is a row from dfs.contest_users.
type DFSContestUser struct {
	ID         int64   `json:"id"`
	ExternalID string  `json:"external_id"`
	OperatorID int64   `json:"operator_id"`
	Name       *string `json:"name"`
}

// DFSContestUsersListParams are the query parameters for listing dfs.contest_users.
type DFSContestUsersListParams struct {
	OperatorID *int64
	Limit      *int
	FromID     *int64
}

func (p *DFSContestUsersListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.OperatorID != nil {
		v.Set("operator_id", strconv.FormatInt(*p.OperatorID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// DFSContestUsersPage is one page of dfs.contest_users results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type DFSContestUsersPage struct {
	Rows       []DFSContestUser `json:"contest_users"`
	Limit      int              `json:"limit"`
	NextFromID *int64           `json:"next_from_id"`
	Quota      Quota            `json:"-"`
}

// DFSContestUsersService accesses the dfs.contest_users endpoints.
type DFSContestUsersService struct {
	client *Client
}

// List returns one page of dfs.contest_users matching params
// (pass nil for no filters).
func (s *DFSContestUsersService) List(ctx context.Context, params *DFSContestUsersListParams) (*DFSContestUsersPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/dfs/contest_users", params.values())
	if err != nil {
		return nil, err
	}
	var page DFSContestUsersPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single dfs.contest_users row by id.
func (s *DFSContestUsersService) Get(ctx context.Context, id int64) (*DFSContestUser, error) {
	body, _, err := s.client.get(ctx, "/api/v1/dfs/contest_users/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row DFSContestUser
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates dfs.contest_users, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *DFSContestUsersService) All(ctx context.Context, params *DFSContestUsersListParams) iter.Seq2[DFSContestUser, error] {
	return func(yield func(DFSContestUser, error) bool) {
		page := DFSContestUsersListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero DFSContestUser
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
