// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for dfs.slate_settings (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// DFSSlateSetting is a row from dfs.slate_settings.
type DFSSlateSetting struct {
	ID          int64           `json:"id"`
	LeagueID    int64           `json:"league_id"`
	OperatorID  int64           `json:"operator_id"`
	ContestType int             `json:"contest_type"`
	GameStyle   *string         `json:"game_style"`
	GameType    int             `json:"game_type"`
	Name        string          `json:"name"`
	Settings    json.RawMessage `json:"settings"`
}

// DFSSlateSettingsListParams are the query parameters for listing dfs.slate_settings.
type DFSSlateSettingsListParams struct {
	Limit  *int
	FromID *int64
}

func (p *DFSSlateSettingsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// DFSSlateSettingsPage is one page of dfs.slate_settings results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type DFSSlateSettingsPage struct {
	Rows       []DFSSlateSetting `json:"slate_settings"`
	Limit      int               `json:"limit"`
	NextFromID *int64            `json:"next_from_id"`
	Quota      Quota             `json:"-"`
}

// DFSSlateSettingsService accesses the dfs.slate_settings endpoints.
type DFSSlateSettingsService struct {
	client *Client
}

// List returns one page of dfs.slate_settings matching params
// (pass nil for no filters).
func (s *DFSSlateSettingsService) List(ctx context.Context, params *DFSSlateSettingsListParams) (*DFSSlateSettingsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/dfs/slate_settings", params.values())
	if err != nil {
		return nil, err
	}
	var page DFSSlateSettingsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single dfs.slate_settings row by id.
func (s *DFSSlateSettingsService) Get(ctx context.Context, id int64) (*DFSSlateSetting, error) {
	body, _, err := s.client.get(ctx, "/api/v1/dfs/slate_settings/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row DFSSlateSetting
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates dfs.slate_settings, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *DFSSlateSettingsService) All(ctx context.Context, params *DFSSlateSettingsListParams) iter.Seq2[DFSSlateSetting, error] {
	return func(yield func(DFSSlateSetting, error) bool) {
		page := DFSSlateSettingsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero DFSSlateSetting
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
