// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for dfs.slate_players (public API).
// Source: schema/api/groups/public.yml + schema/model/dfs/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// DFSSlatePlayer is a row from dfs.slate_players.
type DFSSlatePlayer struct {
	ID             int64    `json:"id"`
	ExportID       *string  `json:"export_id"`
	ExternalID     *string  `json:"external_id"`
	LeagueID       int64    `json:"league_id"`
	PlayerID       int64    `json:"player_id"`
	SlateGameID    int64    `json:"slate_game_id"`
	SlateID        int64    `json:"slate_id"`
	TeamID         *int64   `json:"team_id"`
	AvgPoints      *float64 `json:"avg_points"`
	DisplayName    *string  `json:"display_name"`
	FirstName      *string  `json:"first_name"`
	InjuryDetails  *string  `json:"injury_details"`
	InjuryStatus   *string  `json:"injury_status"`
	LastName       *string  `json:"last_name"`
	Position       string   `json:"position"`
	RosterPosition string   `json:"roster_position"`
	Salary         int      `json:"salary"`
}

// DFSSlatePlayersListParams are the query parameters for listing dfs.slate_players.
type DFSSlatePlayersListParams struct {
	SlateID *int64
	Limit   *int
	FromID  *int64
}

func (p *DFSSlatePlayersListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.SlateID != nil {
		v.Set("slate_id", strconv.FormatInt(*p.SlateID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// DFSSlatePlayersPage is one page of dfs.slate_players results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type DFSSlatePlayersPage struct {
	Rows       []DFSSlatePlayer `json:"slate_players"`
	Limit      int              `json:"limit"`
	NextFromID *int64           `json:"next_from_id"`
	Quota      Quota            `json:"-"`
}

// DFSSlatePlayersService accesses the dfs.slate_players endpoints.
type DFSSlatePlayersService struct {
	client *Client
}

// List returns one page of dfs.slate_players matching params
// (pass nil for no filters).
func (s *DFSSlatePlayersService) List(ctx context.Context, params *DFSSlatePlayersListParams) (*DFSSlatePlayersPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/dfs/slate_players", params.values())
	if err != nil {
		return nil, err
	}
	var page DFSSlatePlayersPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single dfs.slate_players row by id.
func (s *DFSSlatePlayersService) Get(ctx context.Context, id int64) (*DFSSlatePlayer, error) {
	body, _, err := s.client.get(ctx, "/api/v1/dfs/slate_players/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row DFSSlatePlayer
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates dfs.slate_players, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *DFSSlatePlayersService) All(ctx context.Context, params *DFSSlatePlayersListParams) iter.Seq2[DFSSlatePlayer, error] {
	return func(yield func(DFSSlatePlayer, error) bool) {
		page := DFSSlatePlayersListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero DFSSlatePlayer
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
