// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for kalshi.series (public API).
// Source: schema/api/groups/public.yml + schema/model/kalshi/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// KalshiSeries is a row from kalshi.series.
type KalshiSeries struct {
	ID           int64   `json:"id"`
	Category     string  `json:"category"`
	ContractType *string `json:"contract_type"`
	Frequency    *string `json:"frequency"`
	IsActive     bool    `json:"is_active"`
	LeagueCode   *string `json:"league_code"`
	SeriesTicker string  `json:"series_ticker"`
	Title        string  `json:"title"`
}

// KalshiSeriesListParams are the query parameters for listing kalshi.series.
type KalshiSeriesListParams struct {
	Limit  *int
	FromID *int64
}

func (p *KalshiSeriesListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// KalshiSeriesPage is one page of kalshi.series results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type KalshiSeriesPage struct {
	Rows       []KalshiSeries `json:"series"`
	Limit      int            `json:"limit"`
	NextFromID *int64         `json:"next_from_id"`
	Quota      Quota          `json:"-"`
}

// KalshiSeriesService accesses the kalshi.series endpoints.
type KalshiSeriesService struct {
	client *Client
}

// List returns one page of kalshi.series matching params
// (pass nil for no filters).
func (s *KalshiSeriesService) List(ctx context.Context, params *KalshiSeriesListParams) (*KalshiSeriesPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/kalshi/series", params.values())
	if err != nil {
		return nil, err
	}
	var page KalshiSeriesPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single kalshi.series row by id.
func (s *KalshiSeriesService) Get(ctx context.Context, id int64) (*KalshiSeries, error) {
	body, _, err := s.client.get(ctx, "/api/v1/kalshi/series/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row KalshiSeries
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates kalshi.series, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *KalshiSeriesService) All(ctx context.Context, params *KalshiSeriesListParams) iter.Seq2[KalshiSeries, error] {
	return func(yield func(KalshiSeries, error) bool) {
		page := KalshiSeriesListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero KalshiSeries
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
