// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for kalshi.events (public API).
// Source: schema/api/groups/public.yml + schema/model/kalshi/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// KalshiEvent is a row from kalshi.events.
type KalshiEvent struct {
	ID            int64   `json:"id"`
	CompetitionID *int64  `json:"competition_id"`
	LeagueGameID  *string `json:"league_game_id"`
	SeriesID      int64   `json:"series_id"`
	AwayTeam      *string `json:"away_team"`
	Category      string  `json:"category"`
	EventTicker   string  `json:"event_ticker"`
	GameDate      *string `json:"game_date"`
	HomeTeam      *string `json:"home_team"`
	LeagueCode    *string `json:"league_code"`
	MarketCount   *int    `json:"market_count"`
	SettledAt     *string `json:"settled_at"`
	Status        string  `json:"status"`
	Title         string  `json:"title"`
}

// KalshiEventsListParams are the query parameters for listing kalshi.events.
type KalshiEventsListParams struct {
	SeriesID      *int64
	CompetitionID *int64
	LeagueCode    *string
	Limit         *int
	FromID        *int64
}

func (p *KalshiEventsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.SeriesID != nil {
		v.Set("series_id", strconv.FormatInt(*p.SeriesID, 10))
	}
	if p.CompetitionID != nil {
		v.Set("competition_id", strconv.FormatInt(*p.CompetitionID, 10))
	}
	if p.LeagueCode != nil {
		v.Set("league_code", *p.LeagueCode)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// KalshiEventsPage is one page of kalshi.events results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type KalshiEventsPage struct {
	Rows       []KalshiEvent `json:"events"`
	Limit      int           `json:"limit"`
	NextFromID *int64        `json:"next_from_id"`
	Quota      Quota         `json:"-"`
}

// KalshiEventsService accesses the kalshi.events endpoints.
type KalshiEventsService struct {
	client *Client
}

// List returns one page of kalshi.events matching params
// (pass nil for no filters).
func (s *KalshiEventsService) List(ctx context.Context, params *KalshiEventsListParams) (*KalshiEventsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/kalshi/events", params.values())
	if err != nil {
		return nil, err
	}
	var page KalshiEventsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single kalshi.events row by id.
func (s *KalshiEventsService) Get(ctx context.Context, id int64) (*KalshiEvent, error) {
	body, _, err := s.client.get(ctx, "/api/v1/kalshi/events/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row KalshiEvent
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates kalshi.events, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *KalshiEventsService) All(ctx context.Context, params *KalshiEventsListParams) iter.Seq2[KalshiEvent, error] {
	return func(yield func(KalshiEvent, error) bool) {
		page := KalshiEventsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero KalshiEvent
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
