// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.game_broadcasters (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBGameBroadcaster is a row from mlb.game_broadcasters.
type MLBGameBroadcaster struct {
	ID              int64  `json:"id"`
	BroadcasterID   int64  `json:"broadcaster_id"`
	GameID          int64  `json:"game_id"`
	BroadcasterType string `json:"broadcaster_type"`
}

// MLBGameBroadcastersListParams are the query parameters for listing mlb.game_broadcasters.
type MLBGameBroadcastersListParams struct {
	GameID *int64
	Limit  *int
	FromID *int64
}

func (p *MLBGameBroadcastersListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBGameBroadcastersPage is one page of mlb.game_broadcasters results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBGameBroadcastersPage struct {
	Rows       []MLBGameBroadcaster `json:"game_broadcasters"`
	Limit      int                  `json:"limit"`
	NextFromID *int64               `json:"next_from_id"`
	Quota      Quota                `json:"-"`
}

// MLBGameBroadcastersService accesses the mlb.game_broadcasters endpoints.
type MLBGameBroadcastersService struct {
	client *Client
}

// List returns one page of mlb.game_broadcasters matching params
// (pass nil for no filters).
func (s *MLBGameBroadcastersService) List(ctx context.Context, params *MLBGameBroadcastersListParams) (*MLBGameBroadcastersPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/game_broadcasters", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBGameBroadcastersPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.game_broadcasters row by id.
func (s *MLBGameBroadcastersService) Get(ctx context.Context, id int64) (*MLBGameBroadcaster, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/game_broadcasters/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBGameBroadcaster
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.game_broadcasters, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBGameBroadcastersService) All(ctx context.Context, params *MLBGameBroadcastersListParams) iter.Seq2[MLBGameBroadcaster, error] {
	return func(yield func(MLBGameBroadcaster, error) bool) {
		page := MLBGameBroadcastersListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBGameBroadcaster
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
