// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.park_factors (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBParkFactor is a row from mlb.park_factors.
type MLBParkFactor struct {
	ID                int64    `json:"id"`
	SeasonID          int64    `json:"season_id"`
	VenueID           int64    `json:"venue_id"`
	BasicParkFactor   float64  `json:"basic_park_factor"`
	DoubleFactor      float64  `json:"double_factor"`
	FlyBallFactor     *float64 `json:"fly_ball_factor"`
	GroundBallFactor  *float64 `json:"ground_ball_factor"`
	HandednessFactor  float64  `json:"handedness_factor"`
	HomeRunFactor     float64  `json:"home_run_factor"`
	LeftHandedFactor  float64  `json:"left_handed_factor"`
	RightHandedFactor float64  `json:"right_handed_factor"`
	RunFactor         *float64 `json:"run_factor"`
	SingleFactor      float64  `json:"single_factor"`
	StrikeoutFactor   float64  `json:"strikeout_factor"`
	TripleFactor      float64  `json:"triple_factor"`
	UpdatedDate       string   `json:"updated_date"`
	WalkFactor        float64  `json:"walk_factor"`
	YearsOfData       int      `json:"years_of_data"`
}

// MLBParkFactorsListParams are the query parameters for listing mlb.park_factors.
type MLBParkFactorsListParams struct {
	VenueID  *int64
	SeasonID *int64
	Limit    *int
	FromID   *int64
}

func (p *MLBParkFactorsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.VenueID != nil {
		v.Set("venue_id", strconv.FormatInt(*p.VenueID, 10))
	}
	if p.SeasonID != nil {
		v.Set("season_id", strconv.FormatInt(*p.SeasonID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBParkFactorsPage is one page of mlb.park_factors results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBParkFactorsPage struct {
	Rows       []MLBParkFactor `json:"park_factors"`
	Limit      int             `json:"limit"`
	NextFromID *int64          `json:"next_from_id"`
	Quota      Quota           `json:"-"`
}

// MLBParkFactorsService accesses the mlb.park_factors endpoints.
type MLBParkFactorsService struct {
	client *Client
}

// List returns one page of mlb.park_factors matching params
// (pass nil for no filters).
func (s *MLBParkFactorsService) List(ctx context.Context, params *MLBParkFactorsListParams) (*MLBParkFactorsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/park_factors", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBParkFactorsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.park_factors row by id.
func (s *MLBParkFactorsService) Get(ctx context.Context, id int64) (*MLBParkFactor, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/park_factors/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBParkFactor
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.park_factors, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBParkFactorsService) All(ctx context.Context, params *MLBParkFactorsListParams) iter.Seq2[MLBParkFactor, error] {
	return func(yield func(MLBParkFactor, error) bool) {
		page := MLBParkFactorsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBParkFactor
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
