// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.woba_weights (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBWobaWeight is a row from mlb.woba_weights.
type MLBWobaWeight struct {
	ID               int64   `json:"id"`
	SeasonID         int64   `json:"season_id"`
	DoubleWeight     float64 `json:"double_weight"`
	HitByPitchWeight float64 `json:"hit_by_pitch_weight"`
	HomeRunWeight    float64 `json:"home_run_weight"`
	LeagueObp        float64 `json:"league_obp"`
	LeagueWoba       float64 `json:"league_woba"`
	SingleWeight     float64 `json:"single_weight"`
	TripleWeight     float64 `json:"triple_weight"`
	UpdatedDate      string  `json:"updated_date"`
	WalkWeight       float64 `json:"walk_weight"`
	WobaScale        float64 `json:"woba_scale"`
}

// MLBWobaWeightsListParams are the query parameters for listing mlb.woba_weights.
type MLBWobaWeightsListParams struct {
	Limit  *int
	FromID *int64
}

func (p *MLBWobaWeightsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBWobaWeightsPage is one page of mlb.woba_weights results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBWobaWeightsPage struct {
	Rows       []MLBWobaWeight `json:"woba_weights"`
	Limit      int             `json:"limit"`
	NextFromID *int64          `json:"next_from_id"`
	Quota      Quota           `json:"-"`
}

// MLBWobaWeightsService accesses the mlb.woba_weights endpoints.
type MLBWobaWeightsService struct {
	client *Client
}

// List returns one page of mlb.woba_weights matching params
// (pass nil for no filters).
func (s *MLBWobaWeightsService) List(ctx context.Context, params *MLBWobaWeightsListParams) (*MLBWobaWeightsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/woba_weights", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBWobaWeightsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.woba_weights row by id.
func (s *MLBWobaWeightsService) Get(ctx context.Context, id int64) (*MLBWobaWeight, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/woba_weights/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBWobaWeight
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.woba_weights, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBWobaWeightsService) All(ctx context.Context, params *MLBWobaWeightsListParams) iter.Seq2[MLBWobaWeight, error] {
	return func(yield func(MLBWobaWeight, error) bool) {
		page := MLBWobaWeightsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBWobaWeight
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
