// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.at_bats (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBAtBat is a row from mlb.at_bats.
type MLBAtBat struct {
	ID                   int64    `json:"id"`
	BatterID             int64    `json:"batter_id"`
	GameID               int64    `json:"game_id"`
	InningID             int64    `json:"inning_id"`
	PitcherID            int64    `json:"pitcher_id"`
	AtBatNumber          int      `json:"at_bat_number"`
	Balls                int      `json:"balls"`
	EndOuts              int      `json:"end_outs"`
	EndRunners           int      `json:"end_runners"`
	ExpectedBattingAvg   *float64 `json:"expected_batting_avg"`
	ExpectedWoba         *float64 `json:"expected_woba"`
	HitCoordX            *float64 `json:"hit_coord_x"`
	HitCoordY            *float64 `json:"hit_coord_y"`
	HitDistance          *int     `json:"hit_distance"`
	HitExitVelocity      *float64 `json:"hit_exit_velocity"`
	HitLaunchAngle       *float64 `json:"hit_launch_angle"`
	HitLocation          *string  `json:"hit_location"`
	HitType              *string  `json:"hit_type"`
	IsBarrel             *bool    `json:"is_barrel"`
	IsFlareBurner        *bool    `json:"is_flare_burner"`
	IsHardHit            *bool    `json:"is_hard_hit"`
	IsSolidContact       *bool    `json:"is_solid_contact"`
	IsSweetSpot          *bool    `json:"is_sweet_spot"`
	IsTopped             *bool    `json:"is_topped"`
	IsUnder              *bool    `json:"is_under"`
	LaunchSpeedAngleZone *int     `json:"launch_speed_angle_zone"`
	PitchCount           int      `json:"pitch_count"`
	Result               string   `json:"result"`
	RunsScored           int      `json:"runs_scored"`
	SprayAngle           *float64 `json:"spray_angle"`
	StartOuts            int      `json:"start_outs"`
	StartRunners         int      `json:"start_runners"`
	StatcastQualityScore *float64 `json:"statcast_quality_score"`
	Strikes              int      `json:"strikes"`
	TrackingConfidence   *float64 `json:"tracking_confidence"`
}

// MLBAtBatsListParams are the query parameters for listing mlb.at_bats.
type MLBAtBatsListParams struct {
	GameID *int64
	Limit  *int
	FromID *int64
}

func (p *MLBAtBatsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBAtBatsPage is one page of mlb.at_bats results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBAtBatsPage struct {
	Rows       []MLBAtBat `json:"at_bats"`
	Limit      int        `json:"limit"`
	NextFromID *int64     `json:"next_from_id"`
	Quota      Quota      `json:"-"`
}

// MLBAtBatsService accesses the mlb.at_bats endpoints.
type MLBAtBatsService struct {
	client *Client
}

// List returns one page of mlb.at_bats matching params
// (pass nil for no filters).
func (s *MLBAtBatsService) List(ctx context.Context, params *MLBAtBatsListParams) (*MLBAtBatsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/at_bats", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBAtBatsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.at_bats row by id.
func (s *MLBAtBatsService) Get(ctx context.Context, id int64) (*MLBAtBat, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/at_bats/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBAtBat
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.at_bats, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBAtBatsService) All(ctx context.Context, params *MLBAtBatsListParams) iter.Seq2[MLBAtBat, error] {
	return func(yield func(MLBAtBat, error) bool) {
		page := MLBAtBatsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBAtBat
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
