// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.umpires (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBUmpire is a row from mlb.umpires.
type MLBUmpire struct {
	ID           int64   `json:"id"`
	MlbUmpireID  int     `json:"mlb_umpire_id"`
	Active       bool    `json:"active"`
	BirthCity    *string `json:"birth_city"`
	BirthCountry *string `json:"birth_country"`
	BirthDate    *string `json:"birth_date"`
	BirthState   *string `json:"birth_state"`
	Experience   *int    `json:"experience"`
	FirstName    string  `json:"first_name"`
	FullName     string  `json:"full_name"`
	LastName     string  `json:"last_name"`
}

// MLBUmpiresListParams are the query parameters for listing mlb.umpires.
type MLBUmpiresListParams struct {
	Active *bool
	Limit  *int
	FromID *int64
}

func (p *MLBUmpiresListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Active != nil {
		v.Set("active", strconv.FormatBool(*p.Active))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBUmpiresPage is one page of mlb.umpires results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBUmpiresPage struct {
	Rows       []MLBUmpire `json:"umpires"`
	Limit      int         `json:"limit"`
	NextFromID *int64      `json:"next_from_id"`
	Quota      Quota       `json:"-"`
}

// MLBUmpiresService accesses the mlb.umpires endpoints.
type MLBUmpiresService struct {
	client *Client
}

// List returns one page of mlb.umpires matching params
// (pass nil for no filters).
func (s *MLBUmpiresService) List(ctx context.Context, params *MLBUmpiresListParams) (*MLBUmpiresPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/umpires", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBUmpiresPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.umpires row by id.
func (s *MLBUmpiresService) Get(ctx context.Context, id int64) (*MLBUmpire, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/umpires/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBUmpire
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.umpires, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBUmpiresService) All(ctx context.Context, params *MLBUmpiresListParams) iter.Seq2[MLBUmpire, error] {
	return func(yield func(MLBUmpire, error) bool) {
		page := MLBUmpiresListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBUmpire
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
