// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.games (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBGame is a row from mlb.games.
type MLBGame struct {
	ID               int64   `json:"id"`
	AwayTeamID       int64   `json:"away_team_id"`
	HomeTeamID       int64   `json:"home_team_id"`
	LeagueGameID     *int    `json:"league_game_id"`
	LeagueID         *string `json:"league_id"`
	LosingPitcherID  *int64  `json:"losing_pitcher_id"`
	SavePitcherID    *int64  `json:"save_pitcher_id"`
	SeasonID         int64   `json:"season_id"`
	VenueID          *int64  `json:"venue_id"`
	WinningPitcherID *int64  `json:"winning_pitcher_id"`
	Attendance       *int    `json:"attendance"`
	AwayTeamScore    int     `json:"away_team_score"`
	Channel          *string `json:"channel"`
	Day              int     `json:"day"`
	DayNight         *string `json:"day_night"`
	Doubleheader     bool    `json:"doubleheader"`
	DurationMinutes  *int    `json:"duration_minutes"`
	EndTime          *string `json:"end_time"`
	GameLabel        *string `json:"game_label"`
	GameNumber       int     `json:"game_number"`
	GameTime         string  `json:"game_time"`
	GameType         string  `json:"game_type"`
	HomeTeamScore    int     `json:"home_team_score"`
	IfNecessary      *bool   `json:"if_necessary"`
	NeutralVenue     bool    `json:"neutral_venue"`
	PostponedStatus  *string `json:"postponed_status"`
	SeasonType       string  `json:"season_type"`
	SeriesGameNumber *string `json:"series_game_number"`
	SeriesName       *string `json:"series_name"`
	SeriesText       *string `json:"series_text"`
	Status           string  `json:"status"`
}

// MLBGamesListParams are the query parameters for listing mlb.games.
type MLBGamesListParams struct {
	SeasonID   *int64
	HomeTeamID *int64
	AwayTeamID *int64
	Status     *string
	Day        *int
	Limit      *int
	FromID     *int64
}

func (p *MLBGamesListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.SeasonID != nil {
		v.Set("season_id", strconv.FormatInt(*p.SeasonID, 10))
	}
	if p.HomeTeamID != nil {
		v.Set("home_team_id", strconv.FormatInt(*p.HomeTeamID, 10))
	}
	if p.AwayTeamID != nil {
		v.Set("away_team_id", strconv.FormatInt(*p.AwayTeamID, 10))
	}
	if p.Status != nil {
		v.Set("status", *p.Status)
	}
	if p.Day != nil {
		v.Set("day", strconv.Itoa(*p.Day))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBGamesPage is one page of mlb.games results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBGamesPage struct {
	Rows       []MLBGame `json:"games"`
	Limit      int       `json:"limit"`
	NextFromID *int64    `json:"next_from_id"`
	Quota      Quota     `json:"-"`
}

// MLBGamesService accesses the mlb.games endpoints.
type MLBGamesService struct {
	client *Client
}

// List returns one page of mlb.games matching params
// (pass nil for no filters).
func (s *MLBGamesService) List(ctx context.Context, params *MLBGamesListParams) (*MLBGamesPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/games", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBGamesPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.games row by id.
func (s *MLBGamesService) Get(ctx context.Context, id int64) (*MLBGame, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/games/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBGame
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.games, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBGamesService) All(ctx context.Context, params *MLBGamesListParams) iter.Seq2[MLBGame, error] {
	return func(yield func(MLBGame, error) bool) {
		page := MLBGamesListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBGame
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
