// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.game_period_lines (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBGamePeriodLine is a row from mlb.game_period_lines.
type MLBGamePeriodLine struct {
	ID                int64    `json:"id"`
	GameID            int64    `json:"game_id"`
	OperatorID        int64    `json:"operator_id"`
	SeasonID          int64    `json:"season_id"`
	CapturedAt        string   `json:"captured_at"`
	ImpliedAwayWinPct *float64 `json:"implied_away_win_pct"`
	ImpliedHomeWinPct *float64 `json:"implied_home_win_pct"`
	IsOpening         bool     `json:"is_opening"`
	MoneylineAway     *int     `json:"moneyline_away"`
	MoneylineHome     *int     `json:"moneyline_home"`
	OverOdds          *int     `json:"over_odds"`
	PeriodCode        string   `json:"period_code"`
	Spread            *float64 `json:"spread"`
	SpreadAwayOdds    *int     `json:"spread_away_odds"`
	SpreadHomeOdds    *int     `json:"spread_home_odds"`
	Total             *float64 `json:"total"`
	UnderOdds         *int     `json:"under_odds"`
}

// MLBGamePeriodLinesListParams are the query parameters for listing mlb.game_period_lines.
type MLBGamePeriodLinesListParams struct {
	GameID *int64
	Limit  *int
	FromID *int64
}

func (p *MLBGamePeriodLinesListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBGamePeriodLinesPage is one page of mlb.game_period_lines results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBGamePeriodLinesPage struct {
	Rows       []MLBGamePeriodLine `json:"game_period_lines"`
	Limit      int                 `json:"limit"`
	NextFromID *int64              `json:"next_from_id"`
	Quota      Quota               `json:"-"`
}

// MLBGamePeriodLinesService accesses the mlb.game_period_lines endpoints.
type MLBGamePeriodLinesService struct {
	client *Client
}

// List returns one page of mlb.game_period_lines matching params
// (pass nil for no filters).
func (s *MLBGamePeriodLinesService) List(ctx context.Context, params *MLBGamePeriodLinesListParams) (*MLBGamePeriodLinesPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/game_period_lines", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBGamePeriodLinesPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.game_period_lines row by id.
func (s *MLBGamePeriodLinesService) Get(ctx context.Context, id int64) (*MLBGamePeriodLine, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/game_period_lines/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBGamePeriodLine
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.game_period_lines, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBGamePeriodLinesService) All(ctx context.Context, params *MLBGamePeriodLinesListParams) iter.Seq2[MLBGamePeriodLine, error] {
	return func(yield func(MLBGamePeriodLine, error) bool) {
		page := MLBGamePeriodLinesListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBGamePeriodLine
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
