// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.team_starting_lineup_batters (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBTeamStartingLineupBatter is a row from mlb.team_starting_lineup_batters.
type MLBTeamStartingLineupBatter struct {
	ID                   int64  `json:"id"`
	PlayerID             int64  `json:"player_id"`
	TeamStartingLineupID int64  `json:"team_starting_lineup_id"`
	BattingOrder         string `json:"batting_order"`
	Position             string `json:"position"`
}

// MLBTeamStartingLineupBattersListParams are the query parameters for listing mlb.team_starting_lineup_batters.
type MLBTeamStartingLineupBattersListParams struct {
	TeamStartingLineupID *int64
	Limit                *int
	FromID               *int64
}

func (p *MLBTeamStartingLineupBattersListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.TeamStartingLineupID != nil {
		v.Set("team_starting_lineup_id", strconv.FormatInt(*p.TeamStartingLineupID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBTeamStartingLineupBattersPage is one page of mlb.team_starting_lineup_batters results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBTeamStartingLineupBattersPage struct {
	Rows       []MLBTeamStartingLineupBatter `json:"team_starting_lineup_batters"`
	Limit      int                           `json:"limit"`
	NextFromID *int64                        `json:"next_from_id"`
	Quota      Quota                         `json:"-"`
}

// MLBTeamStartingLineupBattersService accesses the mlb.team_starting_lineup_batters endpoints.
type MLBTeamStartingLineupBattersService struct {
	client *Client
}

// List returns one page of mlb.team_starting_lineup_batters matching params
// (pass nil for no filters).
func (s *MLBTeamStartingLineupBattersService) List(ctx context.Context, params *MLBTeamStartingLineupBattersListParams) (*MLBTeamStartingLineupBattersPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/team_starting_lineup_batters", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBTeamStartingLineupBattersPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.team_starting_lineup_batters row by id.
func (s *MLBTeamStartingLineupBattersService) Get(ctx context.Context, id int64) (*MLBTeamStartingLineupBatter, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/team_starting_lineup_batters/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBTeamStartingLineupBatter
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.team_starting_lineup_batters, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBTeamStartingLineupBattersService) All(ctx context.Context, params *MLBTeamStartingLineupBattersListParams) iter.Seq2[MLBTeamStartingLineupBatter, error] {
	return func(yield func(MLBTeamStartingLineupBatter, error) bool) {
		page := MLBTeamStartingLineupBattersListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBTeamStartingLineupBatter
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
