// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.play_by_plays (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBPlayByPlay is a row from mlb.play_by_plays.
type MLBPlayByPlay struct {
	ID                 int64   `json:"id"`
	AtBatID            *int64  `json:"at_bat_id"`
	BatterID           *int64  `json:"batter_id"`
	CatcherID          *int64  `json:"catcher_id"`
	FirstBaseRunnerID  *int64  `json:"first_base_runner_id"`
	GameID             int64   `json:"game_id"`
	InningID           int64   `json:"inning_id"`
	PitcherID          *int64  `json:"pitcher_id"`
	PlayID             int64   `json:"play_id"`
	PlayerID           *int64  `json:"player_id"`
	SecondBaseRunnerID *int64  `json:"second_base_runner_id"`
	TeamID             int64   `json:"team_id"`
	ThirdBaseRunnerID  *int64  `json:"third_base_runner_id"`
	CountBalls         int     `json:"count_balls"`
	CountStrikes       int     `json:"count_strikes"`
	EventSubType       int     `json:"event_sub_type"`
	EventType          int     `json:"event_type"`
	HitLocation        *string `json:"hit_location"`
	HitType            *string `json:"hit_type"`
	MlbEventNum        int     `json:"mlb_event_num"`
	Outs               int     `json:"outs"`
	RunnersOnBase      int     `json:"runners_on_base"`
}

// MLBPlayByPlaysListParams are the query parameters for listing mlb.play_by_plays.
type MLBPlayByPlaysListParams struct {
	GameID *int64
	Limit  *int
	FromID *int64
}

func (p *MLBPlayByPlaysListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBPlayByPlaysPage is one page of mlb.play_by_plays results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBPlayByPlaysPage struct {
	Rows       []MLBPlayByPlay `json:"play_by_plays"`
	Limit      int             `json:"limit"`
	NextFromID *int64          `json:"next_from_id"`
	Quota      Quota           `json:"-"`
}

// MLBPlayByPlaysService accesses the mlb.play_by_plays endpoints.
type MLBPlayByPlaysService struct {
	client *Client
}

// List returns one page of mlb.play_by_plays matching params
// (pass nil for no filters).
func (s *MLBPlayByPlaysService) List(ctx context.Context, params *MLBPlayByPlaysListParams) (*MLBPlayByPlaysPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/play_by_plays", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBPlayByPlaysPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.play_by_plays row by id.
func (s *MLBPlayByPlaysService) Get(ctx context.Context, id int64) (*MLBPlayByPlay, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/play_by_plays/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBPlayByPlay
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.play_by_plays, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBPlayByPlaysService) All(ctx context.Context, params *MLBPlayByPlaysListParams) iter.Seq2[MLBPlayByPlay, error] {
	return func(yield func(MLBPlayByPlay, error) bool) {
		page := MLBPlayByPlaysListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBPlayByPlay
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
