// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for mlb.game_umpires (public API).
// Source: schema/api/groups/public.yml + schema/model/mlb/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// MLBGameUmpire is a row from mlb.game_umpires.
type MLBGameUmpire struct {
	ID       int64   `json:"id"`
	GameID   int64   `json:"game_id"`
	UmpireID int64   `json:"umpire_id"`
	Position *string `json:"position"`
}

// MLBGameUmpiresListParams are the query parameters for listing mlb.game_umpires.
type MLBGameUmpiresListParams struct {
	GameID *int64
	Limit  *int
	FromID *int64
}

func (p *MLBGameUmpiresListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// MLBGameUmpiresPage is one page of mlb.game_umpires results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type MLBGameUmpiresPage struct {
	Rows       []MLBGameUmpire `json:"game_umpires"`
	Limit      int             `json:"limit"`
	NextFromID *int64          `json:"next_from_id"`
	Quota      Quota           `json:"-"`
}

// MLBGameUmpiresService accesses the mlb.game_umpires endpoints.
type MLBGameUmpiresService struct {
	client *Client
}

// List returns one page of mlb.game_umpires matching params
// (pass nil for no filters).
func (s *MLBGameUmpiresService) List(ctx context.Context, params *MLBGameUmpiresListParams) (*MLBGameUmpiresPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/mlb/game_umpires", params.values())
	if err != nil {
		return nil, err
	}
	var page MLBGameUmpiresPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single mlb.game_umpires row by id.
func (s *MLBGameUmpiresService) Get(ctx context.Context, id int64) (*MLBGameUmpire, error) {
	body, _, err := s.client.get(ctx, "/api/v1/mlb/game_umpires/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row MLBGameUmpire
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates mlb.game_umpires, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *MLBGameUmpiresService) All(ctx context.Context, params *MLBGameUmpiresListParams) iter.Seq2[MLBGameUmpire, error] {
	return func(yield func(MLBGameUmpire, error) bool) {
		page := MLBGameUmpiresListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero MLBGameUmpire
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
