// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nba.game_possessions (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NBAGamePossession is a row from nba.game_possessions.
type NBAGamePossession struct {
	ID                 int64   `json:"id"`
	GameID             int64   `json:"game_id"`
	TeamID             *int64  `json:"team_id"`
	Ast                int     `json:"ast"`
	AwayScore          int     `json:"away_score"`
	Blk                int     `json:"blk"`
	CumAwayPoss        int     `json:"cum_away_poss"`
	CumHomePoss        int     `json:"cum_home_poss"`
	Dreb               int     `json:"dreb"`
	EndClock           *int    `json:"end_clock"`
	EndNbaEventNum     int     `json:"end_nba_event_num"`
	Fg3a               int     `json:"fg3a"`
	Fg3m               int     `json:"fg3m"`
	Fga                int     `json:"fga"`
	Fgm                int     `json:"fgm"`
	Fta                int     `json:"fta"`
	Ftm                int     `json:"ftm"`
	GameSecondsElapsed int     `json:"game_seconds_elapsed"`
	HomeScore          int     `json:"home_score"`
	Oreb               int     `json:"oreb"`
	Period             int     `json:"period"`
	Pf                 int     `json:"pf"`
	Pts                int     `json:"pts"`
	StartClock         int     `json:"start_clock"`
	StartNbaEventNum   int     `json:"start_nba_event_num"`
	Stl                int     `json:"stl"`
	TimeActualEnd      *string `json:"time_actual_end"`
	TimeActualStart    *string `json:"time_actual_start"`
	Tov                int     `json:"tov"`
}

// NBAGamePossessionsListParams are the query parameters for listing nba.game_possessions.
type NBAGamePossessionsListParams struct {
	GameID *int64
	TeamID *int64
	Limit  *int
	FromID *int64
}

func (p *NBAGamePossessionsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.TeamID != nil {
		v.Set("team_id", strconv.FormatInt(*p.TeamID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NBAGamePossessionsPage is one page of nba.game_possessions results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NBAGamePossessionsPage struct {
	Rows       []NBAGamePossession `json:"game_possessions"`
	Limit      int                 `json:"limit"`
	NextFromID *int64              `json:"next_from_id"`
	Quota      Quota               `json:"-"`
}

// NBAGamePossessionsService accesses the nba.game_possessions endpoints.
type NBAGamePossessionsService struct {
	client *Client
}

// List returns one page of nba.game_possessions matching params
// (pass nil for no filters).
func (s *NBAGamePossessionsService) List(ctx context.Context, params *NBAGamePossessionsListParams) (*NBAGamePossessionsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nba/game_possessions", params.values())
	if err != nil {
		return nil, err
	}
	var page NBAGamePossessionsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nba.game_possessions row by id.
func (s *NBAGamePossessionsService) Get(ctx context.Context, id int64) (*NBAGamePossession, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nba/game_possessions/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NBAGamePossession
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nba.game_possessions, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NBAGamePossessionsService) All(ctx context.Context, params *NBAGamePossessionsListParams) iter.Seq2[NBAGamePossession, error] {
	return func(yield func(NBAGamePossession, error) bool) {
		page := NBAGamePossessionsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NBAGamePossession
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
