// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nba.stadiums (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NBAStadium is a row from nba.stadiums.
type NBAStadium struct {
	ID              int64    `json:"id"`
	LeagueStadiumID *int     `json:"league_stadium_id"`
	Address         *string  `json:"address"`
	Capacity        *int     `json:"capacity"`
	City            string   `json:"city"`
	ClosedDate      *string  `json:"closed_date"`
	Country         *string  `json:"country"`
	Description     *string  `json:"description"`
	Elevation       *float64 `json:"elevation"`
	ImageURL        *string  `json:"image_url"`
	Latitude        *float64 `json:"latitude"`
	Longitude       *float64 `json:"longitude"`
	Name            string   `json:"name"`
	OpenedDate      *string  `json:"opened_date"`
	RoofType        *string  `json:"roof_type"`
	State           *string  `json:"state"`
	Surface         *string  `json:"surface"`
	TeamName        *string  `json:"team_name"`
	Timezone        *string  `json:"timezone"`
}

// NBAStadiumsListParams are the query parameters for listing nba.stadiums.
type NBAStadiumsListParams struct {
	Limit  *int
	FromID *int64
}

func (p *NBAStadiumsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NBAStadiumsPage is one page of nba.stadiums results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NBAStadiumsPage struct {
	Rows       []NBAStadium `json:"stadiums"`
	Limit      int          `json:"limit"`
	NextFromID *int64       `json:"next_from_id"`
	Quota      Quota        `json:"-"`
}

// NBAStadiumsService accesses the nba.stadiums endpoints.
type NBAStadiumsService struct {
	client *Client
}

// List returns one page of nba.stadiums matching params
// (pass nil for no filters).
func (s *NBAStadiumsService) List(ctx context.Context, params *NBAStadiumsListParams) (*NBAStadiumsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nba/stadiums", params.values())
	if err != nil {
		return nil, err
	}
	var page NBAStadiumsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nba.stadiums row by id.
func (s *NBAStadiumsService) Get(ctx context.Context, id int64) (*NBAStadium, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nba/stadiums/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NBAStadium
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nba.stadiums, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NBAStadiumsService) All(ctx context.Context, params *NBAStadiumsListParams) iter.Seq2[NBAStadium, error] {
	return func(yield func(NBAStadium, error) bool) {
		page := NBAStadiumsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NBAStadium
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
