// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nba.games (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NBAGame is a row from nba.games.
type NBAGame struct {
	ID                 int64   `json:"id"`
	AwayTeamID         int64   `json:"away_team_id"`
	HomeTeamID         int64   `json:"home_team_id"`
	LeagueGameID       *string `json:"league_game_id"`
	SeasonID           int64   `json:"season_id"`
	StadiumID          *int    `json:"stadium_id"`
	Attendance         *int    `json:"attendance"`
	AwayRotationNumber *int    `json:"away_rotation_number"`
	AwayTeam           string  `json:"away_team"`
	AwayTeamScore      int     `json:"away_team_score"`
	Channel            *string `json:"channel"`
	Day                int     `json:"day"`
	EndTime            *string `json:"end_time"`
	GameLabel          *string `json:"game_label"`
	GameSubLabel       *string `json:"game_sub_label"`
	GameTime           string  `json:"game_time"`
	HomeRotationNumber *int    `json:"home_rotation_number"`
	HomeTeam           string  `json:"home_team"`
	HomeTeamScore      int     `json:"home_team_score"`
	IfNecessary        *bool   `json:"if_necessary"`
	NeutralVenue       bool    `json:"neutral_venue"`
	PostponedStatus    *string `json:"postponed_status"`
	SeasonType         string  `json:"season_type"`
	SeriesGameNumber   *string `json:"series_game_number"`
	SeriesName         *string `json:"series_name"`
	SeriesText         *string `json:"series_text"`
	StartTime          string  `json:"start_time"`
	Status             string  `json:"status"`
}

// NBAGamesListParams are the query parameters for listing nba.games.
type NBAGamesListParams struct {
	SeasonID   *int64
	HomeTeamID *int64
	AwayTeamID *int64
	Status     *string
	Day        *int
	SeasonType *string
	Limit      *int
	FromID     *int64
}

func (p *NBAGamesListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.SeasonID != nil {
		v.Set("season_id", strconv.FormatInt(*p.SeasonID, 10))
	}
	if p.HomeTeamID != nil {
		v.Set("home_team_id", strconv.FormatInt(*p.HomeTeamID, 10))
	}
	if p.AwayTeamID != nil {
		v.Set("away_team_id", strconv.FormatInt(*p.AwayTeamID, 10))
	}
	if p.Status != nil {
		v.Set("status", *p.Status)
	}
	if p.Day != nil {
		v.Set("day", strconv.Itoa(*p.Day))
	}
	if p.SeasonType != nil {
		v.Set("season_type", *p.SeasonType)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NBAGamesPage is one page of nba.games results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NBAGamesPage struct {
	Rows       []NBAGame `json:"games"`
	Limit      int       `json:"limit"`
	NextFromID *int64    `json:"next_from_id"`
	Quota      Quota     `json:"-"`
}

// NBAGamesService accesses the nba.games endpoints.
type NBAGamesService struct {
	client *Client
}

// List returns one page of nba.games matching params
// (pass nil for no filters).
func (s *NBAGamesService) List(ctx context.Context, params *NBAGamesListParams) (*NBAGamesPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nba/games", params.values())
	if err != nil {
		return nil, err
	}
	var page NBAGamesPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nba.games row by id.
func (s *NBAGamesService) Get(ctx context.Context, id int64) (*NBAGame, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nba/games/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NBAGame
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nba.games, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NBAGamesService) All(ctx context.Context, params *NBAGamesListParams) iter.Seq2[NBAGame, error] {
	return func(yield func(NBAGame, error) bool) {
		page := NBAGamesListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NBAGame
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
