// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nba.season_player_stats (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NBASeasonPlayerStat is a row from nba.season_player_stats.
type NBASeasonPlayerStat struct {
	ID                           int64   `json:"id"`
	PlayerID                     int64   `json:"player_id"`
	SeasonID                     int64   `json:"season_id"`
	AssistPercentage             float64 `json:"assist_percentage"`
	AssistRatio                  float64 `json:"assist_ratio"`
	AssistToTurnover             float64 `json:"assist_to_turnover"`
	Assists                      int     `json:"assists"`
	AvgDribblesPerTouch          float64 `json:"avg_dribbles_per_touch"`
	AvgSecondsPerTouch           float64 `json:"avg_seconds_per_touch"`
	Blocks                       int     `json:"blocks"`
	DefensiveRating              float64 `json:"defensive_rating"`
	DefensiveReboundPercentage   float64 `json:"defensive_rebound_percentage"`
	DefensiveRebounds            int     `json:"defensive_rebounds"`
	DoubleDoubles                int     `json:"double_doubles"`
	EffectiveFieldGoalPercentage float64 `json:"effective_field_goal_percentage"`
	FieldGoalPercentage          float64 `json:"field_goal_percentage"`
	FieldGoalsAttempted          int     `json:"field_goals_attempted"`
	FieldGoalsMade               int     `json:"field_goals_made"`
	Fouls                        int     `json:"fouls"`
	FreeThrowPercentage          float64 `json:"free_throw_percentage"`
	FreeThrowsAttempted          int     `json:"free_throws_attempted"`
	FreeThrowsMade               int     `json:"free_throws_made"`
	FrontCourtTouches            int     `json:"front_court_touches"`
	GamesPlayed                  int     `json:"games_played"`
	Losses                       int     `json:"losses"`
	Minutes                      float64 `json:"minutes"`
	NetRating                    float64 `json:"net_rating"`
	OffensiveRating              float64 `json:"offensive_rating"`
	OffensiveReboundPercentage   float64 `json:"offensive_rebound_percentage"`
	OffensiveRebounds            int     `json:"offensive_rebounds"`
	Pace                         float64 `json:"pace"`
	PlayerImpactEstimate         float64 `json:"player_impact_estimate"`
	PlusMinus                    int     `json:"plus_minus"`
	Possessions                  int     `json:"possessions"`
	Pts                          int     `json:"pts"`
	ReboundPercentage            float64 `json:"rebound_percentage"`
	Rebounds                     int     `json:"rebounds"`
	Steals                       int     `json:"steals"`
	ThreePointPercentage         float64 `json:"three_point_percentage"`
	ThreePointersAttempted       int     `json:"three_pointers_attempted"`
	ThreePointersMade            int     `json:"three_pointers_made"`
	TimeOfPossession             float64 `json:"time_of_possession"`
	Touches                      int     `json:"touches"`
	TripleDoubles                int     `json:"triple_doubles"`
	TrueShootingPercentage       float64 `json:"true_shooting_percentage"`
	TurnoverPercentage           float64 `json:"turnover_percentage"`
	Turnovers                    int     `json:"turnovers"`
	UsagePercentage              float64 `json:"usage_percentage"`
	Wins                         int     `json:"wins"`
}

// NBASeasonPlayerStatsListParams are the query parameters for listing nba.season_player_stats.
type NBASeasonPlayerStatsListParams struct {
	SeasonID *int64
	PlayerID *int64
	Limit    *int
	FromID   *int64
}

func (p *NBASeasonPlayerStatsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.SeasonID != nil {
		v.Set("season_id", strconv.FormatInt(*p.SeasonID, 10))
	}
	if p.PlayerID != nil {
		v.Set("player_id", strconv.FormatInt(*p.PlayerID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NBASeasonPlayerStatsPage is one page of nba.season_player_stats results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NBASeasonPlayerStatsPage struct {
	Rows       []NBASeasonPlayerStat `json:"season_player_stats"`
	Limit      int                   `json:"limit"`
	NextFromID *int64                `json:"next_from_id"`
	Quota      Quota                 `json:"-"`
}

// NBASeasonPlayerStatsService accesses the nba.season_player_stats endpoints.
type NBASeasonPlayerStatsService struct {
	client *Client
}

// List returns one page of nba.season_player_stats matching params
// (pass nil for no filters).
func (s *NBASeasonPlayerStatsService) List(ctx context.Context, params *NBASeasonPlayerStatsListParams) (*NBASeasonPlayerStatsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nba/season_player_stats", params.values())
	if err != nil {
		return nil, err
	}
	var page NBASeasonPlayerStatsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nba.season_player_stats row by id.
func (s *NBASeasonPlayerStatsService) Get(ctx context.Context, id int64) (*NBASeasonPlayerStat, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nba/season_player_stats/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NBASeasonPlayerStat
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nba.season_player_stats, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NBASeasonPlayerStatsService) All(ctx context.Context, params *NBASeasonPlayerStatsListParams) iter.Seq2[NBASeasonPlayerStat, error] {
	return func(yield func(NBASeasonPlayerStat, error) bool) {
		page := NBASeasonPlayerStatsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NBASeasonPlayerStat
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
