// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nba.operator_team_lookups (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NBAOperatorTeamLookup is a row from nba.operator_team_lookups.
type NBAOperatorTeamLookup struct {
	ID             int64   `json:"id"`
	OperatorID     int64   `json:"operator_id"`
	OperatorTeamID string  `json:"operator_team_id"`
	TeamID         int64   `json:"team_id"`
	Abbreviation   *string `json:"abbreviation"`
	TeamName       *string `json:"team_name"`
}

// NBAOperatorTeamLookupsListParams are the query parameters for listing nba.operator_team_lookups.
type NBAOperatorTeamLookupsListParams struct {
	OperatorID *int64
	TeamID     *int64
	Limit      *int
	FromID     *int64
}

func (p *NBAOperatorTeamLookupsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.OperatorID != nil {
		v.Set("operator_id", strconv.FormatInt(*p.OperatorID, 10))
	}
	if p.TeamID != nil {
		v.Set("team_id", strconv.FormatInt(*p.TeamID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NBAOperatorTeamLookupsPage is one page of nba.operator_team_lookups results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NBAOperatorTeamLookupsPage struct {
	Rows       []NBAOperatorTeamLookup `json:"operator_team_lookups"`
	Limit      int                     `json:"limit"`
	NextFromID *int64                  `json:"next_from_id"`
	Quota      Quota                   `json:"-"`
}

// NBAOperatorTeamLookupsService accesses the nba.operator_team_lookups endpoints.
type NBAOperatorTeamLookupsService struct {
	client *Client
}

// List returns one page of nba.operator_team_lookups matching params
// (pass nil for no filters).
func (s *NBAOperatorTeamLookupsService) List(ctx context.Context, params *NBAOperatorTeamLookupsListParams) (*NBAOperatorTeamLookupsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nba/operator_team_lookups", params.values())
	if err != nil {
		return nil, err
	}
	var page NBAOperatorTeamLookupsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nba.operator_team_lookups row by id.
func (s *NBAOperatorTeamLookupsService) Get(ctx context.Context, id int64) (*NBAOperatorTeamLookup, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nba/operator_team_lookups/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NBAOperatorTeamLookup
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nba.operator_team_lookups, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NBAOperatorTeamLookupsService) All(ctx context.Context, params *NBAOperatorTeamLookupsListParams) iter.Seq2[NBAOperatorTeamLookup, error] {
	return func(yield func(NBAOperatorTeamLookup, error) bool) {
		page := NBAOperatorTeamLookupsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NBAOperatorTeamLookup
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
