// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nba.game_referees (public API).
// Source: schema/api/groups/public.yml + schema/model/nba/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NBAGameReferee is a row from nba.game_referees.
type NBAGameReferee struct {
	ID        int64   `json:"id"`
	GameID    int64   `json:"game_id"`
	RefereeID int64   `json:"referee_id"`
	Position  *string `json:"position"`
}

// NBAGameRefereesListParams are the query parameters for listing nba.game_referees.
type NBAGameRefereesListParams struct {
	GameID    *int64
	RefereeID *int64
	Limit     *int
	FromID    *int64
}

func (p *NBAGameRefereesListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.RefereeID != nil {
		v.Set("referee_id", strconv.FormatInt(*p.RefereeID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NBAGameRefereesPage is one page of nba.game_referees results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NBAGameRefereesPage struct {
	Rows       []NBAGameReferee `json:"game_referees"`
	Limit      int              `json:"limit"`
	NextFromID *int64           `json:"next_from_id"`
	Quota      Quota            `json:"-"`
}

// NBAGameRefereesService accesses the nba.game_referees endpoints.
type NBAGameRefereesService struct {
	client *Client
}

// List returns one page of nba.game_referees matching params
// (pass nil for no filters).
func (s *NBAGameRefereesService) List(ctx context.Context, params *NBAGameRefereesListParams) (*NBAGameRefereesPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nba/game_referees", params.values())
	if err != nil {
		return nil, err
	}
	var page NBAGameRefereesPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nba.game_referees row by id.
func (s *NBAGameRefereesService) Get(ctx context.Context, id int64) (*NBAGameReferee, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nba/game_referees/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NBAGameReferee
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nba.game_referees, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NBAGameRefereesService) All(ctx context.Context, params *NBAGameRefereesListParams) iter.Seq2[NBAGameReferee, error] {
	return func(yield func(NBAGameReferee, error) bool) {
		page := NBAGameRefereesListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NBAGameReferee
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
