// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nfl.referees (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NFLReferee is a row from nfl.referees.
type NFLReferee struct {
	ID           int64  `json:"id"`
	NflRefereeID int    `json:"nfl_referee_id"`
	Active       bool   `json:"active"`
	Experience   *int   `json:"experience"`
	FirstName    string `json:"first_name"`
	FullName     string `json:"full_name"`
	LastName     string `json:"last_name"`
	Position     string `json:"position"`
}

// NFLRefereesListParams are the query parameters for listing nfl.referees.
type NFLRefereesListParams struct {
	Active *bool
	Limit  *int
	FromID *int64
}

func (p *NFLRefereesListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Active != nil {
		v.Set("active", strconv.FormatBool(*p.Active))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NFLRefereesPage is one page of nfl.referees results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NFLRefereesPage struct {
	Rows       []NFLReferee `json:"referees"`
	Limit      int          `json:"limit"`
	NextFromID *int64       `json:"next_from_id"`
	Quota      Quota        `json:"-"`
}

// NFLRefereesService accesses the nfl.referees endpoints.
type NFLRefereesService struct {
	client *Client
}

// List returns one page of nfl.referees matching params
// (pass nil for no filters).
func (s *NFLRefereesService) List(ctx context.Context, params *NFLRefereesListParams) (*NFLRefereesPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nfl/referees", params.values())
	if err != nil {
		return nil, err
	}
	var page NFLRefereesPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nfl.referees row by id.
func (s *NFLRefereesService) Get(ctx context.Context, id int64) (*NFLReferee, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nfl/referees/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NFLReferee
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nfl.referees, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NFLRefereesService) All(ctx context.Context, params *NFLRefereesListParams) iter.Seq2[NFLReferee, error] {
	return func(yield func(NFLReferee, error) bool) {
		page := NFLRefereesListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NFLReferee
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
