// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nfl.depth_charts (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NFLDepthChart is a row from nfl.depth_charts.
type NFLDepthChart struct {
	ID            int64   `json:"id"`
	EliasID       *string `json:"elias_id"`
	GameID        int64   `json:"game_id"`
	PlayerID      int64   `json:"player_id"`
	SeasonID      int64   `json:"season_id"`
	TeamID        int64   `json:"team_id"`
	DepthOrder    *int    `json:"depth_order"`
	DepthPosition string  `json:"depth_position"`
	DepthTeam     *string `json:"depth_team"`
	Formation     *string `json:"formation"`
	GameType      string  `json:"game_type"`
	JerseyNumber  *int    `json:"jersey_number"`
	Position      string  `json:"position"`
	Status        *string `json:"status"`
	Week          int     `json:"week"`
}

// NFLDepthChartsListParams are the query parameters for listing nfl.depth_charts.
type NFLDepthChartsListParams struct {
	GameID   *int64
	TeamID   *int64
	SeasonID *int64
	Week     *int
	PlayerID *int64
	Position *string
	Limit    *int
	FromID   *int64
}

func (p *NFLDepthChartsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.TeamID != nil {
		v.Set("team_id", strconv.FormatInt(*p.TeamID, 10))
	}
	if p.SeasonID != nil {
		v.Set("season_id", strconv.FormatInt(*p.SeasonID, 10))
	}
	if p.Week != nil {
		v.Set("week", strconv.Itoa(*p.Week))
	}
	if p.PlayerID != nil {
		v.Set("player_id", strconv.FormatInt(*p.PlayerID, 10))
	}
	if p.Position != nil {
		v.Set("position", *p.Position)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NFLDepthChartsPage is one page of nfl.depth_charts results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NFLDepthChartsPage struct {
	Rows       []NFLDepthChart `json:"depth_charts"`
	Limit      int             `json:"limit"`
	NextFromID *int64          `json:"next_from_id"`
	Quota      Quota           `json:"-"`
}

// NFLDepthChartsService accesses the nfl.depth_charts endpoints.
type NFLDepthChartsService struct {
	client *Client
}

// List returns one page of nfl.depth_charts matching params
// (pass nil for no filters).
func (s *NFLDepthChartsService) List(ctx context.Context, params *NFLDepthChartsListParams) (*NFLDepthChartsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nfl/depth_charts", params.values())
	if err != nil {
		return nil, err
	}
	var page NFLDepthChartsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nfl.depth_charts row by id.
func (s *NFLDepthChartsService) Get(ctx context.Context, id int64) (*NFLDepthChart, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nfl/depth_charts/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NFLDepthChart
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nfl.depth_charts, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NFLDepthChartsService) All(ctx context.Context, params *NFLDepthChartsListParams) iter.Seq2[NFLDepthChart, error] {
	return func(yield func(NFLDepthChart, error) bool) {
		page := NFLDepthChartsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NFLDepthChart
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
