// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nfl.game_player_pfr_advstats (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NFLGamePlayerPfrAdvstat is a row from nfl.game_player_pfr_advstats.
type NFLGamePlayerPfrAdvstat struct {
	ID                         int64    `json:"id"`
	GameID                     int64    `json:"game_id"`
	OpponentTeamID             int64    `json:"opponent_team_id"`
	PlayerID                   int64    `json:"player_id"`
	TeamID                     int64    `json:"team_id"`
	Carries                    *int     `json:"carries"`
	DefAdot                    *float64 `json:"def_adot"`
	DefAirYdsCompleted         *int     `json:"def_air_yds_completed"`
	DefCompletionPct           *float64 `json:"def_completion_pct"`
	DefCompletionsAllowed      *int     `json:"def_completions_allowed"`
	DefInts                    *int     `json:"def_ints"`
	DefMissedTacklePct         *float64 `json:"def_missed_tackle_pct"`
	DefMissedTackles           *int     `json:"def_missed_tackles"`
	DefPasserRatingAllowed     *float64 `json:"def_passer_rating_allowed"`
	DefPressures               *int     `json:"def_pressures"`
	DefReceivingTdAllowed      *int     `json:"def_receiving_td_allowed"`
	DefSacks                   *float64 `json:"def_sacks"`
	DefTacklesCombined         *int     `json:"def_tackles_combined"`
	DefTargets                 *int     `json:"def_targets"`
	DefTimesBlitzed            *int     `json:"def_times_blitzed"`
	DefTimesHitqb              *int     `json:"def_times_hitqb"`
	DefTimesHurried            *int     `json:"def_times_hurried"`
	DefYdsAfterCatch           *int     `json:"def_yds_after_catch"`
	DefYdsAllowed              *int     `json:"def_yds_allowed"`
	DefYdsAllowedPerCmp        *float64 `json:"def_yds_allowed_per_cmp"`
	DefYdsAllowedPerTgt        *float64 `json:"def_yds_allowed_per_tgt"`
	PassingBadThrowPct         *float64 `json:"passing_bad_throw_pct"`
	PassingBadThrows           *int     `json:"passing_bad_throws"`
	PassingDropPct             *float64 `json:"passing_drop_pct"`
	PassingDrops               *int     `json:"passing_drops"`
	ReceivingBrokenTackles     *int     `json:"receiving_broken_tackles"`
	ReceivingDrop              *int     `json:"receiving_drop"`
	ReceivingDropPct           *float64 `json:"receiving_drop_pct"`
	ReceivingInt               *int     `json:"receiving_int"`
	ReceivingRat               *float64 `json:"receiving_rat"`
	RushingBrokenTackles       *int     `json:"rushing_broken_tackles"`
	RushingYdsAfterContact     *int     `json:"rushing_yds_after_contact"`
	RushingYdsAfterContactAvg  *float64 `json:"rushing_yds_after_contact_avg"`
	RushingYdsBeforeContact    *int     `json:"rushing_yds_before_contact"`
	RushingYdsBeforeContactAvg *float64 `json:"rushing_yds_before_contact_avg"`
	TimesBlitzed               *int     `json:"times_blitzed"`
	TimesHit                   *int     `json:"times_hit"`
	TimesHurried               *int     `json:"times_hurried"`
	TimesPressured             *int     `json:"times_pressured"`
	TimesPressuredPct          *float64 `json:"times_pressured_pct"`
	TimesSacked                *int     `json:"times_sacked"`
}

// NFLGamePlayerPfrAdvstatsListParams are the query parameters for listing nfl.game_player_pfr_advstats.
type NFLGamePlayerPfrAdvstatsListParams struct {
	GameID         *int64
	PlayerID       *int64
	TeamID         *int64
	OpponentTeamID *int64
	Limit          *int
	FromID         *int64
}

func (p *NFLGamePlayerPfrAdvstatsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.PlayerID != nil {
		v.Set("player_id", strconv.FormatInt(*p.PlayerID, 10))
	}
	if p.TeamID != nil {
		v.Set("team_id", strconv.FormatInt(*p.TeamID, 10))
	}
	if p.OpponentTeamID != nil {
		v.Set("opponent_team_id", strconv.FormatInt(*p.OpponentTeamID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NFLGamePlayerPfrAdvstatsPage is one page of nfl.game_player_pfr_advstats results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NFLGamePlayerPfrAdvstatsPage struct {
	Rows       []NFLGamePlayerPfrAdvstat `json:"game_player_pfr_advstats"`
	Limit      int                       `json:"limit"`
	NextFromID *int64                    `json:"next_from_id"`
	Quota      Quota                     `json:"-"`
}

// NFLGamePlayerPfrAdvstatsService accesses the nfl.game_player_pfr_advstats endpoints.
type NFLGamePlayerPfrAdvstatsService struct {
	client *Client
}

// List returns one page of nfl.game_player_pfr_advstats matching params
// (pass nil for no filters).
func (s *NFLGamePlayerPfrAdvstatsService) List(ctx context.Context, params *NFLGamePlayerPfrAdvstatsListParams) (*NFLGamePlayerPfrAdvstatsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nfl/game_player_pfr_advstats", params.values())
	if err != nil {
		return nil, err
	}
	var page NFLGamePlayerPfrAdvstatsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nfl.game_player_pfr_advstats row by id.
func (s *NFLGamePlayerPfrAdvstatsService) Get(ctx context.Context, id int64) (*NFLGamePlayerPfrAdvstat, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nfl/game_player_pfr_advstats/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NFLGamePlayerPfrAdvstat
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nfl.game_player_pfr_advstats, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NFLGamePlayerPfrAdvstatsService) All(ctx context.Context, params *NFLGamePlayerPfrAdvstatsListParams) iter.Seq2[NFLGamePlayerPfrAdvstat, error] {
	return func(yield func(NFLGamePlayerPfrAdvstat, error) bool) {
		page := NFLGamePlayerPfrAdvstatsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NFLGamePlayerPfrAdvstat
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
