// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nfl.game_player_ngs_rushings (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NFLGamePlayerNgsRushing is a row from nfl.game_player_ngs_rushings.
type NFLGamePlayerNgsRushing struct {
	ID                               int64    `json:"id"`
	GameID                           int64    `json:"game_id"`
	PlayerGsisID                     string   `json:"player_gsis_id"`
	PlayerID                         int64    `json:"player_id"`
	TeamID                           int64    `json:"team_id"`
	AvgRushYds                       *float64 `json:"avg_rush_yds"`
	AvgTimeToLos                     *float64 `json:"avg_time_to_los"`
	Efficiency                       *float64 `json:"efficiency"`
	ExpectedRushYds                  *float64 `json:"expected_rush_yds"`
	PercentAttemptsGteEightDefenders *float64 `json:"percent_attempts_gte_eight_defenders"`
	RushAttempts                     *int     `json:"rush_attempts"`
	RushPctOverExpected              *float64 `json:"rush_pct_over_expected"`
	RushTds                          *int     `json:"rush_tds"`
	RushYds                          *int     `json:"rush_yds"`
	RushYdsOverExpected              *float64 `json:"rush_yds_over_expected"`
	RushYdsOverExpectedPerAtt        *float64 `json:"rush_yds_over_expected_per_att"`
	Season                           int      `json:"season"`
	SeasonType                       string   `json:"season_type"`
	Week                             int      `json:"week"`
}

// NFLGamePlayerNgsRushingsListParams are the query parameters for listing nfl.game_player_ngs_rushings.
type NFLGamePlayerNgsRushingsListParams struct {
	GameID   *int64
	PlayerID *int64
	TeamID   *int64
	Season   *int
	Week     *int
	Limit    *int
	FromID   *int64
}

func (p *NFLGamePlayerNgsRushingsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.GameID != nil {
		v.Set("game_id", strconv.FormatInt(*p.GameID, 10))
	}
	if p.PlayerID != nil {
		v.Set("player_id", strconv.FormatInt(*p.PlayerID, 10))
	}
	if p.TeamID != nil {
		v.Set("team_id", strconv.FormatInt(*p.TeamID, 10))
	}
	if p.Season != nil {
		v.Set("season", strconv.Itoa(*p.Season))
	}
	if p.Week != nil {
		v.Set("week", strconv.Itoa(*p.Week))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NFLGamePlayerNgsRushingsPage is one page of nfl.game_player_ngs_rushings results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NFLGamePlayerNgsRushingsPage struct {
	Rows       []NFLGamePlayerNgsRushing `json:"game_player_ngs_rushings"`
	Limit      int                       `json:"limit"`
	NextFromID *int64                    `json:"next_from_id"`
	Quota      Quota                     `json:"-"`
}

// NFLGamePlayerNgsRushingsService accesses the nfl.game_player_ngs_rushings endpoints.
type NFLGamePlayerNgsRushingsService struct {
	client *Client
}

// List returns one page of nfl.game_player_ngs_rushings matching params
// (pass nil for no filters).
func (s *NFLGamePlayerNgsRushingsService) List(ctx context.Context, params *NFLGamePlayerNgsRushingsListParams) (*NFLGamePlayerNgsRushingsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nfl/game_player_ngs_rushings", params.values())
	if err != nil {
		return nil, err
	}
	var page NFLGamePlayerNgsRushingsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nfl.game_player_ngs_rushings row by id.
func (s *NFLGamePlayerNgsRushingsService) Get(ctx context.Context, id int64) (*NFLGamePlayerNgsRushing, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nfl/game_player_ngs_rushings/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NFLGamePlayerNgsRushing
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nfl.game_player_ngs_rushings, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NFLGamePlayerNgsRushingsService) All(ctx context.Context, params *NFLGamePlayerNgsRushingsListParams) iter.Seq2[NFLGamePlayerNgsRushing, error] {
	return func(yield func(NFLGamePlayerNgsRushing, error) bool) {
		page := NFLGamePlayerNgsRushingsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NFLGamePlayerNgsRushing
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
