// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nfl.season_player_thirddown_stats (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NFLSeasonPlayerThirddownStat is a row from nfl.season_player_thirddown_stats.
type NFLSeasonPlayerThirddownStat struct {
	ID                          int64   `json:"id"`
	PlayerID                    int64   `json:"player_id"`
	SeasonID                    int64   `json:"season_id"`
	AssistedTackles             int     `json:"assisted_tackles"`
	DefensiveTds                int     `json:"defensive_tds"`
	ForcedFumbles               int     `json:"forced_fumbles"`
	FumbleRecoveryTds           int     `json:"fumble_recovery_tds"`
	FumbleRecoveryYds           int     `json:"fumble_recovery_yds"`
	Fumbles                     int     `json:"fumbles"`
	FumblesLost                 int     `json:"fumbles_lost"`
	FumblesRecovered            int     `json:"fumbles_recovered"`
	GamesPlayed                 int     `json:"games_played"`
	GamesStarted                int     `json:"games_started"`
	InterceptionTds             int     `json:"interception_tds"`
	InterceptionYds             int     `json:"interception_yds"`
	Interceptions               int     `json:"interceptions"`
	OffensiveSnaps              int     `json:"offensive_snaps"`
	OffensiveTds                int     `json:"offensive_tds"`
	PassesDefended              int     `json:"passes_defended"`
	PassingAttempts             int     `json:"passing_attempts"`
	PassingCompletionPercentage float64 `json:"passing_completion_percentage"`
	PassingCompletions          int     `json:"passing_completions"`
	PassingInterceptions        int     `json:"passing_interceptions"`
	PassingLong                 int     `json:"passing_long"`
	PassingRating               float64 `json:"passing_rating"`
	PassingSackYds              int     `json:"passing_sack_yds"`
	PassingSacks                int     `json:"passing_sacks"`
	PassingTds                  int     `json:"passing_tds"`
	PassingYds                  int     `json:"passing_yds"`
	PassingYdsPerAttempt        float64 `json:"passing_yds_per_attempt"`
	PassingYdsPerCompletion     float64 `json:"passing_yds_per_completion"`
	QuarterbackHits             int     `json:"quarterback_hits"`
	ReceivingLong               int     `json:"receiving_long"`
	ReceivingTds                int     `json:"receiving_tds"`
	ReceivingYds                int     `json:"receiving_yds"`
	ReceivingYdsPerReception    float64 `json:"receiving_yds_per_reception"`
	ReceivingYdsPerTarget       float64 `json:"receiving_yds_per_target"`
	ReceptionPercentage         float64 `json:"reception_percentage"`
	Receptions                  int     `json:"receptions"`
	RushingAttempts             int     `json:"rushing_attempts"`
	RushingLong                 int     `json:"rushing_long"`
	RushingTds                  int     `json:"rushing_tds"`
	RushingYds                  int     `json:"rushing_yds"`
	RushingYdsPerAttempt        float64 `json:"rushing_yds_per_attempt"`
	Sacks                       float64 `json:"sacks"`
	SoloTackles                 int     `json:"solo_tackles"`
	TacklesForLoss              int     `json:"tackles_for_loss"`
	Targets                     int     `json:"targets"`
	TotalTds                    int     `json:"total_tds"`
	TwoPtPassConversions        int     `json:"two_pt_pass_conversions"`
	TwoPtReceptionConversions   int     `json:"two_pt_reception_conversions"`
	TwoPtRushConversions        int     `json:"two_pt_rush_conversions"`
}

// NFLSeasonPlayerThirddownStatsListParams are the query parameters for listing nfl.season_player_thirddown_stats.
type NFLSeasonPlayerThirddownStatsListParams struct {
	PlayerID *int64
	SeasonID *int64
	Limit    *int
	FromID   *int64
}

func (p *NFLSeasonPlayerThirddownStatsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.PlayerID != nil {
		v.Set("player_id", strconv.FormatInt(*p.PlayerID, 10))
	}
	if p.SeasonID != nil {
		v.Set("season_id", strconv.FormatInt(*p.SeasonID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NFLSeasonPlayerThirddownStatsPage is one page of nfl.season_player_thirddown_stats results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NFLSeasonPlayerThirddownStatsPage struct {
	Rows       []NFLSeasonPlayerThirddownStat `json:"season_player_thirddown_stats"`
	Limit      int                            `json:"limit"`
	NextFromID *int64                         `json:"next_from_id"`
	Quota      Quota                          `json:"-"`
}

// NFLSeasonPlayerThirddownStatsService accesses the nfl.season_player_thirddown_stats endpoints.
type NFLSeasonPlayerThirddownStatsService struct {
	client *Client
}

// List returns one page of nfl.season_player_thirddown_stats matching params
// (pass nil for no filters).
func (s *NFLSeasonPlayerThirddownStatsService) List(ctx context.Context, params *NFLSeasonPlayerThirddownStatsListParams) (*NFLSeasonPlayerThirddownStatsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nfl/season_player_thirddown_stats", params.values())
	if err != nil {
		return nil, err
	}
	var page NFLSeasonPlayerThirddownStatsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nfl.season_player_thirddown_stats row by id.
func (s *NFLSeasonPlayerThirddownStatsService) Get(ctx context.Context, id int64) (*NFLSeasonPlayerThirddownStat, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nfl/season_player_thirddown_stats/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NFLSeasonPlayerThirddownStat
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nfl.season_player_thirddown_stats, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NFLSeasonPlayerThirddownStatsService) All(ctx context.Context, params *NFLSeasonPlayerThirddownStatsListParams) iter.Seq2[NFLSeasonPlayerThirddownStat, error] {
	return func(yield func(NFLSeasonPlayerThirddownStat, error) bool) {
		page := NFLSeasonPlayerThirddownStatsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NFLSeasonPlayerThirddownStat
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
