// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nfl.team_player_rosters (public API).
// Source: schema/api/groups/public.yml + schema/model/nfl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NFLTeamPlayerRoster is a row from nfl.team_player_rosters.
type NFLTeamPlayerRoster struct {
	ID            int64   `json:"id"`
	PlayerID      int64   `json:"player_id"`
	SeasonID      int64   `json:"season_id"`
	TeamID        int64   `json:"team_id"`
	Day           int     `json:"day"`
	DepthOrder    *int    `json:"depth_order"`
	Position      *string `json:"position"`
	PositionGroup *string `json:"position_group"`
}

// NFLTeamPlayerRostersListParams are the query parameters for listing nfl.team_player_rosters.
type NFLTeamPlayerRostersListParams struct {
	TeamID   *int64
	PlayerID *int64
	SeasonID *int64
	Position *string
	Limit    *int
	FromID   *int64
}

func (p *NFLTeamPlayerRostersListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.TeamID != nil {
		v.Set("team_id", strconv.FormatInt(*p.TeamID, 10))
	}
	if p.PlayerID != nil {
		v.Set("player_id", strconv.FormatInt(*p.PlayerID, 10))
	}
	if p.SeasonID != nil {
		v.Set("season_id", strconv.FormatInt(*p.SeasonID, 10))
	}
	if p.Position != nil {
		v.Set("position", *p.Position)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NFLTeamPlayerRostersPage is one page of nfl.team_player_rosters results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NFLTeamPlayerRostersPage struct {
	Rows       []NFLTeamPlayerRoster `json:"team_player_rosters"`
	Limit      int                   `json:"limit"`
	NextFromID *int64                `json:"next_from_id"`
	Quota      Quota                 `json:"-"`
}

// NFLTeamPlayerRostersService accesses the nfl.team_player_rosters endpoints.
type NFLTeamPlayerRostersService struct {
	client *Client
}

// List returns one page of nfl.team_player_rosters matching params
// (pass nil for no filters).
func (s *NFLTeamPlayerRostersService) List(ctx context.Context, params *NFLTeamPlayerRostersListParams) (*NFLTeamPlayerRostersPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nfl/team_player_rosters", params.values())
	if err != nil {
		return nil, err
	}
	var page NFLTeamPlayerRostersPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nfl.team_player_rosters row by id.
func (s *NFLTeamPlayerRostersService) Get(ctx context.Context, id int64) (*NFLTeamPlayerRoster, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nfl/team_player_rosters/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NFLTeamPlayerRoster
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nfl.team_player_rosters, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NFLTeamPlayerRostersService) All(ctx context.Context, params *NFLTeamPlayerRostersListParams) iter.Seq2[NFLTeamPlayerRoster, error] {
	return func(yield func(NFLTeamPlayerRoster, error) bool) {
		page := NFLTeamPlayerRostersListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NFLTeamPlayerRoster
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
