// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nhl.draft_picks (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NHLDraftPick is a row from nhl.draft_picks.
type NHLDraftPick struct {
	ID             int64  `json:"id"`
	DraftID        *int   `json:"draft_id"`
	OriginalTeamID *int   `json:"original_team_id"`
	PlayerID       *int64 `json:"player_id"`
	TeamID         int64  `json:"team_id"`
	OverallPick    int    `json:"overall_pick"`
	PickInRound    int    `json:"pick_in_round"`
	Round          int    `json:"round"`
	Year           int    `json:"year"`
}

// NHLDraftPicksListParams are the query parameters for listing nhl.draft_picks.
type NHLDraftPicksListParams struct {
	Year     *int
	TeamID   *int64
	PlayerID *int64
	Limit    *int
	FromID   *int64
}

func (p *NHLDraftPicksListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Year != nil {
		v.Set("year", strconv.Itoa(*p.Year))
	}
	if p.TeamID != nil {
		v.Set("team_id", strconv.FormatInt(*p.TeamID, 10))
	}
	if p.PlayerID != nil {
		v.Set("player_id", strconv.FormatInt(*p.PlayerID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NHLDraftPicksPage is one page of nhl.draft_picks results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NHLDraftPicksPage struct {
	Rows       []NHLDraftPick `json:"draft_picks"`
	Limit      int            `json:"limit"`
	NextFromID *int64         `json:"next_from_id"`
	Quota      Quota          `json:"-"`
}

// NHLDraftPicksService accesses the nhl.draft_picks endpoints.
type NHLDraftPicksService struct {
	client *Client
}

// List returns one page of nhl.draft_picks matching params
// (pass nil for no filters).
func (s *NHLDraftPicksService) List(ctx context.Context, params *NHLDraftPicksListParams) (*NHLDraftPicksPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nhl/draft_picks", params.values())
	if err != nil {
		return nil, err
	}
	var page NHLDraftPicksPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nhl.draft_picks row by id.
func (s *NHLDraftPicksService) Get(ctx context.Context, id int64) (*NHLDraftPick, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nhl/draft_picks/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NHLDraftPick
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nhl.draft_picks, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NHLDraftPicksService) All(ctx context.Context, params *NHLDraftPicksListParams) iter.Seq2[NHLDraftPick, error] {
	return func(yield func(NHLDraftPick, error) bool) {
		page := NHLDraftPicksListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NHLDraftPick
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
