// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nhl.standings (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NHLStanding is a row from nhl.standings.
type NHLStanding struct {
	ID                       int64   `json:"id"`
	SeasonID                 int64   `json:"season_id"`
	TeamID                   int64   `json:"team_id"`
	AwayLosses               int     `json:"away_losses"`
	AwayOvertimeLosses       int     `json:"away_overtime_losses"`
	AwayWins                 int     `json:"away_wins"`
	ClinchedConference       bool    `json:"clinched_conference"`
	ClinchedDivision         bool    `json:"clinched_division"`
	ClinchedPlayoffs         bool    `json:"clinched_playoffs"`
	ClinchedPresidentsTrophy bool    `json:"clinched_presidents_trophy"`
	Conference               string  `json:"conference"`
	ConferenceRank           int     `json:"conference_rank"`
	Division                 string  `json:"division"`
	DivisionRank             int     `json:"division_rank"`
	GamesPlayed              int     `json:"games_played"`
	GoalDifferential         int     `json:"goal_differential"`
	GoalsAgainst             int     `json:"goals_against"`
	GoalsFor                 int     `json:"goals_for"`
	HomeLosses               int     `json:"home_losses"`
	HomeOvertimeLosses       int     `json:"home_overtime_losses"`
	HomeWins                 int     `json:"home_wins"`
	Last10Losses             int     `json:"last_10_losses"`
	Last10OvertimeLosses     int     `json:"last_10_overtime_losses"`
	Last10Wins               int     `json:"last_10_wins"`
	Losses                   int     `json:"losses"`
	OvertimeLosses           int     `json:"overtime_losses"`
	Pts                      int     `json:"pts"`
	PtsPercentage            float64 `json:"pts_percentage"`
	Rank                     int     `json:"rank"`
	RegulationWins           int     `json:"regulation_wins"`
	SeasonType               string  `json:"season_type"`
	ShootoutLosses           int     `json:"shootout_losses"`
	ShootoutWins             int     `json:"shootout_wins"`
	Streak                   *string `json:"streak"`
	WildCardRank             *int    `json:"wild_card_rank"`
	Wins                     int     `json:"wins"`
}

// NHLStandingsListParams are the query parameters for listing nhl.standings.
type NHLStandingsListParams struct {
	SeasonID *int64
	TeamID   *int64
	Limit    *int
	FromID   *int64
}

func (p *NHLStandingsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.SeasonID != nil {
		v.Set("season_id", strconv.FormatInt(*p.SeasonID, 10))
	}
	if p.TeamID != nil {
		v.Set("team_id", strconv.FormatInt(*p.TeamID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NHLStandingsPage is one page of nhl.standings results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NHLStandingsPage struct {
	Rows       []NHLStanding `json:"standings"`
	Limit      int           `json:"limit"`
	NextFromID *int64        `json:"next_from_id"`
	Quota      Quota         `json:"-"`
}

// NHLStandingsService accesses the nhl.standings endpoints.
type NHLStandingsService struct {
	client *Client
}

// List returns one page of nhl.standings matching params
// (pass nil for no filters).
func (s *NHLStandingsService) List(ctx context.Context, params *NHLStandingsListParams) (*NHLStandingsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nhl/standings", params.values())
	if err != nil {
		return nil, err
	}
	var page NHLStandingsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nhl.standings row by id.
func (s *NHLStandingsService) Get(ctx context.Context, id int64) (*NHLStanding, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nhl/standings/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NHLStanding
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nhl.standings, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NHLStandingsService) All(ctx context.Context, params *NHLStandingsListParams) iter.Seq2[NHLStanding, error] {
	return func(yield func(NHLStanding, error) bool) {
		page := NHLStandingsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NHLStanding
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
