// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nhl.playoff_series (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NHLPlayoffSery is a row from nhl.playoff_series.
type NHLPlayoffSery struct {
	ID           int64   `json:"id"`
	AwayTeamID   int64   `json:"away_team_id"`
	HomeTeamID   int64   `json:"home_team_id"`
	SeasonID     int64   `json:"season_id"`
	SeriesID     *int    `json:"series_id"`
	WinnerTeamID *int64  `json:"winner_team_id"`
	AwayTeamSeed int     `json:"away_team_seed"`
	AwayTeamWins int     `json:"away_team_wins"`
	Conference   *string `json:"conference"`
	GamesPlayed  int     `json:"games_played"`
	HomeTeamSeed int     `json:"home_team_seed"`
	HomeTeamWins int     `json:"home_team_wins"`
	MaxGames     int     `json:"max_games"`
	PlayoffRound string  `json:"playoff_round"`
	Status       string  `json:"status"`
}

// NHLPlayoffSeriesListParams are the query parameters for listing nhl.playoff_series.
type NHLPlayoffSeriesListParams struct {
	SeasonID   *int64
	HomeTeamID *int64
	AwayTeamID *int64
	Limit      *int
	FromID     *int64
}

func (p *NHLPlayoffSeriesListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.SeasonID != nil {
		v.Set("season_id", strconv.FormatInt(*p.SeasonID, 10))
	}
	if p.HomeTeamID != nil {
		v.Set("home_team_id", strconv.FormatInt(*p.HomeTeamID, 10))
	}
	if p.AwayTeamID != nil {
		v.Set("away_team_id", strconv.FormatInt(*p.AwayTeamID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NHLPlayoffSeriesPage is one page of nhl.playoff_series results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NHLPlayoffSeriesPage struct {
	Rows       []NHLPlayoffSery `json:"playoff_series"`
	Limit      int              `json:"limit"`
	NextFromID *int64           `json:"next_from_id"`
	Quota      Quota            `json:"-"`
}

// NHLPlayoffSeriesService accesses the nhl.playoff_series endpoints.
type NHLPlayoffSeriesService struct {
	client *Client
}

// List returns one page of nhl.playoff_series matching params
// (pass nil for no filters).
func (s *NHLPlayoffSeriesService) List(ctx context.Context, params *NHLPlayoffSeriesListParams) (*NHLPlayoffSeriesPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nhl/playoff_series", params.values())
	if err != nil {
		return nil, err
	}
	var page NHLPlayoffSeriesPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nhl.playoff_series row by id.
func (s *NHLPlayoffSeriesService) Get(ctx context.Context, id int64) (*NHLPlayoffSery, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nhl/playoff_series/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NHLPlayoffSery
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nhl.playoff_series, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NHLPlayoffSeriesService) All(ctx context.Context, params *NHLPlayoffSeriesListParams) iter.Seq2[NHLPlayoffSery, error] {
	return func(yield func(NHLPlayoffSery, error) bool) {
		page := NHLPlayoffSeriesListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NHLPlayoffSery
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
