// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for nhl.seasons (public API).
// Source: schema/api/groups/public.yml + schema/model/nhl/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// NHLSeason is a row from nhl.seasons.
type NHLSeason struct {
	ID                     int64   `json:"id"`
	LeagueID               *string `json:"league_id"`
	EndDate                *string `json:"end_date"`
	PostSeasonStartDate    *string `json:"post_season_start_date"`
	RegularSeasonStartDate *string `json:"regular_season_start_date"`
	StanleyCupFinalsDate   *string `json:"stanley_cup_finals_date"`
	StartDate              string  `json:"start_date"`
	StartYear              int     `json:"start_year"`
}

// NHLSeasonsListParams are the query parameters for listing nhl.seasons.
type NHLSeasonsListParams struct {
	Limit  *int
	FromID *int64
}

func (p *NHLSeasonsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// NHLSeasonsPage is one page of nhl.seasons results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type NHLSeasonsPage struct {
	Rows       []NHLSeason `json:"seasons"`
	Limit      int         `json:"limit"`
	NextFromID *int64      `json:"next_from_id"`
	Quota      Quota       `json:"-"`
}

// NHLSeasonsService accesses the nhl.seasons endpoints.
type NHLSeasonsService struct {
	client *Client
}

// List returns one page of nhl.seasons matching params
// (pass nil for no filters).
func (s *NHLSeasonsService) List(ctx context.Context, params *NHLSeasonsListParams) (*NHLSeasonsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/nhl/seasons", params.values())
	if err != nil {
		return nil, err
	}
	var page NHLSeasonsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single nhl.seasons row by id.
func (s *NHLSeasonsService) Get(ctx context.Context, id int64) (*NHLSeason, error) {
	body, _, err := s.client.get(ctx, "/api/v1/nhl/seasons/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row NHLSeason
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates nhl.seasons, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *NHLSeasonsService) All(ctx context.Context, params *NHLSeasonsListParams) iter.Seq2[NHLSeason, error] {
	return func(yield func(NHLSeason, error) bool) {
		page := NHLSeasonsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero NHLSeason
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
