// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for pga.tours (public API).
// Source: schema/api/groups/public.yml + schema/model/golf/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// PGATour is a row from pga.tours.
type PGATour struct {
	ID          int64   `json:"id"`
	TourID      int     `json:"tour_id"`
	Active      bool    `json:"active"`
	Code        string  `json:"code"`
	Description *string `json:"description"`
	LogoURL     *string `json:"logo_url"`
	Name        string  `json:"name"`
}

// PGAToursListParams are the query parameters for listing pga.tours.
type PGAToursListParams struct {
	Active *bool
	Limit  *int
	FromID *int64
}

func (p *PGAToursListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Active != nil {
		v.Set("active", strconv.FormatBool(*p.Active))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// PGAToursPage is one page of pga.tours results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type PGAToursPage struct {
	Rows       []PGATour `json:"tours"`
	Limit      int       `json:"limit"`
	NextFromID *int64    `json:"next_from_id"`
	Quota      Quota     `json:"-"`
}

// PGAToursService accesses the pga.tours endpoints.
type PGAToursService struct {
	client *Client
}

// List returns one page of pga.tours matching params
// (pass nil for no filters).
func (s *PGAToursService) List(ctx context.Context, params *PGAToursListParams) (*PGAToursPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/pga/tours", params.values())
	if err != nil {
		return nil, err
	}
	var page PGAToursPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single pga.tours row by id.
func (s *PGAToursService) Get(ctx context.Context, id int64) (*PGATour, error) {
	body, _, err := s.client.get(ctx, "/api/v1/pga/tours/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row PGATour
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates pga.tours, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *PGAToursService) All(ctx context.Context, params *PGAToursListParams) iter.Seq2[PGATour, error] {
	return func(yield func(PGATour, error) bool) {
		page := PGAToursListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero PGATour
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
