// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for pga.leaderboards (public API).
// Source: schema/api/groups/public.yml + schema/model/golf/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// PGALeaderboard is a row from pga.leaderboards.
type PGALeaderboard struct {
	ID                  int64    `json:"id"`
	PlayerID            int64    `json:"player_id"`
	PlayerTournamentID  int      `json:"player_tournament_id"`
	TournamentID        int64    `json:"tournament_id"`
	Earnings            *int64   `json:"earnings"`
	FedexPts            *int     `json:"fedex_pts"`
	IsAlternate         *bool    `json:"is_alternate"`
	IsWithdrawn         *bool    `json:"is_withdrawn"`
	MadeCut             *int     `json:"made_cut"`
	MadeCutDidNotFinish *bool    `json:"made_cut_did_not_finish"`
	Rank                *int     `json:"rank"`
	SgApproach          *float64 `json:"sg_approach"`
	SgAroundGreen       *float64 `json:"sg_around_green"`
	SgOffTee            *float64 `json:"sg_off_tee"`
	SgPutting           *float64 `json:"sg_putting"`
	SgTeeToGreen        *float64 `json:"sg_tee_to_green"`
	SgTotal             *float64 `json:"sg_total"`
	TeeTime             *string  `json:"tee_time"`
	TotalScore          *int     `json:"total_score"`
	TotalStrokes        *int     `json:"total_strokes"`
	TotalThrough        *int     `json:"total_through"`
	TournamentStatus    *string  `json:"tournament_status"`
	Win                 *int     `json:"win"`
}

// PGALeaderboardsListParams are the query parameters for listing pga.leaderboards.
type PGALeaderboardsListParams struct {
	TournamentID *int64
	PlayerID     *int64
	Limit        *int
	FromID       *int64
}

func (p *PGALeaderboardsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.TournamentID != nil {
		v.Set("tournament_id", strconv.FormatInt(*p.TournamentID, 10))
	}
	if p.PlayerID != nil {
		v.Set("player_id", strconv.FormatInt(*p.PlayerID, 10))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// PGALeaderboardsPage is one page of pga.leaderboards results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type PGALeaderboardsPage struct {
	Rows       []PGALeaderboard `json:"leaderboards"`
	Limit      int              `json:"limit"`
	NextFromID *int64           `json:"next_from_id"`
	Quota      Quota            `json:"-"`
}

// PGALeaderboardsService accesses the pga.leaderboards endpoints.
type PGALeaderboardsService struct {
	client *Client
}

// List returns one page of pga.leaderboards matching params
// (pass nil for no filters).
func (s *PGALeaderboardsService) List(ctx context.Context, params *PGALeaderboardsListParams) (*PGALeaderboardsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/pga/leaderboards", params.values())
	if err != nil {
		return nil, err
	}
	var page PGALeaderboardsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single pga.leaderboards row by id.
func (s *PGALeaderboardsService) Get(ctx context.Context, id int64) (*PGALeaderboard, error) {
	body, _, err := s.client.get(ctx, "/api/v1/pga/leaderboards/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row PGALeaderboard
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates pga.leaderboards, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *PGALeaderboardsService) All(ctx context.Context, params *PGALeaderboardsListParams) iter.Seq2[PGALeaderboard, error] {
	return func(yield func(PGALeaderboard, error) bool) {
		page := PGALeaderboardsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero PGALeaderboard
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
