// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for pga.courses (public API).
// Source: schema/api/groups/public.yml + schema/model/golf/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// PGACourse is a row from pga.courses.
type PGACourse struct {
	ID             int64    `json:"id"`
	LeagueCourseID *int     `json:"league_course_id"`
	Address        *string  `json:"address"`
	City           *string  `json:"city"`
	Country        *string  `json:"country"`
	Elevation      *float64 `json:"elevation"`
	ImageURL       *string  `json:"image_url"`
	Latitude       *float64 `json:"latitude"`
	Longitude      *float64 `json:"longitude"`
	Name           string   `json:"name"`
	Par            int      `json:"par"`
	State          *string  `json:"state"`
	Timezone       *string  `json:"timezone"`
	Yards          int      `json:"yards"`
	Zip            *string  `json:"zip"`
}

// PGACoursesListParams are the query parameters for listing pga.courses.
type PGACoursesListParams struct {
	Limit  *int
	FromID *int64
}

func (p *PGACoursesListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// PGACoursesPage is one page of pga.courses results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type PGACoursesPage struct {
	Rows       []PGACourse `json:"courses"`
	Limit      int         `json:"limit"`
	NextFromID *int64      `json:"next_from_id"`
	Quota      Quota       `json:"-"`
}

// PGACoursesService accesses the pga.courses endpoints.
type PGACoursesService struct {
	client *Client
}

// List returns one page of pga.courses matching params
// (pass nil for no filters).
func (s *PGACoursesService) List(ctx context.Context, params *PGACoursesListParams) (*PGACoursesPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/pga/courses", params.values())
	if err != nil {
		return nil, err
	}
	var page PGACoursesPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single pga.courses row by id.
func (s *PGACoursesService) Get(ctx context.Context, id int64) (*PGACourse, error) {
	body, _, err := s.client.get(ctx, "/api/v1/pga/courses/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row PGACourse
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates pga.courses, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *PGACoursesService) All(ctx context.Context, params *PGACoursesListParams) iter.Seq2[PGACourse, error] {
	return func(yield func(PGACourse, error) bool) {
		page := PGACoursesListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero PGACourse
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
