// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for pga.player_news (public API).
// Source: schema/api/groups/public.yml + schema/model/golf/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// PGAPlayerNew is a row from pga.player_news.
type PGAPlayerNew struct {
	ID                int64            `json:"id"`
	PlayerID          *int64           `json:"player_id"`
	TournamentID      *int64           `json:"tournament_id"`
	AiProcessed       bool             `json:"ai_processed"`
	Author            *string          `json:"author"`
	Categories        *string          `json:"categories"`
	Content           *string          `json:"content"`
	NewsTime          string           `json:"news_time"`
	OriginalSource    *string          `json:"original_source"`
	OriginalSourceURL *string          `json:"original_source_url"`
	Priority          int              `json:"priority"`
	SituationalImpact *json.RawMessage `json:"situational_impact"`
	Source            *string          `json:"source"`
	TermsOfUse        *string          `json:"terms_of_use"`
	Title             string           `json:"title"`
	UpdatedTime       *string          `json:"updated_time"`
	URL               *string          `json:"url"`
}

// PGAPlayerNewsListParams are the query parameters for listing pga.player_news.
type PGAPlayerNewsListParams struct {
	PlayerID     *int64
	TournamentID *int64
	NewsTime     *string
	Limit        *int
	FromID       *int64
}

func (p *PGAPlayerNewsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.PlayerID != nil {
		v.Set("player_id", strconv.FormatInt(*p.PlayerID, 10))
	}
	if p.TournamentID != nil {
		v.Set("tournament_id", strconv.FormatInt(*p.TournamentID, 10))
	}
	if p.NewsTime != nil {
		v.Set("news_time", *p.NewsTime)
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// PGAPlayerNewsPage is one page of pga.player_news results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type PGAPlayerNewsPage struct {
	Rows       []PGAPlayerNew `json:"player_news"`
	Limit      int            `json:"limit"`
	NextFromID *int64         `json:"next_from_id"`
	Quota      Quota          `json:"-"`
}

// PGAPlayerNewsService accesses the pga.player_news endpoints.
type PGAPlayerNewsService struct {
	client *Client
}

// List returns one page of pga.player_news matching params
// (pass nil for no filters).
func (s *PGAPlayerNewsService) List(ctx context.Context, params *PGAPlayerNewsListParams) (*PGAPlayerNewsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/pga/player_news", params.values())
	if err != nil {
		return nil, err
	}
	var page PGAPlayerNewsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single pga.player_news row by id.
func (s *PGAPlayerNewsService) Get(ctx context.Context, id int64) (*PGAPlayerNew, error) {
	body, _, err := s.client.get(ctx, "/api/v1/pga/player_news/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row PGAPlayerNew
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates pga.player_news, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *PGAPlayerNewsService) All(ctx context.Context, params *PGAPlayerNewsListParams) iter.Seq2[PGAPlayerNew, error] {
	return func(yield func(PGAPlayerNew, error) bool) {
		page := PGAPlayerNewsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero PGAPlayerNew
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
