// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for polymarket.sports (public API).
// Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// PolymarketSport is a row from polymarket.sports.
type PolymarketSport struct {
	ID      int64  `json:"id"`
	SportID *int   `json:"sport_id"`
	Name    string `json:"name"`
	TagSlug string `json:"tag_slug"`
}

// PolymarketSportsListParams are the query parameters for listing polymarket.sports.
type PolymarketSportsListParams struct {
	Limit  *int
	FromID *int64
}

func (p *PolymarketSportsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// PolymarketSportsPage is one page of polymarket.sports results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type PolymarketSportsPage struct {
	Rows       []PolymarketSport `json:"sports"`
	Limit      int               `json:"limit"`
	NextFromID *int64            `json:"next_from_id"`
	Quota      Quota             `json:"-"`
}

// PolymarketSportsService accesses the polymarket.sports endpoints.
type PolymarketSportsService struct {
	client *Client
}

// List returns one page of polymarket.sports matching params
// (pass nil for no filters).
func (s *PolymarketSportsService) List(ctx context.Context, params *PolymarketSportsListParams) (*PolymarketSportsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/polymarket/sports", params.values())
	if err != nil {
		return nil, err
	}
	var page PolymarketSportsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single polymarket.sports row by id.
func (s *PolymarketSportsService) Get(ctx context.Context, id int64) (*PolymarketSport, error) {
	body, _, err := s.client.get(ctx, "/api/v1/polymarket/sports/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row PolymarketSport
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates polymarket.sports, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *PolymarketSportsService) All(ctx context.Context, params *PolymarketSportsListParams) iter.Seq2[PolymarketSport, error] {
	return func(yield func(PolymarketSport, error) bool) {
		page := PolymarketSportsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero PolymarketSport
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
