// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for polymarket.price_histories (public API).
// Source: schema/api/groups/public.yml + schema/model/polymarket/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// PolymarketPriceHistory is a row from polymarket.price_histories.
type PolymarketPriceHistory struct {
	ID              int64  `json:"id"`
	MarketID        int64  `json:"market_id"`
	TokenID         string `json:"token_id"`
	CloseBps        int    `json:"close_bps"`
	HighBps         int    `json:"high_bps"`
	IntervalSeconds int    `json:"interval_seconds"`
	LowBps          int    `json:"low_bps"`
	OpenBps         int    `json:"open_bps"`
	PeriodStart     string `json:"period_start"`
	Volume          *int64 `json:"volume"`
}

// PolymarketPriceHistoriesListParams are the query parameters for listing polymarket.price_histories.
type PolymarketPriceHistoriesListParams struct {
	TokenID         *string
	MarketID        *int64
	IntervalSeconds *int
	Limit           *int
	FromID          *int64
}

func (p *PolymarketPriceHistoriesListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.TokenID != nil {
		v.Set("token_id", *p.TokenID)
	}
	if p.MarketID != nil {
		v.Set("market_id", strconv.FormatInt(*p.MarketID, 10))
	}
	if p.IntervalSeconds != nil {
		v.Set("interval_seconds", strconv.Itoa(*p.IntervalSeconds))
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// PolymarketPriceHistoriesPage is one page of polymarket.price_histories results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type PolymarketPriceHistoriesPage struct {
	Rows       []PolymarketPriceHistory `json:"price_histories"`
	Limit      int                      `json:"limit"`
	NextFromID *int64                   `json:"next_from_id"`
	Quota      Quota                    `json:"-"`
}

// PolymarketPriceHistoriesService accesses the polymarket.price_histories endpoints.
type PolymarketPriceHistoriesService struct {
	client *Client
}

// List returns one page of polymarket.price_histories matching params
// (pass nil for no filters).
func (s *PolymarketPriceHistoriesService) List(ctx context.Context, params *PolymarketPriceHistoriesListParams) (*PolymarketPriceHistoriesPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/polymarket/price_histories", params.values())
	if err != nil {
		return nil, err
	}
	var page PolymarketPriceHistoriesPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single polymarket.price_histories row by id.
func (s *PolymarketPriceHistoriesService) Get(ctx context.Context, id int64) (*PolymarketPriceHistory, error) {
	body, _, err := s.client.get(ctx, "/api/v1/polymarket/price_histories/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row PolymarketPriceHistory
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates polymarket.price_histories, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *PolymarketPriceHistoriesService) All(ctx context.Context, params *PolymarketPriceHistoriesListParams) iter.Seq2[PolymarketPriceHistory, error] {
	return func(yield func(PolymarketPriceHistory, error) bool) {
		page := PolymarketPriceHistoriesListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero PolymarketPriceHistory
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
