// Code generated by generate-go-sdk-public.ts. DO NOT EDIT.
//
// SDK resource for reference.operators (public API).
// Source: schema/api/groups/public.yml + schema/model/main/*.yml

package statapi

import (
	"context"
	"encoding/json"
	"iter"
	"net/url"
	"strconv"
)

// ReferenceOperator is a row from reference.operators.
type ReferenceOperator struct {
	ID           int64   `json:"id"`
	Code         string  `json:"code"`
	Description  *string `json:"description"`
	IsActive     bool    `json:"is_active"`
	Name         string  `json:"name"`
	OperatorType string  `json:"operator_type"`
	WebsiteURL   *string `json:"website_url"`
}

// ReferenceOperatorsListParams are the query parameters for listing reference.operators.
type ReferenceOperatorsListParams struct {
	Limit  *int
	FromID *int64
}

func (p *ReferenceOperatorsListParams) values() url.Values {
	v := url.Values{}
	if p == nil {
		return v
	}
	if p.Limit != nil {
		v.Set("limit", strconv.Itoa(*p.Limit))
	}
	if p.FromID != nil {
		v.Set("from_id", strconv.FormatInt(*p.FromID, 10))
	}
	return v
}

// ReferenceOperatorsPage is one page of reference.operators results plus the keyset
// cursor to the next page (NextFromID is nil on the final page).
type ReferenceOperatorsPage struct {
	Rows       []ReferenceOperator `json:"operators"`
	Limit      int                 `json:"limit"`
	NextFromID *int64              `json:"next_from_id"`
	Quota      Quota               `json:"-"`
}

// ReferenceOperatorsService accesses the reference.operators endpoints.
type ReferenceOperatorsService struct {
	client *Client
}

// List returns one page of reference.operators matching params
// (pass nil for no filters).
func (s *ReferenceOperatorsService) List(ctx context.Context, params *ReferenceOperatorsListParams) (*ReferenceOperatorsPage, error) {
	body, quota, err := s.client.get(ctx, "/api/v1/reference/operators", params.values())
	if err != nil {
		return nil, err
	}
	var page ReferenceOperatorsPage
	if err := json.Unmarshal(body, &page); err != nil {
		return nil, err
	}
	page.Quota = quota
	return &page, nil
}

// Get returns a single reference.operators row by id.
func (s *ReferenceOperatorsService) Get(ctx context.Context, id int64) (*ReferenceOperator, error) {
	body, _, err := s.client.get(ctx, "/api/v1/reference/operators/"+strconv.FormatInt(id, 10), nil)
	if err != nil {
		return nil, err
	}
	var row ReferenceOperator
	if err := json.Unmarshal(body, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// All auto-paginates reference.operators, walking next_from_id.
// Iteration stops on the first error, yielded with a zero-value row.
// Always walks with FromID set (starting at 0): from_id forces the server's
// ascending keyset order; without it, DESC-default tables re-yield page 1 and
// under-walk. Iteration is therefore always oldest-first.
func (s *ReferenceOperatorsService) All(ctx context.Context, params *ReferenceOperatorsListParams) iter.Seq2[ReferenceOperator, error] {
	return func(yield func(ReferenceOperator, error) bool) {
		page := ReferenceOperatorsListParams{}
		if params != nil {
			page = *params
		}
		if page.FromID == nil {
			page.FromID = new(int64)
		}
		for {
			resp, err := s.List(ctx, &page)
			if err != nil {
				var zero ReferenceOperator
				yield(zero, err)
				return
			}
			for _, row := range resp.Rows {
				if !yield(row, nil) {
					return
				}
			}
			if resp.NextFromID == nil {
				return
			}
			page.FromID = resp.NextFromID
		}
	}
}
