// Code generated by generate-sdk-smoke.ts. DO NOT EDIT.
//
// Live smoke for the statapi Go SDK. Runs six probes against STAT_API_BASE_URL
// (default https://api.stat-api.com) with STAT_API_KEY. Run: go run ./cmd/smoke
package main

import (
	"context"
	"errors"
	"fmt"
	"os"

	statapi "github.com/stat-api/stat-api/go"
)

var failures int

func pass(id, msg string) { fmt.Printf("PASS %s  %s\n", id, msg) }
func fail(id, msg string) { failures++; fmt.Printf("FAIL %s  %s\n", id, msg) }

func main() {
	baseURL := os.Getenv("STAT_API_BASE_URL")
	if baseURL == "" {
		baseURL = "https://api.stat-api.com"
	}
	key := os.Getenv("STAT_API_KEY")
	if key == "" {
		fmt.Fprintln(os.Stderr, "STAT_API_KEY is required")
		os.Exit(2)
	}
	ctx := context.Background()

	client, err := statapi.NewWithOptions(statapi.Options{APIKey: key, BaseURL: baseURL})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}

	// probe1 — plain list
	var firstID int64
	haveFirst := false
	if page, err := client.NBA.Teams.List(ctx, &statapi.NBATeamsListParams{Limit: statapi.Int(2)}); err != nil {
		fail("probe1-list", err.Error())
	} else if len(page.Rows) >= 1 {
		firstID = page.Rows[0].ID
		haveFirst = true
		pass("probe1-list", fmt.Sprintf("nba.teams limit=2 -> %d rows", len(page.Rows)))
	} else {
		fail("probe1-list", "nba.teams returned 0 rows")
	}

	// probe2 — required-filter-set table via smoke params
	if page, err := client.DFS.ContestUsers.List(ctx, &statapi.DFSContestUsersListParams{OperatorID: statapi.Int64(1)}); err != nil {
		fail("probe2-required-set", err.Error())
	} else {
		pass("probe2-required-set", fmt.Sprintf("dfs.contest_users via smoke params -> %d rows", len(page.Rows)))
	}

	// probe3 — get(id)
	if !haveFirst {
		fail("probe3-get", "no id from probe1")
	} else if row, err := client.NBA.Teams.Get(ctx, firstID); err != nil {
		fail("probe3-get", err.Error())
	} else if row.ID == firstID {
		pass("probe3-get", fmt.Sprintf("get(%d) ok", firstID))
	} else {
		fail("probe3-get", fmt.Sprintf("id mismatch %d", row.ID))
	}

	// probe4 — two-page keyset walk
	if p1, err := client.NBA.Teams.List(ctx, &statapi.NBATeamsListParams{Limit: statapi.Int(2)}); err != nil {
		fail("probe4-paginate", err.Error())
	} else if p1.NextFromID == nil {
		fail("probe4-paginate", "page1 next_from_id is nil")
	} else {
		cursor := *p1.NextFromID
		if p2, err := client.NBA.Teams.List(ctx, &statapi.NBATeamsListParams{Limit: statapi.Int(2), FromID: &cursor}); err != nil {
			fail("probe4-paginate", err.Error())
		} else {
			advanced := len(p2.Rows) >= 1
			for _, r := range p2.Rows {
				if r.ID <= cursor {
					advanced = false
				}
			}
			if advanced {
				pass("probe4-paginate", fmt.Sprintf("page2 ids advance past %d", cursor))
			} else {
				fail("probe4-paginate", "page2 did not advance")
			}
		}
	}

	// probe5 — bad key -> AuthenticationError
	if badClient, err := statapi.NewWithOptions(statapi.Options{APIKey: "sdb_bad_00000000000000000000000000000000", BaseURL: baseURL}); err != nil {
		fail("probe5-auth", err.Error())
	} else {
		_, err := badClient.NBA.Teams.List(ctx, &statapi.NBATeamsListParams{Limit: statapi.Int(2)})
		var authErr *statapi.AuthenticationError
		if errors.As(err, &authErr) {
			pass("probe5-auth", "bad key -> AuthenticationError")
		} else {
			fail("probe5-auth", fmt.Sprintf("wrong error: %v", err))
		}
	}

	// probe6 — quota surfaced on the list Page
	if page, err := client.NBA.Teams.List(ctx, &statapi.NBATeamsListParams{Limit: statapi.Int(2)}); err != nil {
		fail("probe6-quota", err.Error())
	} else if page.Quota.Present {
		pass("probe6-quota", fmt.Sprintf("quota surfaced (limit=%d)", page.Quota.Limit))
	} else {
		fail("probe6-quota", "no quota on list response")
	}

	if failures == 0 {
		os.Exit(0)
	}
	os.Exit(1)
}
