// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for kalshi.markets (public API).
// Source: schema/api/groups/public.yml + schema/model/kalshi/*.yml
package com.statapi.kalshi;

import com.statapi.JsonValue;

public record KalshiMarket(
    Long id,
    Long competitionId,
    Long eventId,
    Long seriesId,
    String closeTime,
    String contractType,
    String expirationTime,
    Integer lastPrice,
    Double line,
    Integer liquidity,
    Integer openInterest,
    String openTime,
    String result,
    String settledAt,
    Integer settlementValue,
    String status,
    String subtitle,
    String ticker,
    String title,
    Integer volume,
    Integer yesAsk,
    Integer yesBid
) {

    public static KalshiMarket fromJson(JsonValue json) {
        return new KalshiMarket(
            json.get("id").asLong(),
            json.get("competition_id").asLong(),
            json.get("event_id").asLong(),
            json.get("series_id").asLong(),
            json.get("close_time").asString(),
            json.get("contract_type").asString(),
            json.get("expiration_time").asString(),
            json.get("last_price").asInt(),
            json.get("line").asDouble(),
            json.get("liquidity").asInt(),
            json.get("open_interest").asInt(),
            json.get("open_time").asString(),
            json.get("result").asString(),
            json.get("settled_at").asString(),
            json.get("settlement_value").asInt(),
            json.get("status").asString(),
            json.get("subtitle").asString(),
            json.get("ticker").asString(),
            json.get("title").asString(),
            json.get("volume").asInt(),
            json.get("yes_ask").asInt(),
            json.get("yes_bid").asInt()
        );
    }
}
