// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for kalshi.market_statuses (public API).
// Source: schema/api/groups/public.yml + schema/model/kalshi/*.yml
package com.statapi.kalshi;

import com.statapi.JsonValue;

public record KalshiMarketStatus(
    Long id,
    JsonValue details,
    String endTs,
    String startTs,
    String status,
    String ticker
) {

    public static KalshiMarketStatus fromJson(JsonValue json) {
        return new KalshiMarketStatus(
            json.get("id").asLong(),
            json.get("details"),
            json.get("end_ts").asString(),
            json.get("start_ts").asString(),
            json.get("status").asString(),
            json.get("ticker").asString()
        );
    }
}
