// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK row for kalshi.events (public API).
// Source: schema/api/groups/public.yml + schema/model/kalshi/*.yml
package com.statapi.kalshi;

import com.statapi.JsonValue;

public record KalshiEvent(
    Long id,
    Long competitionId,
    String leagueGameId,
    Long seriesId,
    String awayTeam,
    String category,
    String eventTicker,
    String gameDate,
    String homeTeam,
    String leagueCode,
    Integer marketCount,
    String settledAt,
    String status,
    String title
) {

    public static KalshiEvent fromJson(JsonValue json) {
        return new KalshiEvent(
            json.get("id").asLong(),
            json.get("competition_id").asLong(),
            json.get("league_game_id").asString(),
            json.get("series_id").asLong(),
            json.get("away_team").asString(),
            json.get("category").asString(),
            json.get("event_ticker").asString(),
            json.get("game_date").asString(),
            json.get("home_team").asString(),
            json.get("league_code").asString(),
            json.get("market_count").asInt(),
            json.get("settled_at").asString(),
            json.get("status").asString(),
            json.get("title").asString()
        );
    }
}
