// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// SDK list params for kalshi.public_trades (public API).
// Source: schema/api/groups/public.yml + schema/model/kalshi/*.yml
package com.statapi.kalshi;

import java.util.LinkedHashMap;
import java.util.Map;

public final class KalshiPublicTradesListParams {

    private Long marketId;
    private Long limit;
    private Long fromId;

    public KalshiPublicTradesListParams marketId(Long marketId) {
        this.marketId = marketId;
        return this;
    }

    public KalshiPublicTradesListParams limit(Long limit) {
        this.limit = limit;
        return this;
    }

    public KalshiPublicTradesListParams fromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public Map<String, String> toQuery() {
        Map<String, String> query = new LinkedHashMap<>();
        if (marketId != null) {
            query.put("market_id", String.valueOf(marketId));
        }
        if (limit != null) {
            query.put("limit", String.valueOf(limit));
        }
        if (fromId != null) {
            query.put("from_id", String.valueOf(fromId));
        }
        return query;
    }
}
