// DO NOT EDIT — generated by generate-java-sdk-public.ts
//
// Resource accessor for the kalshi league (public API).
package com.statapi.kalshi;

import com.statapi.Http;

public final class KalshiApi {

    private final KalshiSeriesResource series;
    private final KalshiMarketStatusesResource marketStatuses;
    private final KalshiEventsResource events;
    private final KalshiMarketsResource markets;
    private final KalshiCandlesResource candles;
    private final KalshiMarketSnapshotsResource marketSnapshots;
    private final KalshiPublicTradesResource publicTrades;

    public KalshiApi(Http http) {
        this.series = new KalshiSeriesResource(http);
        this.marketStatuses = new KalshiMarketStatusesResource(http);
        this.events = new KalshiEventsResource(http);
        this.markets = new KalshiMarketsResource(http);
        this.candles = new KalshiCandlesResource(http);
        this.marketSnapshots = new KalshiMarketSnapshotsResource(http);
        this.publicTrades = new KalshiPublicTradesResource(http);
    }

    public KalshiSeriesResource series() {
        return series;
    }

    public KalshiMarketStatusesResource marketStatuses() {
        return marketStatuses;
    }

    public KalshiEventsResource events() {
        return events;
    }

    public KalshiMarketsResource markets() {
        return markets;
    }

    public KalshiCandlesResource candles() {
        return candles;
    }

    public KalshiMarketSnapshotsResource marketSnapshots() {
        return marketSnapshots;
    }

    public KalshiPublicTradesResource publicTrades() {
        return publicTrades;
    }
}
