# DO NOT EDIT — generated by generate-python-sdk-public.ts
#
# Client barrel composing per-league resource accessors.

from __future__ import annotations

from .transport import HttpTransport
from .dfs import (
    DFSSlatesResource,
    DFSContestUserLineupPlayerEntriesResource,
    DFSContestUsersResource,
    DFSGameStatsResource,
    DFSPlayerStatsResource,
    DFSSlatePlayerProjectionsResource,
    DFSSlateProjectionSourcesResource,
    DFSSlateSettingsResource,
    DFSTeamStatsResource,
    DFSContestsResource,
    DFSSlateGamesResource,
    DFSSlatePlayersResource,
    DFSContestUserLineupsResource,
)
from .kalshi import (
    KalshiSeriesResource,
    KalshiMarketStatusesResource,
    KalshiEventsResource,
    KalshiMarketsResource,
    KalshiCandlesResource,
    KalshiMarketSnapshotsResource,
    KalshiPublicTradesResource,
)
from .mlb import (
    MLBSeasonsResource,
    MLBVenuesResource,
    MLBUmpiresResource,
    MLBTeamsResource,
    MLBParkFactorsResource,
    MLBSeasonRunEnvironmentsResource,
    MLBVenueDimensionsResource,
    MLBWobaWeightsResource,
    MLBGamesResource,
    MLBPlayersResource,
    MLBBroadcastersResource,
    MLBOperatorTeamLookupsResource,
    MLBPlayoffsResource,
    MLBSeasonTeamStatsResource,
    MLBSeriesOddsResource,
    MLBInningsResource,
    MLBGameAltLinesResource,
    MLBGameBroadcastersResource,
    MLBGameLinesResource,
    MLBGamePeriodLinesResource,
    MLBGamePlayerBatterStatsResource,
    MLBGamePlayerPitchingStatsResource,
    MLBGamePlayerPropsResource,
    MLBGameTeamRostersResource,
    MLBGameTeamStatsResource,
    MLBGameUmpiresResource,
    MLBOperatorPlayerLookupsResource,
    MLBPitchesResource,
    MLBPlayerAwardsResource,
    MLBPlayerInjuriesResource,
    MLBPlayerNewsResource,
    MLBSeasonPlayerStatsResource,
    MLBTeamPlayerRostersResource,
    MLBTeamStartingLineupBattersResource,
    MLBTeamStartingLineupsResource,
    MLBVenueWeathersResource,
    MLBAtBatsResource,
    MLBPlayByPlaysResource,
)
from .nba import (
    NBASeasonsResource,
    NBAStadiumsResource,
    NBARefereesResource,
    NBACoachingStaffsResource,
    NBATeamsResource,
    NBAGamesResource,
    NBAPlayersResource,
    NBABroadcastersResource,
    NBAOperatorTeamLookupsResource,
    NBAPlayoffsResource,
    NBASeasonTeamStatsResource,
    NBATeamCoachingStaffsResource,
    NBATeamStandingsResource,
    NBAGameBroadcastersResource,
    NBAGameLinesResource,
    NBAGamePeriodLinesResource,
    NBAGamePlayerPropsResource,
    NBAGamePlayerStatsResource,
    NBAGamePossessionsResource,
    NBAGameRefereesResource,
    NBAGameTeamLineupStintsResource,
    NBAGameTeamRostersResource,
    NBAGameTeamStatsResource,
    NBAOperatorPlayerLookupsResource,
    NBAPlayByPlaysResource,
    NBAPlayerNewsResource,
    NBASeasonPlayerStatsResource,
    NBATeamDepthChartsResource,
    NBATeamGameContextsResource,
)
from .nfl import (
    NFLSeasonsResource,
    NFLStadiumsResource,
    NFLRefereesResource,
    NFLTeamsResource,
    NFLPlayersResource,
    NFLGamesResource,
    NFLCoachingStaffTenuresResource,
    NFLCoachingStaffsResource,
    NFLDepthChartSnapshotsResource,
    NFLOperatorTeamLookupsResource,
    NFLPlayoffsResource,
    NFLSeasonTeamStatsResource,
    NFLCombineResultsResource,
    NFLDepthChartEntriesResource,
    NFLDepthChartsResource,
    NFLDraftPicksResource,
    NFLGameDrivesResource,
    NFLGameLinesResource,
    NFLGamePlayerFirstdownStatsResource,
    NFLGamePlayerNgsPassingsResource,
    NFLGamePlayerNgsReceivingsResource,
    NFLGamePlayerNgsRushingsResource,
    NFLGamePlayerPfrAdvstatsResource,
    NFLGamePlayerRedzoneStatsResource,
    NFLGamePlayerStatsResource,
    NFLGamePlayerThirddownStatsResource,
    NFLGameRefereesResource,
    NFLGameTeamRostersResource,
    NFLGameTeamStaffsResource,
    NFLGameTeamStatsResource,
    NFLGameWeathersResource,
    NFLInjuriesResource,
    NFLOperatorPlayerLookupsResource,
    NFLPlayByPlaysResource,
    NFLPlayParticipationsResource,
    NFLPlayerContractsResource,
    NFLPlayerNewsResource,
    NFLSeasonPlayerFirstdownStatsResource,
    NFLSeasonPlayerRedzoneStatsResource,
    NFLSeasonPlayerStatsResource,
    NFLSeasonPlayerThirddownStatsResource,
    NFLTeamPlayerRostersResource,
)
from .nhl import (
    NHLSeasonsResource,
    NHLArenasResource,
    NHLTeamsResource,
    NHLPlayersResource,
    NHLGamesResource,
    NHLLineCombinationsResource,
    NHLOperatorTeamLookupsResource,
    NHLPlayoffSeriesResource,
    NHLSeasonTeamStatsResource,
    NHLStandingsResource,
    NHLDraftPicksResource,
    NHLGameOddsResource,
    NHLGamePlayerStatsResource,
    NHLGameTeamStatsResource,
    NHLGoalieDepthChartsResource,
    NHLOperatorPlayerLookupsResource,
    NHLPenaltiesResource,
    NHLPeriodsResource,
    NHLPlayerInjuriesResource,
    NHLPlayerNewsResource,
    NHLScoringPlaysResource,
    NHLSeasonPlayerStatsResource,
)
from .pga import (
    PGAPlayersResource,
    PGAToursResource,
    PGACoursesResource,
    PGASeasonsResource,
    PGAOperatorPlayerLookupsResource,
    PGATournamentsResource,
    PGAPlayerSeasonStatsResource,
    PGACourseHoleStatsResource,
    PGALeaderboardsResource,
    PGAPlayerHolesResource,
    PGAPlayerNewsResource,
    PGAPlayerRoundsResource,
    PGAPlayerShotsResource,
    PGATournamentOddsResource,
    PGATournamentRoundsResource,
)
from .polymarket import (
    PolymarketEventsResource,
    PolymarketSportsResource,
    PolymarketTokensResource,
    PolymarketMarketsResource,
    PolymarketCandlesResource,
    PolymarketMarketSnapshotsResource,
    PolymarketOrderBookSnapshotsResource,
    PolymarketPriceHistoriesResource,
    PolymarketPublicTradesResource,
    PolymarketTokenSnapshotsResource,
)
from .reference import (
    ReferenceOperatorsResource,
)


class _DfsApi:
    def __init__(self, transport: HttpTransport) -> None:
        self.slates = DFSSlatesResource(transport)
        self.contest_user_lineup_player_entries = DFSContestUserLineupPlayerEntriesResource(transport)
        self.contest_users = DFSContestUsersResource(transport)
        self.game_stats = DFSGameStatsResource(transport)
        self.player_stats = DFSPlayerStatsResource(transport)
        self.slate_player_projections = DFSSlatePlayerProjectionsResource(transport)
        self.slate_projection_sources = DFSSlateProjectionSourcesResource(transport)
        self.slate_settings = DFSSlateSettingsResource(transport)
        self.team_stats = DFSTeamStatsResource(transport)
        self.contests = DFSContestsResource(transport)
        self.slate_games = DFSSlateGamesResource(transport)
        self.slate_players = DFSSlatePlayersResource(transport)
        self.contest_user_lineups = DFSContestUserLineupsResource(transport)


class _KalshiApi:
    def __init__(self, transport: HttpTransport) -> None:
        self.series = KalshiSeriesResource(transport)
        self.market_statuses = KalshiMarketStatusesResource(transport)
        self.events = KalshiEventsResource(transport)
        self.markets = KalshiMarketsResource(transport)
        self.candles = KalshiCandlesResource(transport)
        self.market_snapshots = KalshiMarketSnapshotsResource(transport)
        self.public_trades = KalshiPublicTradesResource(transport)


class _MlbApi:
    def __init__(self, transport: HttpTransport) -> None:
        self.seasons = MLBSeasonsResource(transport)
        self.venues = MLBVenuesResource(transport)
        self.umpires = MLBUmpiresResource(transport)
        self.teams = MLBTeamsResource(transport)
        self.park_factors = MLBParkFactorsResource(transport)
        self.season_run_environments = MLBSeasonRunEnvironmentsResource(transport)
        self.venue_dimensions = MLBVenueDimensionsResource(transport)
        self.woba_weights = MLBWobaWeightsResource(transport)
        self.games = MLBGamesResource(transport)
        self.players = MLBPlayersResource(transport)
        self.broadcasters = MLBBroadcastersResource(transport)
        self.operator_team_lookups = MLBOperatorTeamLookupsResource(transport)
        self.playoffs = MLBPlayoffsResource(transport)
        self.season_team_stats = MLBSeasonTeamStatsResource(transport)
        self.series_odds = MLBSeriesOddsResource(transport)
        self.innings = MLBInningsResource(transport)
        self.game_alt_lines = MLBGameAltLinesResource(transport)
        self.game_broadcasters = MLBGameBroadcastersResource(transport)
        self.game_lines = MLBGameLinesResource(transport)
        self.game_period_lines = MLBGamePeriodLinesResource(transport)
        self.game_player_batter_stats = MLBGamePlayerBatterStatsResource(transport)
        self.game_player_pitching_stats = MLBGamePlayerPitchingStatsResource(transport)
        self.game_player_props = MLBGamePlayerPropsResource(transport)
        self.game_team_rosters = MLBGameTeamRostersResource(transport)
        self.game_team_stats = MLBGameTeamStatsResource(transport)
        self.game_umpires = MLBGameUmpiresResource(transport)
        self.operator_player_lookups = MLBOperatorPlayerLookupsResource(transport)
        self.pitches = MLBPitchesResource(transport)
        self.player_awards = MLBPlayerAwardsResource(transport)
        self.player_injuries = MLBPlayerInjuriesResource(transport)
        self.player_news = MLBPlayerNewsResource(transport)
        self.season_player_stats = MLBSeasonPlayerStatsResource(transport)
        self.team_player_rosters = MLBTeamPlayerRostersResource(transport)
        self.team_starting_lineup_batters = MLBTeamStartingLineupBattersResource(transport)
        self.team_starting_lineups = MLBTeamStartingLineupsResource(transport)
        self.venue_weathers = MLBVenueWeathersResource(transport)
        self.at_bats = MLBAtBatsResource(transport)
        self.play_by_plays = MLBPlayByPlaysResource(transport)


class _NbaApi:
    def __init__(self, transport: HttpTransport) -> None:
        self.seasons = NBASeasonsResource(transport)
        self.stadiums = NBAStadiumsResource(transport)
        self.referees = NBARefereesResource(transport)
        self.coaching_staffs = NBACoachingStaffsResource(transport)
        self.teams = NBATeamsResource(transport)
        self.games = NBAGamesResource(transport)
        self.players = NBAPlayersResource(transport)
        self.broadcasters = NBABroadcastersResource(transport)
        self.operator_team_lookups = NBAOperatorTeamLookupsResource(transport)
        self.playoffs = NBAPlayoffsResource(transport)
        self.season_team_stats = NBASeasonTeamStatsResource(transport)
        self.team_coaching_staffs = NBATeamCoachingStaffsResource(transport)
        self.team_standings = NBATeamStandingsResource(transport)
        self.game_broadcasters = NBAGameBroadcastersResource(transport)
        self.game_lines = NBAGameLinesResource(transport)
        self.game_period_lines = NBAGamePeriodLinesResource(transport)
        self.game_player_props = NBAGamePlayerPropsResource(transport)
        self.game_player_stats = NBAGamePlayerStatsResource(transport)
        self.game_possessions = NBAGamePossessionsResource(transport)
        self.game_referees = NBAGameRefereesResource(transport)
        self.game_team_lineup_stints = NBAGameTeamLineupStintsResource(transport)
        self.game_team_rosters = NBAGameTeamRostersResource(transport)
        self.game_team_stats = NBAGameTeamStatsResource(transport)
        self.operator_player_lookups = NBAOperatorPlayerLookupsResource(transport)
        self.play_by_plays = NBAPlayByPlaysResource(transport)
        self.player_news = NBAPlayerNewsResource(transport)
        self.season_player_stats = NBASeasonPlayerStatsResource(transport)
        self.team_depth_charts = NBATeamDepthChartsResource(transport)
        self.team_game_contexts = NBATeamGameContextsResource(transport)


class _NflApi:
    def __init__(self, transport: HttpTransport) -> None:
        self.seasons = NFLSeasonsResource(transport)
        self.stadiums = NFLStadiumsResource(transport)
        self.referees = NFLRefereesResource(transport)
        self.teams = NFLTeamsResource(transport)
        self.players = NFLPlayersResource(transport)
        self.games = NFLGamesResource(transport)
        self.coaching_staff_tenures = NFLCoachingStaffTenuresResource(transport)
        self.coaching_staffs = NFLCoachingStaffsResource(transport)
        self.depth_chart_snapshots = NFLDepthChartSnapshotsResource(transport)
        self.operator_team_lookups = NFLOperatorTeamLookupsResource(transport)
        self.playoffs = NFLPlayoffsResource(transport)
        self.season_team_stats = NFLSeasonTeamStatsResource(transport)
        self.combine_results = NFLCombineResultsResource(transport)
        self.depth_chart_entries = NFLDepthChartEntriesResource(transport)
        self.depth_charts = NFLDepthChartsResource(transport)
        self.draft_picks = NFLDraftPicksResource(transport)
        self.game_drives = NFLGameDrivesResource(transport)
        self.game_lines = NFLGameLinesResource(transport)
        self.game_player_firstdown_stats = NFLGamePlayerFirstdownStatsResource(transport)
        self.game_player_ngs_passings = NFLGamePlayerNgsPassingsResource(transport)
        self.game_player_ngs_receivings = NFLGamePlayerNgsReceivingsResource(transport)
        self.game_player_ngs_rushings = NFLGamePlayerNgsRushingsResource(transport)
        self.game_player_pfr_advstats = NFLGamePlayerPfrAdvstatsResource(transport)
        self.game_player_redzone_stats = NFLGamePlayerRedzoneStatsResource(transport)
        self.game_player_stats = NFLGamePlayerStatsResource(transport)
        self.game_player_thirddown_stats = NFLGamePlayerThirddownStatsResource(transport)
        self.game_referees = NFLGameRefereesResource(transport)
        self.game_team_rosters = NFLGameTeamRostersResource(transport)
        self.game_team_staffs = NFLGameTeamStaffsResource(transport)
        self.game_team_stats = NFLGameTeamStatsResource(transport)
        self.game_weathers = NFLGameWeathersResource(transport)
        self.injuries = NFLInjuriesResource(transport)
        self.operator_player_lookups = NFLOperatorPlayerLookupsResource(transport)
        self.play_by_plays = NFLPlayByPlaysResource(transport)
        self.play_participations = NFLPlayParticipationsResource(transport)
        self.player_contracts = NFLPlayerContractsResource(transport)
        self.player_news = NFLPlayerNewsResource(transport)
        self.season_player_firstdown_stats = NFLSeasonPlayerFirstdownStatsResource(transport)
        self.season_player_redzone_stats = NFLSeasonPlayerRedzoneStatsResource(transport)
        self.season_player_stats = NFLSeasonPlayerStatsResource(transport)
        self.season_player_thirddown_stats = NFLSeasonPlayerThirddownStatsResource(transport)
        self.team_player_rosters = NFLTeamPlayerRostersResource(transport)


class _NhlApi:
    def __init__(self, transport: HttpTransport) -> None:
        self.seasons = NHLSeasonsResource(transport)
        self.arenas = NHLArenasResource(transport)
        self.teams = NHLTeamsResource(transport)
        self.players = NHLPlayersResource(transport)
        self.games = NHLGamesResource(transport)
        self.line_combinations = NHLLineCombinationsResource(transport)
        self.operator_team_lookups = NHLOperatorTeamLookupsResource(transport)
        self.playoff_series = NHLPlayoffSeriesResource(transport)
        self.season_team_stats = NHLSeasonTeamStatsResource(transport)
        self.standings = NHLStandingsResource(transport)
        self.draft_picks = NHLDraftPicksResource(transport)
        self.game_odds = NHLGameOddsResource(transport)
        self.game_player_stats = NHLGamePlayerStatsResource(transport)
        self.game_team_stats = NHLGameTeamStatsResource(transport)
        self.goalie_depth_charts = NHLGoalieDepthChartsResource(transport)
        self.operator_player_lookups = NHLOperatorPlayerLookupsResource(transport)
        self.penalties = NHLPenaltiesResource(transport)
        self.periods = NHLPeriodsResource(transport)
        self.player_injuries = NHLPlayerInjuriesResource(transport)
        self.player_news = NHLPlayerNewsResource(transport)
        self.scoring_plays = NHLScoringPlaysResource(transport)
        self.season_player_stats = NHLSeasonPlayerStatsResource(transport)


class _PgaApi:
    def __init__(self, transport: HttpTransport) -> None:
        self.players = PGAPlayersResource(transport)
        self.tours = PGAToursResource(transport)
        self.courses = PGACoursesResource(transport)
        self.seasons = PGASeasonsResource(transport)
        self.operator_player_lookups = PGAOperatorPlayerLookupsResource(transport)
        self.tournaments = PGATournamentsResource(transport)
        self.player_season_stats = PGAPlayerSeasonStatsResource(transport)
        self.course_hole_stats = PGACourseHoleStatsResource(transport)
        self.leaderboards = PGALeaderboardsResource(transport)
        self.player_holes = PGAPlayerHolesResource(transport)
        self.player_news = PGAPlayerNewsResource(transport)
        self.player_rounds = PGAPlayerRoundsResource(transport)
        self.player_shots = PGAPlayerShotsResource(transport)
        self.tournament_odds = PGATournamentOddsResource(transport)
        self.tournament_rounds = PGATournamentRoundsResource(transport)


class _PolymarketApi:
    def __init__(self, transport: HttpTransport) -> None:
        self.events = PolymarketEventsResource(transport)
        self.sports = PolymarketSportsResource(transport)
        self.tokens = PolymarketTokensResource(transport)
        self.markets = PolymarketMarketsResource(transport)
        self.candles = PolymarketCandlesResource(transport)
        self.market_snapshots = PolymarketMarketSnapshotsResource(transport)
        self.order_book_snapshots = PolymarketOrderBookSnapshotsResource(transport)
        self.price_histories = PolymarketPriceHistoriesResource(transport)
        self.public_trades = PolymarketPublicTradesResource(transport)
        self.token_snapshots = PolymarketTokenSnapshotsResource(transport)


class _ReferenceApi:
    def __init__(self, transport: HttpTransport) -> None:
        self.operators = ReferenceOperatorsResource(transport)


class StatApi:
    """Entry point for the stat-api sports data API.

    Reads the API key from api_key= or the STAT_API_KEY environment
    variable; the base URL from base_url=, STAT_API_BASE_URL, or
    https://api.stat-api.com.
    """

    def __init__(
        self,
        api_key: str | None = None,
        base_url: str | None = None,
        timeout: float | None = None,
    ) -> None:
        transport = HttpTransport(api_key=api_key, base_url=base_url, timeout=timeout)
        self._transport = transport
        self.dfs = _DfsApi(transport)
        self.kalshi = _KalshiApi(transport)
        self.mlb = _MlbApi(transport)
        self.nba = _NbaApi(transport)
        self.nfl = _NflApi(transport)
        self.nhl = _NhlApi(transport)
        self.pga = _PgaApi(transport)
        self.polymarket = _PolymarketApi(transport)
        self.reference = _ReferenceApi(transport)
